blevesearch/bleve

examples_test.go
This has examples for most functions required while building a query. Related to #79
=> adds examples for most query functions

examples_test.go, search.go
#79 
Is the special field mentioned anywhere else? I could not find it. If it is, the second commit can be removed.
=> adds examples for mapping functions and special field * in docs

analysis/analyzers/custom_analyzer/custom_analyzer.go
#120 Are there any tests for this analyzer? I tried writing one, but it required importing too many components, everything from tokenizers, char filters, etc... Is there a better way of writing tests for this?
=> adds handling of []string type attributes to custom analyzer

analysis/language/ar/stemmer_ar.go, analysis/language/ar/stemmer_ar_test.go
=> add arabic light stemmer

analysis/language/ar/analyzer_ar_test.go, analysis/language/ar/stemmer_ar.go
=> arabic stemmer: strip multiple suffixes

analysis/language/ar/analyzer_ar.go, analysis/language/ar/analyzer_ar_test.go, analysis/language/ar/stemmer_ar.go, analysis/language/ar/stemmer_ar_test.go
The stemmer is now the same as Lucene's (but I think we can do better) and I've added unicode normalisation to the analyzer. #150
=> Further improvements to the Arabic analyzer

error.go, query_boolean.go, query_test.go
=> Allow query string handling which contains only not must

index/upside_down/row.go
=> use binary.MaxVarintLen64

index_test.go, mapping_document.go
DocumentMapping.Dynamic was ignored by everything but the marshalling
code.
Issue #235
I do not know the codebase at all, this is a shot in the dark, but works for meTM.
=> implement document static mappings

error.go, index_impl.go, search/search.go
The last commit is highly subjective but I would argue that removing one level of nesting makes the code easier to reason about.
=> Code simplifications

index/store/boltdb/store.go
Use this option when rebuilding indexes from scratch. In my small case
(~17000 json documents), it reduces indexing from 520s to 250s.
I did not add any test, short of forced indexing termination it only
has performance effects, which are hard to test. And unknown options are
currently ignored.
Issue #240
=> boltdb: add "nosync" option to force boltdb.DB.NoSync=true

index/store/boltdb/iterator.go, index/store/boltdb/store_test.go, index/store/goleveldb/store_test.go, index/store/gtreap/iterator.go, index/store/gtreap/reader.go, index/store/gtreap/store_test.go, index/store/metrics/store_test.go, index/store/test/iterator.go
You can review this one before the documentation PR https://github.com/blevesearch/bleve/pull/253 . I will adjust and rebase the latter after the fixes are merged.
=> Fix rangeiterator seek

query.go, query_test.go
This is convenient to see either complicated queries build
programmatically, or to make sure the query parser does what it is
expected to do.
Note only queries made of bleve basic queries are supported. If we
wanted to support external queries, for instance string queries with an
alternative parser, I suggest to introduce some kind of:
```
type ExpandableQuery interface {
Query
Expand(*IndexMapping) (Query, error)
}
```
and type assert to that instead of *queryStringQuery. It would require expandQuery to be exported as well.
Wish fulfilled :sparkles:
You were right about minShould being the problem with my query. And it means the example I reused in the test from http://www.blevesearch.com/docs/Query-String-Query/ is incorrect:
`+water -light beer` is really equivalent to `+water -light …
=> query: add DumpQuery to expand string query and format them as JSON

utils/bleve_dump/main.go
I was expecting:
$ bleve_dump -index /index -docID 123 -fields html
to print only the terms for "html" field in specified document. The
command now detects extra arguments and flag collisions.
=> bleve_dump: improve online help and error handling

analysis/token_filters/stop_tokens_filter/stop_tokens_filter.go, analysis/token_map/custom.go, analysis/type.go
I may try to put this information in the wiki, it would be easier to find.
=> token_map: document it along with stop_token_filter

query_numeric_range.go
Should say numeric instead of date.
=> Update NumericRangeQuery comments

index/firestorm/comp.go, index/firestorm/firestorm.go, index/firestorm/garbage.go, index/firestorm/lookup.go, index/firestorm/stored.go, index/firestorm/termfreq.go, index/firestorm/warmup.go, index/upside_down/analysis.go, index/upside_down/dump.go, index/upside_down/index_reader.go, index/upside_down/reader.go, index/upside_down/row.go, index/upside_down/row_test.go, index/upside_down/upside_down.go
Various perf and correctness fixes, related to firestorm.
=> perf 20160106

index/firestorm/firestorm.go, index/upside_down/upside_down.go
@mschoch - this feels better as an upside-down perf improvement.  But, it messes up the analysis vs indexing timing metrics, so probably needs some more thought.
=> upside-down backindex read concurrency

.gitignore, analysis/type.go, document/field_boolean.go, index/firestorm/analysis.go, index/firestorm/reader.go, index/upside_down/upside_down.go, index_impl.go, index_test.go, mapping_document.go, mapping_field.go, mapping_test.go, query_bool_field.go
First go at implementing bool field support - fixed #109
=> Implemented boolean field support

search/searchers/search_fuzzy.go, search/searchers/search_numeric_range.go, search/searchers/search_regexp.go
=> pass the boost value into the term searcher

analysis/language/ja/ja_morph_kagome.go, analysis/language/ja/ja_morph_kagome_test.go
=> Use a small version of kagome

index/store/goleveldb/store.go
=> Add compact method to goleveldb store

index/store/moss/lower.go, index/store/moss/lower_test.go, index/store/moss/store.go, vendor/manifest
This PR depends upon the mossStore changes in review.couchbase.com, with the last change in the series at... http://review.couchbase.org/#/c/64490/
=> enable mossStore as configurable lower-level store

analysis/token_filters/camelcase_filter/camelcase_filter.go, analysis/token_filters/camelcase_filter/camelcase_filter_test.go, analysis/token_filters/camelcase_filter/parser.go, analysis/token_filters/camelcase_filter/states.go
The code is geared towards readability (a simple push-down automata), and making it easy to change the token classes. People often have strong, differing, opinions on exactly how to slice a string :)
=> init. simple camel case parser.

index_test.go, search/collectors/topn.go
the collector has optimizations to avoid allocation and reslicing
during the common case of searching for top hits
however, in some cases users request an a very large number of
search hits to be returned (attempting to get them all)  this
caused unnecessary allocation of ram.
to address this we introduce a new constant PreAllocSizeSkipCap
it defaults the value of 1000.  if your search+skip is less than
this constant, you get the optimized behavior.  if your
search+skip is greater than this, we cap the preallcations to
this lower value.  additional space is acquired on an as needed
basis by growing the DocumentMatchPool and reslicing the
collector backing slice
applications can change the value of PreAllocSizeSkipCap to suit
their own needs
fixes #408
=> cap preallocation by the collector to reasonable value

search/collectors/heap.go
=> fix for #416

search/searchers/search_boolean.go, search/searchers/search_disjunction.go
These are mostly related to avoiding memory allocations in the search codepaths via backing arrays.
=> miscellaneous search perf tweaks

search/searchers/search_boolean.go
This change to the BooleanSearcher.Next() tries to perform fewer
internal id comparisons.
=> optimize boolean search Next() with fewer id comparisons

index/upside_down/reader.go
This change to upside_down term-field-reader no longer moves the
underlying kvstore iterator forward preemptively.  Instead, it will invoke
Next() on the underlying kvstore iterator only when the caller invokes the
term-field-reader's Next().
There's a special case to handle the situation on the first Next()
invocation after the term-field-reader is created.
=> issue 441 - upside_down termFieldReader doesn't call Next() early

index/upside_down/reader.go, index/upside_down/row.go
This is a cleanup commit that's followup to a code review discussion
on a previous Advance() perf-optimization PR...
https://github.com/blevesearch/bleve/pull/443
=> added upside_down TermFrequencyRow.KeyAppendTo() API

index/upside_down/reader.go, index/upside_down/reader_test.go
also added unit tests for newUpsideDownCouchDocIDReaderOnly
use cases
fixes #449
=> fix logic in Advance() of UpsideDownCouchDocIDReader

search/collectors/slice.go
panic in collectStoreSlice.Final
=> closes #453

index/field_cache.go
The newly introudced reverse map (indexFields) is an array instead of a map, since the lookup keys (field id's) are just relatively low uint16's.
=> field cache also tracks fieldIndex -> fieldName reverse mapping

query.go, search/query/fuzzy.go
see https://groups.google.com/d/msg/bleve/vkVxnLMlXow/5qM1jL0ZEgAJ
=> Settle on default fuzziness of 1 (for now)

search/searcher/search_disjunction.go
Disjunction searchers are used heavily by higher-level searchers, like
prefix searchers.  In that case, a disjunction searcher might have
many thousands of child searchers.
This commit adds an optimization to close each child term searcher as
soon as a child searcher is finished and remove it from the
disjunction searcher's children.
=> optimize disjunction searcher to trim child searchers array earlier

search/query/date_range.go, search/query/date_range_test.go
See also MB-21322 found by Mihir Kamdar.
=> fix BleveQueryTime json marshaling with double-quoting

index/index.go, index/store/kvstore.go, index/upsidedown/index_reader.go, registry/store.go, search/facets_builder.go
This commit is some minor optimizations around the facets builder that doesn't change the APIs.
=> Minor facets builder optimizations

search/facets_builder.go, search/facets_builder_test.go
=> numeric range facet merging compare range values not pointers

index_alias_impl.go, index_alias_impl_test.go
MultiSearch previously had its own timeout checking.  This commit
removes that timeout checking, so that now MultiSearch instead depends
upon the bleve.Index implementations to perform their own context
deadline/timeout checking.
Because deadline/timeout checking is now handled by the bleve.Index
implementations, this change allows applications to provide richer
error and status results during timeouts.
=> simplified MultiSearch requires that indexes honor context deadlines

search/query/bool_field.go, search/query/boolean.go, search/query/conjunction.go, search/query/date_range.go, search/query/disjunction.go, search/query/docid.go, search/query/fuzzy.go, search/query/match.go, search/query/match_all.go, search/query/match_none.go, search/query/match_phrase.go, search/query/numeric_range.go, search/query/phrase.go, search/query/prefix.go, search/query/query.go, search/query/query_string.go, search/query/regexp.go, search/query/term.go, search/query/wildcard.go
It's really helpful to retrieve back the field and boost for our own query parser
=> Added getters to boost and field query interfaces

config/config_cld2.go
renamed detect_lang to detectlang.
https://github.com/blevesearch/blevex/commit/01d10016d20884963b9adfdc25b4de41cd9fecf4
=> renamed detect_lang to detectlang

analysis/token/edgengram/edgengram.go, analysis/token/edgengram/edgengram_test.go
edge condition was incorreclty checked
fixes #523
=> fix edge ngram output when side=Back and input token len=max

search/searcher/search_phrase.go
at the core, the Next() method moves another searcher forward
and checks each hit to see if it also satisfies the phrase
constraints.  the current implementation has 4 nested for loops.
these nested loops make it harder read (indentation) and harder
to reason about (complexity).
this refactor does not remove any loops, it simply moves some
of the inner loops into separate methods so that one can
more easily reason about the parts separately.
=> refactor phrase search into seprate methods

search/search.go, search/searcher/search_phrase.go, search/searcher/search_phrase_test.go
a more correct solution that will enable us to extend in two
important ways:
1) support slop
2) support multi-phrase
=> refactor phrase search to be recursive

README.md
=> Apache2 license badge

analysis/analyzer/custom/custom.go
when specified in the custom type of analyzer
=> add validtion which checks the type of char/token filters

search/query/query_string.y, search/query/query_string.y.go, search/query/query_string_parser_test.go
=> fix query string parsing of numeric ranges with negative value

cmd/bleve/cmd/dumpDoc.go, cmd/bleve/cmd/dumpFields.go
I noticed these while looking through licensing of this project.
(everything else looked correct)
=> Added name to copyright notice

geo/parse.go, query.go, search/query/geo_boundingbox.go, search/query/geo_distance.go, search/searcher/search_geoboundingbox.go, search/searcher/search_geoboundingbox_test.go, search/searcher/search_geopointdistance.go
also one fix came from steve, i must have forgotten to push that
commit up before merging
=> geo review comments from sreekanth

search/searcher/search_disjunction.go, search/searcher/search_fuzzy.go, search/searcher/search_geoboundingbox.go, search/searcher/search_geopointdistance.go, search/searcher/search_multi_term.go, search/searcher/search_numeric_range.go, search/searcher/search_regexp.go, search/searcher/search_term_prefix.go, search/searcher/search_term_range.go
- geo searches now use this option and skip the check
- export ComputeGeoTerms for geo debug visualizations
=> add option for multi term searcher to skip max disjunction check

index.go, index_impl.go, index_test.go
IndexAdvanced bypasses the mapping matching and adds the doc directly
=> Add new IndexAdvanced function

geo/geo.go, geo/geo_test.go, geo/sloppy.go, search/searcher/search_geopointdistance.go
there was a bug where if the circle described by the point
distance query crossed the poles, then we incorrectly built
a box around it.  this resulted in incorrect searh results.
=> fix geo point distance search

search/sort.go
As we discussed exporting lon/lat fields in SortGeoDistance struct.
=> Exposing lon/lat fields in SortGeoDistance struct

search/search.go
=> Add comments to Location struct

search/searcher/search_numeric_range.go
previously, all numeric terms required to implement a numeric
range search were passed to the disjunction query (possibly
exceeding the disjunction clause limit)
now, after producing the list of terms, we filter them against
the terms which actually exist in the term dictionary.  the
theory is that this will often greatly reduce the number of terms
and therefore reduce the liklihood that you would run into the
disjunction term limit in practice.
because the term dictionary interface does not have a seek API
and we're reluctant to add that now, i chose to do a binary
search of the terms, which either finds the term, or not. then
subsequent binary searches can proceed from that position,
since both the list of terms and the term dictionary are sorted.
=> filter numeric range terms against the term dictionary

search.go
Hi Marty, as discussed adding a new setter method for dateTImeRange in FacetRequests
=> Adding a new bucket setter method for dateTimeRange

analysis/token/camelcase/camelcase.go, analysis/token/camelcase/camelcase_test.go, analysis/token/camelcase/parser.go
=> Fix token start/end/position values in camelCase tokenizer

index/scorch/mergeplan/merge_plan.go, index/scorch/mergeplan/merge_plan_test.go, index/scorch/mergeplan/sort.go
I added some "test" code, that's not really automated unit testing, but that prints out simple ascii bar charts of the segments as various scenarios are running and evolving -- somewhat like a low rent version of those lucene youtube videos, but without the animation.
=> mergeplan: scoring implemented

index/scorch/introducer.go, index/scorch/merge.go, index/scorch/persister.go, index/scorch/reader.go, index/scorch/reader_test.go, index/scorch/scorch.go, index/scorch/segment/empty.go, index/scorch/segment/mem/segment.go, index/scorch/segment/segment.go, index/scorch/segment/zap/segment.go, index/scorch/snapshot_index.go
Future commits will provide actual cleanup when ref-counts reach 0.
=> scorch ref-counting

index/scorch/introducer.go, index/scorch/scorch_test.go, index/scorch/snapshot_index.go, index/scorch/snapshot_segment.go
Creating a fresh PR incorporating the review comments from the older PR, 
Yes @mschoch , I have verified that subsequent calls to the same snapshot doesn't recompute the data again.
=> DocumentVisitFieldTerms Scorch implementation level1

index/scorch/mergeplan/merge_plan.go, index/scorch/mergeplan/merge_plan_test.go
Moving the package comment for mergeplan to the right place.
=> scorch mergeplan package comments tweak

index/scorch/mergeplan/merge_plan.go, index/scorch/mergeplan/merge_plan_test.go
Refactored out API so it's usable from other places.
=> scorch mergeplan.ToBarChart() refactored to callable API

index/scorch/introducer.go, index/scorch/scorch.go, index/scorch/snapshot_rollback.go, index/scorch/snapshot_rollback_test.go
- PreviousPersistedSnapshot
- SnapshotRevert
+ unit test
=> scorch APIs to support rollback

index/scorch/snapshot_index_tfr.go
I'm suspecting that Marty's editor is more exciting than mine. :-)
=> scorch remove leftover doc comment

index/scorch/merge.go, index/scorch/persister.go, index/scorch/scorch.go
Event types:
- EventKindCloseStart
- EventKindClose
- EventKindMergerProgress
- EventKindPersisterProgress
- EventKindBatchIntroductionStart
- EventKindBatchIntroduction
=> Adding onEvent callback support for scorch

analysis/lang/ru/analyzer_ru.go, analysis/lang/ru/analyzer_ru_test.go, analysis/lang/ru/snowball/stem_Unicode.go, analysis/lang/ru/stemmer_ru.go, analysis/lang/ru/stemmer_ru_test.go, analysis/lang/ru/stop_filter_ru.go, analysis/lang/ru/stop_words_ru.go, analysis/token/snowball/snowball.go, analysis/token/snowball/snowball_test.go
=> Added Russian analyzer with snowball stemmer

index/scorch/segment/mem/build.go, index/scorch/segment/mem/segment.go, index/scorch/segment/zap/build.go
Starting to look at scorch mem segment optimizations, and saw some minor things
=> scorch mem segment optimizations

analysis/token/unique/unique.go, analysis/token/unique/unique_test.go
Implements #737, plus unit tests.
=> Add UniqueTerm token filter

index/scorch/scorch.go, index/scorch/snapshot_rollback_test.go
The TestIndexRollback unit test was failing occasionally(?), but
seemingly more than ever, so this commit tries to remove avenues of
raciness in the test...
- The Scorch.Open() method is refactored into an Scorch.openBolt()
helper method in order to allow unit tests to control which
background goroutines are started.
- TestIndexRollback() doesn't start the merger goroutine, to simulate
a really slow merger that never gets around to merging old segments.
- TestIndexRollback() creates a long-lived reader after the first
batch, so that the first index snapshot isn't removed due to the
long-lived reader's ref-count.
- TestIndexRollback() temporarily bumps NumSnapshotsToKeep to a large
number so the persister isn't tempted to removeOldData() that we're
trying to rollback to.
=> scorch zap TestIndexRollback fixes

index/scorch/persister.go
See also: https://github.com/blevesearch/bleve/issues/763
=> scorch persistSnapshot comments update

index/scorch/merge.go
mergePlanner options are parsed from the
scorch configs parameters
=> configurable mergePlanner options

index/scorch/persister.go
adding a pause to persister until the merger catches up.
=> pausing persister until merging catches up

index/scorch/introducer.go, index/scorch/merge.go, index/scorch/persister.go, index/scorch/segment/zap/intcoder.go, index/scorch/segment/zap/merge.go
Also, there's a 'go fmt' that was needed.
=> Various scorch optimizations around merge & chunkedIntCoder

index.go, index_alias_impl.go, index_alias_impl_test.go, index_impl.go, index_test.go, search/collector.go, search/collector/bench_test.go, search/collector/topn.go, search/collector/topn_test.go, vendor/manifest
update all references to context to use std lib pkg
=> BREAKING API CHANGE - use stdlib context pkg

index/scorch/introducer.go, index/scorch/merge.go, index/scorch/persister.go, index/scorch/scorch.go, index/scorch/snapshot_index.go, index/scorch/snapshot_index_tfr.go, index/scorch/stats.go
This has changes / improvements on top of @sreekanth-cb's PR #787, changing gauges into counters, and adding more counters.
=> adding stats for scorch, with no gauges

index/scorch/segment/zap/posting.go
Removed attribute: iterator of type Posting
=> Address build breakage after rebase

index/scorch/segment/zap/build.go
This change leverages the ability for chunkedIntCoder.Add()
to accept multiple input param values (via the '...' param signature),
meaning there can be fewer Add() invocations.
=> scorch zap optimize chunkedIntCoder.Add() calls to use multiple vals

index/scorch/merge.go, index/scorch/segment/mem/build.go, index/scorch/segment/zap/build.go, index/scorch/segment/zap/intcoder.go
More scrubbing of inner loops, an error return value bug fix, and a go fmt.
=> err fix and more scorch optimizing

index/scorch/segment/mem/build.go
This change produces less garbage by switching from a map[uint16]'s to
array's for the memory-segment fieldLens and docMap, and by reusing
those arrays across multiple mem/build/processDocument() calls.
=> scorch mem processDocument reuses fieldLens/docMap arrays

index/scorch/persister.go, index/scorch/scorch.go
NumSnapshotsToKeep read from index configs
=> making NumSnapshotsToKeep configurable

index/scorch/segment/zap/new.go
Since interim structs are now sync.Pool'ed, we can now also hold onto
and reuse the associated vellum builder.
=> scorch zap optimize interim's reuse of vellum builders

index/scorch/mergeplan/merge_plan.go, index/scorch/segment/zap/posting.go
posting iterator array positions clean up,
and max segment size limit adjustment for hit-1 optimisation
=> posting iterator array positions clean up,

index/scorch/segment/empty.go, index/scorch/segment/mem/posting.go, index/scorch/segment/mem/segment_test.go, index/scorch/segment/segment.go, index/scorch/segment/zap/contentcoder.go, index/scorch/segment/zap/docvalues.go, index/scorch/segment/zap/merge.go, index/scorch/segment/zap/merge_test.go, index/scorch/segment/zap/new.go, index/scorch/segment/zap/posting.go, index/scorch/segment/zap/segment.go, index/scorch/segment/zap/segment_test.go, index/scorch/snapshot_index.go, index/scorch/snapshot_segment.go
Now that I've been recently slapped by sync.Pool, it's time again for even more sync.Pool :-)
=> More buffer & slice reuse optimizations

index/index.go, index/scorch/segment/empty.go, index/scorch/segment/mem/dict.go, index/scorch/segment/mem/dict_test.go, index/scorch/segment/segment.go, index/scorch/segment/zap/dict.go, index/scorch/snapshot_index.go, index/scorch/snapshot_segment.go, search/searcher/search_fuzzy.go, search/searcher/search_regexp.go
draft changes for any discussions.
Surprisingly, for the fuzzy queries vellum based implementation takes more time.
Need to analyse that..
=> vellum adoption for regex and fuzzy queries

index/scorch/snapshot_index_tfr.go, search/searcher/search_phrase.go, search/searcher/search_phrase_test.go
From trying to understand the phrase search codepaths and looking at the phrase search pprof flame graphs, here are some micro-optimizations (no changes to API's), mostly around memory allocations.
=> micro optimizations around phrase search

index/scorch/persister.go, index/scorch/segment/zap/build.go, index/scorch/segment/zap/segment.go, index/scorch/segment/zap/write.go
=> persisting the zap version to bolt

index/scorch/reader_test.go, index/scorch/segment/empty.go, index/scorch/segment/segment.go, index/scorch/segment/zap/posting.go, index/scorch/snapshot_index_tfr.go
advance will jump directly to the expected segment
then it will skip directly to the expectec chunk
=> improve scorch Advance implementation

document/document.go, document/field.go, document/field_boolean.go, document/field_composite.go, document/field_datetime.go, document/field_geopoint.go, document/field_numeric.go, document/field_text.go, index.go
+ Supporting APIs to fetch these stats: last added
document's size and total documents' size.
=> MB-28847: Account for total documents' size within a batch

search/searcher/search_disjunction.go
See also https://issues.couchbase.com/browse/MB-29421
=> disable disjunction heap optimization due to reported problems

numeric/prefix_coded.go, search/sort.go
for code reviewers... if the individual commits might be more palatable / less-risky on an individual basis, no problem if we want only a subset of these in the near term
=> various sort related optimizations

index/scorch/scorch.go
T1:
runtime.sigpanic()
/home/couchbase/.cbdepscache/exploded/x86_64/go-1.9.6/go/src/runtime/signal_unix.go:367 +0x17c fp=0xc4315bc928 sp=0xc4315bc8d8 pc=0x44432c
github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).AddRef(0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index/scorch/snapshot_index.go:77 +0x22 fp=0xc4315bc948 sp=0xc4315bc928 pc=0x6012c2
github.com/blevesearch/bleve/index/scorch.(*Scorch).currentSnapshot(0xc420364380, 0xc4314ca180)
/home/couchbase/jenkins/workspace/couchbase-server-unix/godeps/src/github.com/blevesearch/bleve/index/scorch/scorch.go:427 +0x53 fp=0xc4315bc970 sp=0xc4315bc948 pc=0x5ffc03
github.com/blevesearch/bleve/index/scorch.(*Scorch).MemoryUsed(0xc420364380, 0x0) …
=> MB-29554: Handle case when MemoryUsed is invoked after index is closed

cmd/bleve/cmd/scorch/info.go, cmd/bleve/cmd/scorch/snapshot.go, cmd/bleve/cmd/zap/dict.go, cmd/bleve/cmd/zap/explore.go, cmd/bleve/cmd/zap/stored.go
+ Handle the _id field special case
+ Format the output for better readability
=> Fix bug in bleve's zap stored command, formatting

analysis/token/snowball/snowball.go, analysis/token/unique/unique.go, cmd/bleve/cmd/zap/dict.go, cmd/bleve/cmd/zap/explore.go, geo/parse_test.go, index/scorch/README.md, index/scorch/segment/zap/README.md, index/scorch/segment/zap/posting.go, index/scorch/segment/zap/segment.go, index_alias_impl_test.go, index_test.go, mapping/document.go, mapping/mapping_test.go, numeric/bin.go, search/searcher/search_phrase.go, search/searcher/search_term_range_test.go
Non-deleted version of https://github.com/blevesearch/bleve/pull/943
=> Fix spelling and typo mistakes

search/searcher/search_fuzzy.go
This should not affect functionality, as the fuzzy searcher uses a
disjunction searcher underneath the hood, and the disjunction searcher
later on checks for the tooManyClauses() case.
But, the idea is that the tooManyClauses() check should be handled the
same whether or not the IndexReaderFuzzy interface is implemented by
the index-reader, and if we can bail earlier, then we waste less
resources.
Also, this commit also checks for error more consistently.
=> optimize scorch FieldDictFuzzy to check for tooManyClauses earlier

index/scorch/introducer.go, index/scorch/merge.go, index/scorch/persister.go, index/scorch/scorch.go
Some scrubbing of the Add/DecRef() codepaths,
motivated by growing # of files issue seen here at...
https://issues.couchbase.com/browse/MB-30456
=> scorch root Add/DecRef() codepath scrubbing

geo/parse.go, geo/parse_test.go, mapping/document.go, mapping/reflect.go
Adding checks to validate the geo point values
while parsing
=> MB-30694: reflect.Value.Type on zero Value panics

index/scorch/segment/zap/dict.go
This optimization avoids creating a regexp for the scorch/zap
dictionary prefix iterator, and instead just does a straight
startKey/endKey iteration.
See also: https://issues.couchbase.com/browse/MB-30263
The incrementBytes() helper func is a direct code copy-&-paste from bleve/index/store/moss/reader.go
=> optimize scorch/zap dict PrefixIterator()

index/scorch/introducer.go, index/scorch/scorch.go, index/scorch/stats.go
Fixing the num_recs_to_persist stat
=> MB-30943 - incorrect `num_recs_to_persist` stat

index/scorch/introducer.go, index/scorch/scorch.go, index/scorch/stats.go
adding file,mem segment stats for currrent root
=> more stats for root segment

search/searcher/search_multi_term.go, search/searcher/search_term_prefix.go
Context:
+ MultiTermSearcher
+ TermPrefixSearcher
=> Check for TooManyClauses as early as possible where applicable

vendor/manifest
Point to:
35d9e73 Prateek Rungta | Re-work pooling to have a fixed memory cost
=> Update vendor/manifest revision of vellum

index/scorch/merge.go, index/scorch/persister.go, index/scorch/segment/segment.go, index/scorch/segment/zap/merge.go, index/scorch/segment/zap/merge_test.go, index/scorch/segment/zap/segment_test.go, index/scorch/stats.go
Faster zap file cleanup on index deletion
=> MB-31660 - suspected file leaks in scorch

search/searcher/search_boolean.go, search_test.go
The currMustNot cursor of the boolean searcher isn't tracked
by the currentID. This means that during Advance(), we'll
need to additionally check to prevent updating the cached
cursor ID for the must not searcher.
Fixes https://github.com/blevesearch/bleve/issues/1029
=> Prevent boolean must not cursor from incorrectly advancing

index/scorch/segment/zap/README.md, index/scorch/segment/zap/zap.md
There are some visualizations of ZAP file format internal structure.
=> Improved ZAP File Format Documentation

index/scorch/merge.go, index/scorch/persister.go, index/scorch/segment/segment.go, index/scorch/segment/zap/merge.go, index/scorch/segment/zap/merge_test.go, index/scorch/segment/zap/segment_test.go, index/scorch/stats.go
=> Backporting fixes to 6.0.1 branch

search_test.go
Adding index close for better cleanup
=> Fix for Travis CI failures

index/scorch/snapshot_index.go
Adopting new levenshtein automaton
=> New levenshtein automaton adoption

.travis.yml
https://golang.org/doc/devel/release.html#policy
=> Update .travis.yml to use supported versions of golang

cmd/bleve/cmd/zap/docvalue.go
Fixing the docvalue cmd to adopt the newer disk format
And minor improvements
=> MB-32287 - `zap docvalue` cmd is broken

search/searcher/search_conjunction.go, search_test.go
Fixes https://github.com/blevesearch/bleve/issues/1074
=> Protect conjunction searcher with no searchers

index.go, index/index.go, index/scorch/introducer.go, index/scorch/persister.go, index/scorch/scorch.go, index/scorch/scorch_test.go, index/upsidedown/upsidedown.go
This is updated version of #1053
=> Add persisted callback to batch

index.go, index/index.go, index/scorch/introducer.go, index/scorch/persister.go, index/scorch/scorch.go, index/scorch/scorch_test.go, index/upsidedown/upsidedown.go
So we can know when a batch was persisted properly to disk
=> Add callbacks to Batch

index/scorch/segment/zap/segment.go
Reverting changes introduced with https://github.com/blevesearch/bleve/pull/1062
Issue identified with them: https://github.com/blevesearch/bleve/issues/1096
=> Revert #1062

index/scorch/segment/zap/posting.go
Consider a scenario of a conjunction search with a high-frequency term
search and a low-frequency term search.
The scorch PostingsIterator for the high-frequency term will have its
nextDocNumAtOrAfter(atOrAfter) method invoked with a non-zero
atOrAfter parameter -- driven by docNum's from the low frequency term
search.
In this case, before this change, the inner loop that moves the
high-frequency "all iterator" forwards performs a division by
chunkFactor on every single "all" docNum, in order to compute the all
iterator's current chunk number, so that it can be checked against the
"actual iterator"'s current chunk number (in order to maintain the
PostingIterator's freqNorm & loc reader positions).
This integer division was appearing in pprof, so this change is to
replace the division op …
=> optimize scorch postingsIter chunk maintenance on skip ahead

.travis.yml
now that race detector passes for whole test suite, lets keep it that way
=> enable race detector on travis

search/collector/topn_test.go
UTs for
-Collector Chaining
-DocumentMatchHandler
-MakeDocumentMatchHandler
=> Unit tests for DocumentMatchHandler

search/search.go
- removing the un-used Document field
=> cleaning up DocumentMatch

index/scorch/persister.go, index/scorch/scorch.go, index/scorch/scorch_test.go, index/scorch/snapshot_rollback.go, index/store/boltdb/iterator.go, index/store/boltdb/reader.go, index/store/boltdb/store.go, index/store/boltdb/store_test.go, index/upsidedown/upsidedown_test.go, vendor/manifest
Replace #1018 since I couldn't figure out how to add commits to it...
=> Techknowlogick switch to bbolt

cmd/bleve/cmd/zap/dict.go
-exposing 1hit count and total term info
-exposing postings size and cardinality (should this be a separate cmd)
=> dict cmd additions

index_impl.go, search/search.go
Refactoring the code a bit to let
applications perform the field loading
and highlighting. Mainly helpful
with the streamed result hits.
=> LoadAndHighlightFields API

search_test.go
Reference: https://github.com/blevesearch/bleve/issues/1185
=> Adding a boolean search testcase

index/scorch/segment/zap/posting.go, search/scorer/scorer_term.go, search/searcher/search_term.go, search_test.go
Fixes: https://github.com/blevesearch/bleve/issues/1194
=> Include freq/norm information when IncludeTermVectors:true

.travis.yml
+ 1.12.x, 1.11.x, 1.10.x
+ https://golang.org/doc/devel/release.html#policy
=> Update .travis.yml to test on the latest 3 versions of golang

search/searcher/search_geoboundingbox.go
reuse the already computed prefixCoded term
=> fix to avoid double prefix coding

analysis/token/reverse/reverse.go, analysis/token/reverse/reverse_test.go, config/config.go
This token filter will simply reverse each token.
=> MB-33617: Supporting the "reverse" token filter

analysis/token/reverse/reverse.go, analysis/token/reverse/reverse_test.go
=> MB-33617: Support unicode strings with combining characters

index/scorch/segment/zap/enumerator_test.go
-implementing the new Exists method from
vellum Iterator interface
=> EnumeratorTests adopting Exists method

index/index.go, index/scorch/segment/empty.go, index/scorch/segment/segment.go, index/scorch/segment/zap/dict.go, index/scorch/snapshot_index.go, index/scorch/snapshot_index_dict.go, search/searcher/search_geoboundingbox.go
New Exists iterator api implementation for the FieldDictionary
geo queries adoption for the Exists api to filter the candidate terms.
This method performs better than the existing RangeIterator and OnlyIterator methods on memory and cpu usage for random dictionary lookups.
=> Geo adopts the new field dictionary Exists (random look up) API

.travis.yml
See.. https://github.com/blevesearch/bleve/issues/1183
=> Disable errcheck on only go1.10

index/scorch/persister.go
The persistedCallbacks of a snapshot that failed persistance need
to be preserved until one of the two events have occurred:
- a new snapshot was introduced
- the retry-attempt of the exact same snapshot succeeded
=> Preserve persistedCallbacks of an unpersisted snapshot until needed

index/scorch/persister.go
If the persister is busy doing the catch up with
the ongoing mutations then there is a chance for
the older snapshot clean up call/removeOldData to
wait for a longer time to get invoked. This can
result in unbounded growth in the number of scorch
files.
This change attempt to invoke removeOldData whenever
the number of files grow beyond the thresholds.
=> Fix for potential removeOldData call starve issue

index/scorch/segment/zap/dict_test.go, index/scorch/snapshot_index.go, vendor/manifest
adopting the levenshtein package
changes in vellum
=> bumping the vellum SHA

.travis.yml
=> Update .travis to test on the last 3 releases of golang

geo/geo.go, search/searcher/search_geopolygon_test.go
Adding json tags for the geo point struct
-adding UTs for simple self-intersecting polygons
=> adding UTs for simple self-intersecting polygons

search/searcher/search_geopolygon.go
Adding input validation checks for polygon points
=> MB-37471 - Incomplete polygon points results empty response

geo/geo.go, geo/parse.go
Adding geohash length validation checks
=> MB-37500 - Polygon query with invalid geohash gives results

vendor/manifest
=> update manifest to fix issue with vellum

index/scorch/merge.go
Upon an index closure event, the file merger skips the
reference count decrement operations at line no: https://github.com/blevesearch/
bleve/blob/05d86ea8f6e30456949f612cf68cf4a27ce8c9c5/index/scorch/merge.go#L261
leading to the leaking of index snapshots. This will further
lead to the segment file leaking as those segment files will
never get ceremoniously un-mapped or handle closed in the event
of an index closure.
details ref - https://issues.couchbase.com/browse/MB-38303
=> MB-38303 - merger leaks index snapshot refCounts on index closure

search/highlight/fragmenter/simple/simple.go, search_test.go
Addresses https://github.com/blevesearch/bleve/issues/1370
=> Fix slice out-of-bounds panic within highlighter

go.mod, index/scorch/segment_plugin.go
=> add support for zap v14

go.mod
Diff since v1.0.1:
* 8f70ead Marty Schoch | fix bug in iterator next optimization
* 915a44a Marty Schoch | update README with badge showing github CI
* 2dd513f Marty Schoch | add github workflow to run tests
=> Update vellum version to v1.0.2

search/searcher/search_geoboundingbox.go
attempt to go back to a simpler compute geo range
but not give up the perf improvements
=> simplify compute geo range

index/scorch/optimize.go, index/scorch/unadorned.go
the unadorned postings lists are only used by scorch
so they are relocated to this package
=> move unadorned into scorch

mapping/mapping_test.go
this works when using array of strings
=> add test to demonstrate multi-geopoint field

go.mod, go.sum
v1.0.4 fixes import for bitset
=> bump vellum to 1.0.4

index/scorch/scorch.go, index/scorch/scorch_test.go
+ By default, etcd-io/bbolt appends an O_CREATE flag to the flags passed in
no matter which mode the user attempts to open the db ..
https://github.com/etcd-io/bbolt/blob/v1.3.5/db.go#L197...L213
+ This appears to be bolt's design decision where they let you create a
file that is only writeable by the process if it doesn't exist - even
when it is OPEN-ed in READ-ONLY mode.
+ However, using an O_CREATE on a file that's owned by a different user
but READ-able by all users, seems to be causing a permissions error.
- While I cannot seem to reproduce this issue on osX, this seems to
manifest on windows which complains ERROR_ACCESS_DENIED.
+ The proposal here is to overwrite Bolt.Options' OpenFile with a custom
implementation that appends the O_CREATE file only if the file does
not exist - …
=> In RDONLY mode, use O_CREATE for bolt.Open(..) only when file doesn't exist

index/scorch/introducer.go
There is a potential file handles leak in an update heavy use case like below,
The new segment files that are created during a merge cycle
are protected from accidental clean up by the concurrent persister
routine over a removal eligibility status set over here -
https://github.com/blevesearch/bleve/blob/master/index/scorch/merge.go#L324
And these merger introduced files are getting removal eligibility
status reset by the persister here -
https://github.com/blevesearch/bleve/blob/master/index/scorch/persister.go#L665
Note that not every epoch/root instance undergoes the processing of the persister
and hence such snapshots that escaped the persister reset process (that
would have flipped the segment files to eligible for removal) would contain segment
files ineligible for removal.
Now, if …
=> Fix for potential file handle leaks in merger.

search/facets_builder.go
For https://github.com/blevesearch/bleve/issues/1653
=> Place a nil guard within TermFacets' Terms() API

index/scorch/snapshot_index.go
Signed-off-by: Aditi Ahuja <aditi.ahuja@couchbase.com>
Fixes #1243 
This PR adds a parameter for the maximum field TFR length of an index. This is used to check for the length of the field TFRs of the index when recycling.
This can be overwritten by the user at the library level by modifying the exported variable or the index level by modifying kvconfig.
=> Adding configurable default threshold for field TFR cache

search/searcher/search_geoshape_polygon_test.go, test/tests/geoshapes/searches.json
-with a larger query shape covering
the whole documents.
=> Updating integration tests

geo/geo_s2plugin_impl.go
It helps is optimizing the index and query time performance for the original geopoint type.
=> Updating the geopoint options for s2's region term indexer

go.mod, go.sum
To include:
* a8f4556 Aditi Ahuja | Updated intersection logic (#10)
=> Update version of blevesearch/geo

index/upsidedown/store/goleveldb/batch.go, index/upsidedown/store/goleveldb/reader.go, index/upsidedown/store/goleveldb/store.go, index/upsidedown/store/goleveldb/writer.go, index/upsidedown/store/gtreap/store.go, index/upsidedown/store/metrics/store.go, search_test.go
+ This unit test highlights the index mapping rules to follow to support GeoShape queries.
=> Adding unit test for a Geo shape query

go.mod, go.sum
To include:
* e34dce0 zeripath | Fix alignment in chunkedContentCoder (#147)
=> Upgrade to blevesearch/zapx@v15.3.8

go.mod, go.sum
* 071c505 Abhi Dangeti | Check if field exists within segment's visitStoredFields callback (#105)
* 08eb848 Abhi Dangeti | Update PostingsList's chunkSize only when err == nil (#151)
=> Upgrade blevesearch/zapx/v15 SHA

go.mod, go.sum
Includes:
* b63d83d Thejas-bhat | Error handling for empty vellum data
=> Update to zap@v15.3.10

go.mod, go.sum
Addresses: https://github.com/blevesearch/bleve/issues/1844
=> Upgrade to golang.org/x/text@v0.8.0

mapping/document.go
Showed 6% improvement in the 180 attribute testcase. I expect the improvement to be greater as the lookup varies.
=> MB-57394: Replace iterative lookup for properties within documentMappingForPath

search.go
Hello👋
There are about three things that I modified.
Modify the position of the function
Modify variable position
Change code to readability
=> Refactor: func in search.go

search/searcher/search_knn.go
=> fix dropped error

go.mod, go.sum
* c565710 Abhi Dangeti | Use latest of blevesearch/go-faiss (#178)
* d7e8f3a Thejas-bhat | bug fix: reconstruct failing due to key not found (#177)
=> Upgrade zapx@v16

search.go, search_knn.go, search_no_knn.go
- Added a new validation function for KNN queries
=> MB-59673: Added validation to KNN queries

go.mod, go.sum
* 322e3d7 Thejas-bhat | choosing the index types more responsibly (#186)
=> Move up zap@v16

search_knn.go
- Support usage of the knn operator "and" while merging knn results across multiple indexes of an alias.
- Drop hits at the merge phase when any score in a hit's score breakdown is made zero to accomodate for the top K knn results
=> integrate knn operator

search/scorer/scorer_constant.go, search_test.go
Currently, match all queries used to return 1.0 as the score even when score = "none".
This PR fixes that by ensuring they return 0.0 in such a case and adding a UT for verification.
=> Fix scoring for match all query

go.mod, go.sum
Includes:
* 78d1df8 Abhi Dangeti | Beautify & Fix cmd line tooling output for vector content (#194)
* 6a57ac5 Abhi Dangeti | Graceful exit when min arguments not provided for vector (#193)
=> Use zapx/v16@v16.0.0

go.mod, go.sum
* 86b1161 Mohd Shaad Khan | MB-59447: support nested/chunked vectors (#185)
* 0f89c37 Aditi Ahuja | MB-60084: Change index merge procedure to account for existing index type. (#197)
=> Upgrade zapx/v16

search/facets_builder.go, search/facets_builder_test.go
Cherry Pick e26eacec92d4fda5d953a8581b4b71b55b0578d6
[MB-60207 fix facets merge (](https://github.com/blevesearch/bleve/commit/e26eacec92d4fda5d953a8581b4b71b55b0578d6)https://github.com/blevesearch/bleve/pull/1946[)](https://github.com/blevesearch/bleve/commit/e26eacec92d4fda5d953a8581b4b71b55b0578d6)
=> MB-60207 fix facets merge (#1946)

go.mod, go.sum
To include:
* 8c668c4 Aditi Ahuja | MB-60269 - Merge path fixes (https://github.com/blevesearch/zapx/pull/202)
=> Upgrade zapx/v16@master

search/searcher/optimize_knn.go, search_knn_test.go
- Return error instead of ignoring it
- Fixed some test case code
=> MB-60352: Fix dropped error

go.mod, go.sum
* 7af9f80 Rahul Rampure | MB-60662: Revert merge buffer pool (https://github.com/blevesearch/zapx/pull/214)
* e1cc843 Aditi Ahuja | Early exit condition for vector index merging (https://github.com/blevesearch/zapx/pull/213)
=> Upgrade to zap/v16@v16.0.4

go.mod, go.sum
* 9aa0040 Rahul Rampure | MB-60739: Fix slicing issue
=> MB-60739: Upgrade go-faiss & zapx/v16

mapping/document.go
- isPropertyVector is always false due to bad initialization
- verified this fix with mprofs
- sorry for not catching this earlier
=> Fix initialisation of isPropertyVector variable

docs/vectors.md
Addresses: https://github.com/blevesearch/bleve/issues/2028
=> Fix doc's json field interpretation in example

go.mod, go.sum
* cdfd338 Aditi Ahuja | MB-60943 - Change quantiser when vector index is tuned for memory
=> MB-60943: Upgrade to zapx/v16@v16.1.0

go.mod, go.sum
Brings in:
* 8d27d20 Rahul Rampure | MB-62167: Fix windows crash (#246)
=> MB-62167: faiss IO flags support for windows

go.mod, go.sum
Requires blevesearch/faiss@d9db66a
=> MB-62221: Upgrade go-faiss, zapx

go.mod, go.sum
* 097ce48 Thejas-bhat | MB-62427: seeking the pointer correctly while reading segmentBase data
=> MB-62427: Upgrade zapx for fix

search_knn.go
Regression introduced with https://github.com/blevesearch/bleve/pull/2084
=> MB-63736: Yet another shortcoming from an earlier commit

go.mod, go.sum
v15:
* 6f61b26 Thejas-bhat | MB-57871 - [v15] Avoid unnecessary atomic operation on bytesWritten
v16:
* ef2b41d Thejas-bhat | MB-57871 - Avoid unnecessary atomic operation on bytesWritten
=> MB-57871: Upgrade zapx v15 and v16

search_test.go
- Fix expected hits due to fuzzy dynamic scoring
=> Fix Broken Test

go.mod, go.sum
=> MB-64360 - Upgrade zapx v16

go.mod, go.sum
For https://github.com/blevesearch/zapx/issues/285 - possible situation on ARM
=> Update zapx/v15,v16 to use a new version of golang/snappy
