- mapping_document.go
Pointers may be references to any type, existing logic will only handle types
understood by `walkDocument`, instead pass the deref'd element to
`processProperty`, where it can get passed back to `walkDocument` if 
necessary, or be processed as a regular field.
I've done some cursory testing and this has fixed issues I was having, but my
testing has not been extensive and it's possible I've missed something.
> Process pointer fields, rather than trying to walk them

- search/facets/facet_builder_numeric.go
- search/facets/facet_builder_numeric_test.go
I am not 100% sure that the benchmark is measuring the right thing so some checking would be advised. In its current form it adds 10/100/1000 ranges to the range facet builder and then updates it with a very limited set of 4 prefix coded values over and over again. Afterwards it measures how long the Result() function takes to return its result.
If the benchmark is indeed mimicking real world uses, using the slice-based Result()-implementation is a net win just like with the term facet builder. Here are the numbers (on my i7 under Linux).
Old (using a list):
```
PASS
BenchmarkNumericFacet10   100000             14304 ns/op
BenchmarkNumericFacet100           10000            147730 ns/op
BenchmarkNumericFacet1000            300           4351645 ns/op
...
```
New (using sort.Sort):
``` …
```
> Add a benchmark for the numeric facet builder and use sort.Sort in it (just like for the terms one) 

- index_impl.go
- index_meta.go
- Fix the following errors found by [errcheck](https://github.com/kisielk/errcheck) :
```
$ bleve git:(master) errcheck github.com/blevesearch/bleve
github.com/blevesearch/bleve/index_impl.go:206:25  defer indexReader.Close()
github.com/blevesearch/bleve/index_impl.go:317:25  defer indexReader.Close()
github.com/blevesearch/bleve/index_impl.go:353:25  defer indexReader.Close()
github.com/blevesearch/bleve/index_impl.go:359:22  defer searcher.Close()
github.com/blevesearch/bleve/index_impl.go:497:25  defer indexReader.Close()
github.com/blevesearch/bleve/index_impl.go:644:20  defer reader.Close()
github.com/blevesearch/bleve/index_meta.go:67:27   defer indexMetaFile.Close()
```
- I've added named return parameters to capture the errors from the deferred calls. Thoughts?
> Check all return errors

- config_goleveldb.go
- index/store/goleveldb/batch.go
- index/store/goleveldb/iterator.go
- index/store/goleveldb/reader.go
- index/store/goleveldb/store.go
- index/store/goleveldb/store_test.go
- index/store/goleveldb/util.go
- index/store/goleveldb/writer.go
- index/upside_down/benchmark_goleveldb_test.go
This pull request introduces [goleveldb][1] as an experimental KV store alternative.  It is based from a  discussion on a [bleve google groups thread][2].  
I think I've performed the instructions mentioned on the [contributing section of the wiki][3].  Let me know if there are any issues I should address.
[1]: https://github.com/syndtr/goleveldb
[2]: https://groups.google.com/forum/#!topic/bleve/aHZ8gmihLiY
[3]: https://github.com/blevesearch/bleve/wiki/Contributing
> add goleveldb as an experimental alternative KV Store

- index/store/goleveldb/reader.go
I just noticed a mistake on my [previous pull request][1].
The `func (r *Reader) BytesSafeAfterClose()` should have been set to return `false`.
[1]: https://github.com/blevesearch/bleve/pull/190
> fix goleveldb's BytesSafeAfterClose() on reader

- analysis/analyzers/custom_analyzer/custom_analyzer.go
before it was in the standard_analyzer package
> Move custom_analyzer to custom_analyzer package

- index.go
This is not the final word on this but it would have helped me a lot
starting with bleve. I left out details about value processing and
custom parsers. I also ignored that named FieldMapping can directly
resolve value fields without having a parent SubDocumentMapping because
it did not appear in any example I read.
Let's consider this as a starting point for documentation improvements.
> doc: document indexed value/mappings interactions

- mapping_field.go
- search.go
- search/search.go
FWIW, the DateTime case is weird. I would have understood if it were stored as such in the index but that is not the case. Historical I suppose.
> doc: document field values storage and retrieval

- index/upside_down/upside_down.go
It boils down to:
1. client sends some work and a notification channel to a single worker,
then waits.
2. worker processes the work
3. worker sends the result to the client using the notification channel
I do not see any problem with this, even with unbuffered channels.
> upside_down: no need for a goroutine to enqueue AnalysisWork

- index/upside_down/upside_down.go
A tiny but steady improvement with no drawbacks.
benchmark                                         old ns/op      new ns/op      delta
BenchmarkAnalyze-2                                192633         184437         -4.25%
BenchmarkBoltDBIndexing1Workers-2                 9091553        8996297        -1.05%
BenchmarkBoltDBIndexing2Workers-2                 9076242        8990708        -0.94%
BenchmarkBoltDBIndexing4Workers-2                 9093248        9045758        -0.52%
BenchmarkBoltDBIndexing1Workers10Batch-2          1372212200     1381494457     +0.68%
BenchmarkBoltDBIndexing2Workers10Batch-2          1412452640     1424967303     +0.89%
BenchmarkBoltDBIndexing4Workers10Batch-2          1381424061     1409152830     +2.01%
BenchmarkBoltDBIndexing1Workers100Batch-2 …
> reducing allocation count

- index.go
- index/index.go
Two questions in passing:
- Is the "store dependent" behaviour of Advance() a problem? I would have expected Advance(k) where k < start to reset at start, giving a SeekFirst() on enumerated sequence.
- I noticed UpsideDownCouchDocIDReader converts .end to the binary row representation in Next() and Advance(). I have measured absolutely nothing and this is probably minor compared to I/Os but would it make sense to cache that instead?
> doc: document DocIDReader, and some Index bits

- index/store/boltdb/reader.go
- index/store/boltdb/store.go
- index/store/boltdb/writer.go
benchmark                                     old ns/op      new ns/op      delta
BenchmarkBoltDBIndexing1Workers-2             9182857        9101477        -0.89%
BenchmarkBoltDBIndexing2Workers-2             9235663        9063540        -1.86%
BenchmarkBoltDBIndexing4Workers-2             9242451        8999922        -2.62%
BenchmarkBoltDBIndexing1Workers10Batch-2      1570988524     1537403316     -2.14%
BenchmarkBoltDBIndexing2Workers10Batch-2      1600295858     1559906635     -2.52%
BenchmarkBoltDBIndexing4Workers10Batch-2      1596448655     1532570284     -4.00%
BenchmarkBoltDBIndexing1Workers100Batch-2     377685284      372590898      -1.35%
BenchmarkBoltDBIndexing2Workers100Batch-2     382156053      369342317      -3.35%
BenchmarkBoltDBIndexing4Workers100Batch-2 …
> BoltDB wrapper nano optimization which makes code a bit prettier too

- index/upside_down/row.go
Rows content is an implementation detail of bleve index and may change
in the future. That said, they also contains information valuable to
assess the quality of the index or understand its performances. So, as
long as we agree that type asserting rows should only be done if you
know what you are doing and are ready to deal with future changes, I see
no reason to hide the row fields from external packages.
Fix #268 
I made the smallest version solving my problem (which means `1 file changed, 1 insertion(+), 30 deletions(-)` in my client code, see https://github.com/pmezard/apec/blob/master/histogram.go#L32 ). I have no strong feelings about it, you can tell me to:
- Extend it to all other fields
- Let is as it is, and let people extend it when required.
- Forget it
> row: expose TermFrequencyRow term and freq fields

- mapping_field.go
- query_match_phrase.go
- query_phrase.go
And mention it is required for phrase and match phrase queries to
succeed.
Fix #280
> mapping_field: document IncludeTermVectors

- mapping_index.go
It returns the name of the analyzer used on a field, which can be passed
to IndexMapping.AnalyzeText().
Fix #282
> mapping_index: add IndexMapping.FieldAnalyzer()

- index_test.go
- mapping_field.go
In the following case, datetime fields are not getting indexed:
- When using an explicit `DateTimeFieldMapping` instead of relying on dynamic mapping
- When indexing from JSON instead of a struct
Test included that demonstrates the problem, and passes with the fix.
> Fixes datetime mapping from JSON, using DateTimeFieldMapping

- index/firestorm/garbage.go
- index/firestorm/garbage_test.go
This fixes https://github.com/blevesearch/bleve/issues/296 and adds a reproducer so that the problem doesn't show up again later.
> Firestorm: dont gc if no documents

- analysis/freq.go
- analysis/tokenizers/unicode/unicode.go
- index/firestorm/analysis.go
- index/firestorm/analysis_test.go
- index/firestorm/comp.go
- index/firestorm/dict_updater.go
- index/firestorm/dict_updater_test.go
- index/firestorm/firestorm.go
- index/firestorm/firestorm.md
- index/firestorm/lookup.go
- index/firestorm/lookup_test.go
- index/firestorm/termfreq.go
In contrast to yesterday's pull request (https://github.com/blevesearch/bleve/pull/304), this most recent pull request has two additional changes...
- a firestorm.Batch() improvement to avoid more data copying in append()'s.
- thanks to @nuss-justin, for feedback that led to dropping a change as the go compiler does some smart things when reading a map via this kind of idiom: myMap[string(bytesKey)].  Thanks for helping to make this better and helping to produce negative lines of code!
dropping a change
> perf 20160102

- analysis/benchmark_test.go
- analysis/freq.go
- analysis/freq_test.go
- document/field_datetime.go
- document/field_numeric.go
- document/field_text.go
- index/firestorm/dict_updater.go
- index/upside_down/upside_down.go
With this change, TermLocations are computed and maintained only if
includeTermVectors is enabled, for higher performance.
> analyze locations only if includeTermVectors enabled

- index/store/metrics/writer.go
Previously, the metrics code would incorrectly return a non-BatchEx.
> metrics implements BatchEx correctly

- mapping_document.go
Assert non-float types to type float64, then re-process.
> Handle numeric fields other than float64 in processProperty

- .gitignore
- index_meta.go
Our continuous integration tests are failing with `cannot create new index, path already exists` when creating a test index.  I can't reproduce this error on my laptop (macbook pro) -- it only happens in CI (shippable.com, ubuntu in a Docker container).  I added a line to explicitly remove the path before creating the index, and am seeing the same failure.  I think the code I changed was masking the actual error by always returning the "path already exists" error without first checking the error type.
> Fix masking of error when creating index (minor error reporting fix)

- index/store/moss/lower.go
The iterator used by moss starts off positioned so that Current() works, so
invoking Next() right off at the start of the loop was incorrect.
> MB-18441 - moss lower-level iterator starts  positioned on current

- index.go
- index_alias_impl.go
- index_alias_impl_test.go
- index_impl.go
- index_test.go
- search/collector.go
- search/collectors/collector_top_score.go
- search/collectors/collector_top_score_test.go
our implementation uses: golang.org/x/net/context
New method SearchInContext() allows the user to run a search
in the provided context.  If that context is cancelled or
exceeds its deadline Bleve will attempt to stop and return
as soon as possible.  This is a *best effort* attempt at this
time and may *not* be in a timely manner.  If the caller must
return very near the timeout, the call should also be wrapped
in a goroutine.
The IndexAlias ipmlementation is affected in a slightly more
complex way.  In order to return partial results when a timeout
occurs on some indexes, the timeout is strictly enforced, and
at the moment this does introduce an additional goroutine.
The Bleve implementation honoring the context is currently
very course-grained.  Specifically we check the Done() channel …
> introduce ability for searches to timeout or be cancelled

- index/store/moss/lower.go
- index/store/moss/store.go
The key was moving the i++ to the right place.
Also, tweaked the logging along the way to tracking this down.
> moss lowerLevelUpdate didn't handle batches of size 1

- index_meta.go
From the comment on the line above, it looks like this was intended to be a call to `os.MkdirAll` instead of `os.Mkdir`.  I caught this because one of my tests is failing to create the test index at a location where the full parent path does not exist.
> Minor fix to ensure full index path exists

- index/store/goleveldb/store.go
I spent a couple hours on this last night as a workaround for #374.
The implementation removes all DictionaryTerm entries with Count=0 from the index, in configurable batches, within a transaction.  Originally I did this all in one large transaction, but settled on this approach to avoid locking out other writers for an extended period of time.  A batch size of 250 seems like a good default number for a server-based implementation...I'll be using batch sizes of more like 50-100 in my app (running on a single core ARMv7).
I ran this test, that I wrote before submitting #374:
>1.  Create and initialize a new index, take snapshot of size of index folder
>1.  Do the following 5 times:
>    1.  Add 1000 documents to the index
>    1.  Take snapshot of size of index folder
>    1.  Delete all …
> Remove DictionaryTerm with count 0 during compact (workaround for #374)

- index/store/moss/lower.go
- index/store/moss/store.go
Due to some local bleve-blast performance runs on my OSX dev box, I saw that the deferred sorting option in moss seemed to help a little with throughput.  So, this change flips on DeferredSort to true by default.
Also, I added an optional "mossStoreOptions" to the map[string]interface{} config, for more configurability.  For example, we should be able to turn that new DeferredSort to false via this new "mossStoreOptions".
Finally, I also tried to simplify the InitMossStore() parameters list by passing along the full options struct.
> configurable mossStoreOptions and DeferredSort defaults to true

- index/store/boltdb/store.go
- index/store/goleveldb/store.go
This is similar to PR #376 (workaround for issue #374), except for boltdb.  
Sorry I didn't reach this conclusion sooner, but it looks like goleveldb won't work for our application even with the new compact logic.  In continued stress testing on a gateway device (128MB RAM, ~100MB available flash), we saw the following:
1.  Within `Compact`, can successfully remove unused `DictionaryTerm` entries.
1.  Application crashes (out of memory) during call to `ldbs.db.CompactRange(util.Range{nil, nil})`.  Apparently `CompactRange` uses a lot of extra memory to remap the file.
I swapped out goleveldb for boltdb and tried all of this again.  With boltdb, we can do the following to manage our filesystem resources without crashing:
1.  Calculate the maximum size we can allow the DB file to reach …
> Compact for boltdb (workaround for #374)

- analysis/token_filters/ngram_filter/ngram_filter.go
- analysis/token_filters/ngram_filter/ngram_filter_test.go
This update merely the configuration of the ngram filter more natural.
It achieves the following:
1) Prevents panics is the conf map does not contain float64 as min and max values
2) Extends the type conversion for min/max fields to both float64 and int.
The int is a more natural type for the conf specification since these values are always integers.
> Preventing panic on ngram initialization, and extending the type conversion

- analysis/token_filters/camelcase_filter/parser.go
- analysis/token_filters/edge_ngram_filter/edge_ngram_filter.go
- analysis/token_filters/ngram_filter/ngram_filter.go
- analysis/token_filters/truncate_token_filter/truncate_token_filter.go
Simple refactoring on the following token filters:
Ngram
EdgeNgram
CamelCase
Truncate
Removing duplicate code and referencing the util code in the analysis package.
All tests have passed.
> removing duplicate code by reusing util.go in analysis

- index/store/boltdb/store.go
- index/store/boltdb/store_test.go
- index/store/boltdb/writer.go
Hi again,
I couldn't resist experimenting with this setting when I saw it in the boltdb `Bucket` documentation:
```go
// Sets the threshold for filling nodes when they split. By default,
// the bucket will fill to 50% but it can be useful to increase this
// amount if you know that your write workloads are mostly append-only.
//
// This is non-persisted across transactions so it must be set in every Tx.
FillPercent float64
```
Documents in our IoT "device reports" index are immutable for as long as they're retained.  I found that page utilization on this index is very much improved with higher `FillPercent` values.  For example, using a value of `0.8` (instead of the default `0.5`), we're able to index 20-25% more reports within a given index file size.
This PR adds `fillPercent` as an …
> Add bucket fillPercent option for boltdb

- examples_test.go
- query_match.go
- query_test.go
Match query operator, either `or` (default), or `and` controls whether analyzed terms construct disjunction, or conjunction query.
> Added match query operator

- index/store/moss/reader.go
The moss KV store adapter's Get() implementation was incorrectly
transforming a 0-length val (e.g., []byte{}) into a nil val.
> MB-20101 - moss KV fix Get() of 0-length vals

- index/index.go
- index/upside_down/index_reader.go
- search.go
- search/facets/facet_builder_datetime.go
- search/facets/facet_builder_numeric.go
- search/facets/facet_builder_terms.go
- search/facets_builder.go
1. Eliminate field cache lookup for each document match times number of fields and terms
2. Make sure to return only relevant fields in the FieldTerms
On a sample of a few 1000s documents with back index rows ranging from 10s to 10000s single facet search returns in less than a second instead of almost 4 min of 100% CPU.
> Make facets much faster

- index/store/moss/iterator.go
- index/store/moss/reader.go
The moss KV store iterator Next() method is invoked in the hot path of search processing, so removing/simplifying some of its code.
> tighter moss KV store iterator handling

- analysis/language/en/possessive_filter_en.go
- analysis/language/en/possessive_filter_en_test.go
previous impl always did full utf8 decode of rune
if we assume most tokens are not possessive this is unnecessary
and even if they are, we only need to chop off last to runes
so, now we only decode last rune of token, and if it looks like
s/S then we proceed to decode second to last rune, and then
only if it looks like any form of apostrophe, do we make any
changes to token, again by just reslicing original to chop
off the possessive extension
> speed up english possessive filter

- analysis/token_filters/stop_tokens_filter/stop_tokens_filter.go
- analysis/token_filters/stop_tokens_filter/stop_tokens_filter_test.go
the token stream resulting from the removal of stop words must
be shorter or the same length as the original, so we just
reuse it and truncate it at the end.
> avoid allocation in stop token filter

- analysis/util.go
- analysis/util_test.go
avoid allocating unnecessary intermediate buffer
> encode runes directly into buffer

- analysis/token_filters/porter/porter.go
- analysis/token_filters/porter/porter_test.go
1.  porter stemmer offers method to NOT do lowercasing, however
to use this we must convert to runes first ourself, so we did this
2.  now we can invoke the version that skips lowercasing, we
already do this ourselves before stemming through separate filter
due to the fact that the stemmer modifies the runes in place
we have no way to know if there were changes, thus we must
always encode back into the term byte slice
added unit test which catches the problem found
NOTE this uses analysis.BuildTermFromRunes so perf gain is
only visible with other PR also merged
future gains are possible if we udpate the stemmer to let us
know if changes were made, thus skipping re-encoding to
[]byte when no changes were actually made
> improve perf of porter stemmer

- index/store/moss/lower.go
- index/store/moss/stats.go
- index/store/moss/store.go
- vendor/manifest
This change depends on the recently introduced mossStore Stats() API
in github.com/couchbase/moss 564bdbc0 commit.
Most of the change involves propagating the mossStore instance (the
statsFunc callback) so that it's accessible to the KVStore.Stats()
method.
See also: http://review.couchbase.org/#/c/67524/
> index/store/moss KV backend propagates mossStore's Stats()

- http/debug.go
- index.go
- index/index.go
- index/smolder/dump.go
- index/smolder/dump_test.go
- index/smolder/index_reader.go
- index/smolder/smoldering.go
- index/smolder/smoldering_test.go
- index/upside_down/dump.go
- index/upside_down/dump_test.go
- index/upside_down/index_reader.go
- index/upside_down/upside_down.go
- index/upside_down/upside_down_test.go
- index_alias_impl.go
- index_alias_impl_test.go
- index_impl.go
- search/collectors/search_test.go
- search/searchers/search_match_all.go
- search/searchers/search_term.go
- search/searchers/search_term_test.go
- utils/bleve_dump/main.go
The DumpXXX() methods were always documented as internal and
unsupported.  However, now they are being removed from the
public top-level API.  They are still available on the internal
IndexReader, which can be accessed using the Advanced() method.
The DocCount() and DumpXXX() methods on the internal index
have moved to the internal index reader, since they logically
operate on a snapshot of an index.
> BREAKING CHANGE - removed DumpXXX() methods from bleve.Index

- index/upside_down/reader.go
- index/upside_down/row.go
This commit modifies the upside_down TermFrequencyRow parseKDoc() to
skip the ByteSeparator (0xFF) scan, as we already know the term's
length in the UpsideDownCouchTermFieldReader.
On my dev box, results from bleve-query test on high frequency terms
went from previous 107qps to 124qps.
> skip termFrequencyRow 0xFF scan as term length is already known

- docs/merge-coverprofile.go
this should prevent people that run:
go get github.com/blevesearch/bleve/...
from getting a useless "docs" program in their bin/ dir
> add build tag protecting merge-coverprofile

- index/store/boltdb/writer.go
We tried to index some terms that were too big and bolt failed writing them (key too large) but now the index hangs because the transaction remained open.
> Make sure that the transaction is closed if there is an error

- query_disjunction.go
See also: https://issues.couchbase.com/browse/MB-21046
This reverts commit 6d6fae289509c9deb27710e6f28d56b1ae587c06.
It turns out that boolean searcher was depending on its 'should'
constituent (a disjunction query) and its min state changes, so a
rewrite wasn't safe/correct given this situation.
> Revert "optimize when disjunction query has only a single child"

- config.go
- index.go
- index/store/boltdb/store.go
- index/store/goleveldb/store.go
- index/store/gtreap/store.go
- index/store/gtreap/store_test.go
- index/store/metrics/metrics_test.go
- index/store/metrics/store_test.go
- index/store/moss/lower.go
- index_impl.go
- index_test.go
- search/searchers/base_test.go
- search/searchers/search_docid_test.go
- search/searchers/search_term_test.go
Previously bleve allowed you to create a memory-only index by
simply passing "" as the path argument to the New() method.
This was not clear when reading the code, and led to some
problematic error cases as well.
Now, to create a memory-only index one should use the
NewMemOnly() method.  Passing "" as the path argument
to the New() method will now return os.ErrInvalid.
Advanced users calling NewUsing() can create disk-based or
memory-only indexes, but the change here is that passing ""
as the path argument no longer defaults you into getting
a memory-only index.  Instead, the KV store is selected
manually, just as it is for the disk-based solutions.
Here is an example use of the NewUsing() method to create
a memory-only index:
```
NewUsing("", indexMapping, Config.DefaultIndexType, …
```
> BREAKING CHANGE - new method to create memory only index

- index/store/metrics/batch.go
- index/store/metrics/iterator.go
- index/store/metrics/reader.go
- index/store/metrics/stats.go
- index/store/metrics/store.go
- index/store/metrics/writer.go
First, we no longer export the internal metrics timers (opens door for vendoring go-metrics in the future)
~~Second, we aggregate stats on an iterator, the record those numbers on Close() of the iterator.  Internally, the metrics library maintains a mutex on the stat, which must be acquired/released, so we want avoid that in the hottest paths.~~
> Metrics Work

- analysis/token/lowercase/lowercase.go
The LowerCaseFilter works on the original slice to avoid allocations,
so skipping already lowercased runes avoids unnecessary work.
```
benchmark                      old ns/op     new ns/op     delta
BenchmarkLowerCaseFilter-8     1302          815           -37.40%
```
> Skip already lowercased runes on transformation.

- analysis/token/lowercase/lowercase.go
- analysis/token/lowercase/lowercase_test.go
Σ maps to σ, except at the end of a word where it maps to ς.
This is the only conditional (contextual) but language-independent
mapping in unicode.
fixes #468
> Address special unicode sigma at end of term when lowercasing.

- analysis/token/lowercase/lowercase.go
- index/store/moss/reader.go
- search/searcher/search_disjunction.go
In this commit, I saw that there was a simple incrementBytes()
implementation elsewhere in bleve that seemed simpler than using the
big int package.
> reuse incrementBytes() in moss KV store integration

- search/searcher/search_disjunction.go
This commit reverts a previous optimization attempt 3f588cd4a that
tried to trim or shrink the array of child searchers in a
search-disjunction.
I've been looking at this code all day so far, with lots of printf's,
but still don't have a solid theory as to why this optimization
introduces a functionality regression.
But, the regression is indisputable.  Removing the code that trims
the child-searchers-array seems to correctly restore correct behavior.
> revert optimization that trims search-disjunction child searchers

- cmd/bleve/cmd/check.go
bleve check was a consistency checking tool originally developed
as a part of cbft.  currently it checks that the term dictionary
counts match the number of postings for the term.  in the future
additional checks could be added.  this tool has been back
ported to bleve as we've now adopted a single common tool for
both cbft and bleve.
> add the bleve check tool

- cmd/bleve/vendor/github.com/inconshreveable/mousetrap/LICENSE
- cmd/bleve/vendor/github.com/inconshreveable/mousetrap/trap_others.go
- cmd/bleve/vendor/github.com/inconshreveable/mousetrap/trap_windows.go
- cmd/bleve/vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
- cmd/bleve/vendor/manifest
our policy has been to vendor the libraries required for the
command-line portion of the bleve command-line tool.  this
included spf13/cobra etc, unfortunately we missed this library
as it is only required for windows users.
> vendor mousetrap

- mapping/document.go
- mapping/mapping_test.go
- mapping/reflect.go
This PR adds a field `StructTagKey` to `mapping.DocumentMapping` that allows users to override which key is used when looking for alternate field names / disablement in struct tags during document mapping.  This makes document mapping easier for organizations that want to index existing data structures (including redefining the field names, disabling, etc.) that have explicitly disabled json tags for other reasons.  The change has no effect on existing usage as the default is still "json". Tests have been added (copied and modified really) using "bleve" as an alternate tag.
> adding override for "json" in struct tags, tests

- search/searcher/search_regexp.go
After initializing its disjunction searcher, a regexp searcher turned out to be just a wrapper around its disjunction searcher.  So, this minor optimization just returns the disjunction searcher directly.
> optimize NewRegexpSearcher to return its disjunction searcher

- index_impl.go
- search.go
changed date parsing to NOT update internal state of the date
range object (avoids races)
second, when marshaling a facet date range, we now use the
string version, if the time.Time is zero and the string version
is not ""
> fix date facets when using MultiSearch

- search/query/query.go
- search/query/query_test.go
presence of the "bool" key triggers parsing as a BoolFieldQuery
fixes #498
> add support for parsing BoolFieldQuery from JSON

- index/store/moss/lower.go
- index/store/moss/store.go
This change adds methods that provide access to the actual, underlying
mossStore instance in the bleve/index/store/moss KVStore adaptor.
This enables applications to utilize advanced, mossStore-specific
features (such as partial rollback of indexes).  See also
https://issues.couchbase.com/browse/MB-17805
> bleve/index/store/moss - accessor for underlying mossStore

- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
In the first patch we use early continues to reduce the level of nesting. The following two patches fix some minor issues in the code and in the last patch we add checking of the DocumentMatch.Location values to the phrase searcher test.
If you prefer to have some of the patches squashed, just let me know.
> Refactor PhraseSearcher

- analysis/lang/cjk/analyzer_cjk.go
The variable has UnicodeTokenizer object, but its name is "whitespaceTokenizer".
> fix the confusing variable name

- search/query/regexp.go
- search/query/wildcard.go
- search/searcher/search_regexp.go
While researching an observed performance issue with wildcard
queries, it was observed that the LiteralPrefix() method on
the regexp.Regexp struct did not always behave as expected.
In particular, when the pattern starts with ^, AND involves
some backtracking, the LiteralPrefix() seems to always be the
empty string.
The side-effect of this is that we rely on having a helpful
prefix, to reduce the number of terms in the term dictionary
that need to be visited.
This change now makes the searcher enforce start/end on the term
directly, by using FindStringIndex() instead of Match().
Next, we also modified WildcardQuery and RegexpQuery to no
longer include the ^ and $ modifiers.
Documentation was also udpated to instruct users that they should
not include the ^ and $ modifiers in their …
> improve performance of regular expression and wildcard queries

- index/upsidedown/analysis.go
- index/upsidedown/dump.go
- index/upsidedown/index_reader.go
- index/upsidedown/row.go
- index/upsidedown/row_test.go
- index/upsidedown/upsidedown.go
- index/upsidedown/upsidedown.pb.go
- index/upsidedown/upsidedown.proto
Previously term entries were encoded pairwise (field/term), so
you'd have data like:
```
F1/T1 F1/T2 F1/T3 F2/T4 F3/T5
```
As you can see, even though field 1 has 3 terms, we repeat the F1
part in the encoded data.  This is a bit wasteful.
In the new format we encode it as a list of terms for each field:
```
F1/T1,T2,T3 F2/T4 F3/T5
```
When fields have multiple terms, this saves space.  In unit
tests there is no additional waste even in the case that a field
has only a single value.
Here are the results of an indexing test case (beer-search):
```
$ benchcmp indexing-before.txt indexing-after.txt
benchmark               old ns/op       new ns/op       delta
BenchmarkIndexing-4     11275835988     10745514321     -4.70%
benchmark               old allocs     new allocs     delta …
```
> INDEX FORMAT CHANGE: change back index row value

- index_test.go
- search/highlight/format/ansi/ansi.go
- search/highlight/format/html/html.go
- search/highlight/highlighter/simple/fragment_scorer_simple.go
- search/highlight/highlighter/simple/highlighter_simple.go
- search/highlight/term_locations.go
- search/highlight/term_locations_test.go
- search/scorer/scorer_term.go
- search/search.go
- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
this originated from a misunderstanding of mine going back
several years.  the values need not be float64 just because
we plan to serialize them as json.
there are still larger questions about what the right type should
be, and where should any conversions go.  but, this commit
simply attempts to address the most egregious problems
> remove use of float64 to represent int things

- search/query/match_phrase.go
- search/query/match_phrase_test.go
- search/query/multi_phrase.go
- search/query/phrase.go
- search/query/query.go
- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
- test/tests/phrase/searches.json
the logic of how a phrase search works should be an internal
detail of the phrase searcher.  further, these changes will
allow proper scoring of phrase matches, which require access
to the underlying searcher objects, which were hidden in the
previous approach.
> move phrase search logic into phrase searcher

- index/store/moss/lower.go
moss store will soon support child collections. This change adds corresponding implementations of the new moss.Snapshot interface methods ChildCollectionNames and ChildCollectionSnapshot.
> Add Snapshot interface methods for moss child collections feature

- search/query/boolean.go
- search/query/conjunction.go
- search/query/disjunction.go
- search/query/query_string_parser.go
- search/query/query_string_parser_test.go
1) disjunction and conjunction queries now support a
"query string mode".  By default they do not operate
in this mode.  When in this mode, any disjunct/conjunct
which evaluates to MatchNone searcher, will be removed
from the disjunction/conjunction.  If the query ends
up with NO conjuncts/disjuncts, it will itself
return the MatchNone seacher.
2) boolean query also supports a query string mode.  when in
this mode, the Must, Should and MustNot searchers are all put
into query string mode.
3) rewriting of negation only queries (like -foo) now take into
account the rewriting rules above, and those are handled first.
this means that we rewrite correctly in case of +stoword -foo
4) the empty query string is now valid, and returns 0 hits.
previously this was considered a validation error.
> improve query string compatibility

- index/index.go
- index/upsidedown/index_reader.go
- index/upsidedown/row.go
- index/upsidedown/row_test.go
- index/upsidedown/upsidedown_test.go
- search/collector/search_test.go
- search/collector/topn.go
- search/facet/facet_builder_datetime.go
- search/facet/facet_builder_numeric.go
- search/facet/facet_builder_numeric_test.go
- search/facet/facet_builder_terms.go
- search/facet/facet_builder_terms_test.go
- search/facets_builder.go
- search/search.go
- search/sort.go
previously we parsed/returned large sections of the documents
back index row in order to compute facet information.  this
would require parsing the protobuf of the entire back index row.
unfortunately this creates considerable garbage.
this new version introduces a visitor/callback approach to
working with data inside the back index row.  the benefit
of this approach is that we can let the higher-level code
see values, prior to any copies of data being made or
intermediate garbage being created.  implementations of
the callback must copy any value which they would like to
retain beyond the callback.
NOTE: this approach is duplicates code from the
automatically generated protobuf code
NOTE: this approach assumes that the "field" field be serialized
before the "terms" field.  This is …
> reduce garbage created while processing facets

- index/store/moss/store.go
- vendor/manifest
@mschoch , @steveyen , Attempt to make configurable CloseEx/Abort for mossStore.
[The store level close would happen twice due to the following collection close which is there in the original code. But by adding an extra check at the Store level close, we may avoid code level regressions(nil dereferencing) on it, but not sure whether thats  a hack or a proper way to do it]
Reference: http://review.couchbase.org/#/c/74385/
> Store abort close

- search/collector/topn_test.go
These two optimizations have some API impacts...
- one adds more API's to allow advanced apps to prevent more garbage creation by reusing DocumentMatchPool's.
- the other subtly changes creation of SearchResults by possibly returning nil Errors and nil Facets instead of empty map instances.  (An alternative might be to return references to preallocated, global, empty map singletons, but that's also a subtle change in behavior, so I figured nil's might be cleaner and avoid issues of folks inadvertently stuffing entries into supposedly "empty" maps.)
Running a modified bleve-query that uses the above two commits and the new DocumentMatchPool context API's (by adding a sync.Pool to bleve-query)... on a 50K wiki docs index, low frequency term query ("shoch", which returns 5 hits), queries per …
> some optimizations that have API impact

- search/collector/topn.go
Additional testing has shown that the heap collector performs
significantly better when larger numbers of hits are requested.
The heap is also faster (though very close) when fewer (10) hits
are requested.
Here are the numbers from my laptop:
slice:
```
go test -run=xxx -bench=. -benchmem
BenchmarkTop10of10000Scores-4        	    5000	    396943 ns/op	    2472 B/op	      26 allocs/op
BenchmarkTop100of10000Scores-4       	    2000	    630894 ns/op	   18848 B/op	     116 allocs/op
BenchmarkTop1000of10000Scores-4      	     100	  14996445 ns/op	  176552 B/op	    1016 allocs/op
BenchmarkTop10000of100000Scores-4    	       1	1878796320 ns/op	 1857768 B/op	   19023 allocs/op
BenchmarkTop10of100000Scores-4       	     500	   3858309 ns/op	    2480 B/op	      26 allocs/op …
```
> switch collector store impl from slice to heap

- search/scorer/scorer_term.go
- search/scorer/scorer_term_test.go
- search/searcher/search_fuzzy.go
- search/searcher/search_geoboundingbox.go
- search/searcher/search_geopointdistance.go
- search/searcher/search_multi_term.go
- search/searcher/search_numeric_range.go
- search/searcher/search_regexp.go
- search/searcher/search_term.go
- search/searcher/search_term_prefix.go
- TermSearcher has alternate constructor if term is []byte, this can avoid
copying in some cases.  TermScorer updated to accept []byte term. Also
removed a few struct fields which were not being used.
- New MultiTermSearcher searches for documents containing any of a list of
terms.  Current implementation simply uses DisjunctionSearcher.
- Several other searcher constructors now simply build a list of terms and
then delegate to the MultiTermSearcher
- NewPrefixSearcher
- NewRegexpSearcher
- NewFuzzySearcher
- NewNumericRangeSearcher
- NewGeoBoundingBoxSearcher and NewGeoPointDistanceSearcher make use of
the MultiTermSearcher internally, and follow the pattern of returning
an existing search.Searcher, as opposed to their own wrapping struct.
- Callback filter functions used in …
> refactor searchers

- query.go
- search/query/query.go
- search/query/query_test.go
- search/query/term_range.go
- search/searcher/search_term_range.go
- search/searcher/search_term_range_test.go
- test/tests/basic/searches.json
The term range query is not often used in full-text queries, but
can be useful when filtering on keyword indexed text terms in
the index.
The JSON syntax to do a TermRange query is the same as for
NumericRange, but the min/max values must be string and not
float64.
> introduce new query TermRange

- index_alias_impl.go
- search/sort.go
When performing a MultiSearch, we create child SearchRequests
from the original SearchRequest.  In doing so we copy many fields.
But, copying of the SortOrder was incorrect, as this contains
state, and distint SortOrder objects must be used.  This change
introduces a Copy() method to the SearchSort interface, and
to the SortOrder types.  MultiSearch now creates a new copy of
the SortOrder for each child request.
> fix race condition in incorrectly shared state in MultiSearch

- search/collector/heap.go
- search/collector/list.go
- search/collector/slice.go
- search/collector/topn.go
we now use the slice store when size+skip <= 10
and use the heap store when size+skip > 10
here are the new perf numbers:
```
go test -run=xxx -bench=. -benchmem
BenchmarkTop10of0Scores-4            	 1000000	      1150 ns/op	    2304 B/op	      15 allocs/op
BenchmarkTop10of3Scores-4            	 1000000	      1417 ns/op	    2304 B/op	      18 allocs/op
BenchmarkTop10of10Scores-4           	 1000000	      2133 ns/op	    2312 B/op	      25 allocs/op
BenchmarkTop10of25Scores-4           	  500000	      3410 ns/op	    2464 B/op	      26 allocs/op
BenchmarkTop10of50Scores-4           	  300000	      5174 ns/op	    2464 B/op	      26 allocs/op
BenchmarkTop10of10000Scores-4        	    5000	    342955 ns/op	    2488 B/op	      26 allocs/op
BenchmarkTop100of0Scores-4           	  300000 …
```
> topn collector switch approach based on size+skip

- analysis/lang/de/analyzer_de.go
- analysis/lang/de/analyzer_de_test.go
- analysis/lang/de/german_normalize.go
- analysis/lang/de/german_normalize_test.go
- analysis/lang/de/light_stemmer_de.go
- analysis/lang/de/stop_filter_de.go
- analysis/lang/de/stop_words_de.go
this introduces new German light stemmer
and moves the other pure Go german analysis components back
in from the blevex package
the libstemmer version of the stemmer will remain in blevex
> add a pure Go German analyzer

- analysis/lang/es/analyzer_es.go
- analysis/lang/es/analyzer_es_test.go
- analysis/lang/es/light_stemmer_es.go
- analysis/lang/es/stop_filter_es.go
- analysis/lang/es/stop_words_es.go
this introduces a new light Spanish stemmer
and move the other pure Go Spanish analysis components back
in from the blevex package
the libstemmer version of the stemmer will remain in blevex
> add a pure Go Spanish analyzer

- search/collector/heap.go
The previous heap Final() loop would decrement count all the way to 0
when it only has to fill enough of the return slice.
> optimmize heap collector Final() for large counts

- search/searcher/search_term_range.go
- search/searcher/search_term_range_test.go
if min and max are the same term
and the term is in dictionary
and both in and max are set to exclusive
then we would panic attempting to access element -1 of a slice.
now, after trimming the slice, we recheck that the length is > 0
> fix panic in term range search

- index.go
- mapping/index.go
- mapping/mapping.go
Many existing structs already have a Type field or method which
conflicts with the bleve Classifier interface.  To address this
without breaking existing applications, we introduce an
alternate BleveType() method which will be checked first.  The
interface describing this method is private, as it should never
need to be referenced outside this package.
fixes #283
> add support for BleveType() alternative for type detection

- mapping/document.go
- mapping/mapping_test.go
Sometimes you have structs which contain data which isn't
exported, or for which the correct data to index isn't just the
contents of it's exported fields.  In these cases your struct
can implement TextMarshaler to return a suitable text
representation.
Previously bleve did not recognize this interface and do anything
to use it.  Now, if the field containing such a struct is
explicitly mapped as "text" and if the struct (or pointer to it)
implements TextMarshaler, we index a text field with the
contents returned by MarshalText().
For backwards compatibilty, dynamic mappings will never use
this feature, and will continue to traverse into the struct
and index the exported fields directly.
fixes #281
> add support for mapping to recognize/use TextMarshaler interface

- cmd/bleve/cmd/query.go
I have found the bleve command is helpful for debugging indexes. I added a --sort-by, -b option for the query sub-command to match the current Sort interface for search results.
> Adding --sort-by to query option for bleve command

- search/query/query_string.go
In the case of ```QueryStringQuery```, when reusing queries, each search request re-parses the the queries. It would be nice to be able to pre-parse the queries, at the same time validating them.
> Allow pre parsing query strings

- mapping/document.go
- mapping/mapping_test.go
We recenlty introduced support for indexing the content of
things implementing TextMarshaler.  Since often times interfaces
are implemented via pointer receivers, we added support to
introspect pointers (previously we just dereferenceed them and
traversed into their underlying structs).  However, in doing so
we neglected to consider the case where the pointer does
implement the interface we care about, but happens to be nil.
fixes #603
> fix nil ptr panic on newly introduced text marshaler support

- search/searcher/search_numeric_range.go
previously the query string queries were modified to aid in
compatibility with other search systems.  this change:
f391b991c20f02681bacd197afc6d8aed444e132
has a problem when combined with:
77101ae424bb385095b8094dc9fd1cd116a3de8c
due to the introduction of MatchNoneSearchers being returned
in a case where previously they never would.
the fix for now is to simply return disjunction queries on 0
terms instead.  this ultimately also matches nothing, but avoids
triggering the logic which handles match none searchers in a
special way.
> fix issue with numeric range queries in query string

- index/upsidedown/reader.go
the implementation of the doc id search requires that the list
of ids be sorted.  however, when doing a multisearch across
many indexes at once, the list of doc ids in the query is shared.
deeper in the implementation, the search of each shard attempts
to sort this list, resulting in a data race.
this is one example of a potentially larger problem, however
it has been decided to fix this data race, even though larger
issues of data owernship may remain unresolved.
this fix makes a copy of the list of doc ids, just prior to
sorting the list.  subsequently, all use of the list is on the
copy that was made, not the original.
fixes #518
> fix data race in doc id search

- mapping/document.go
- mapping/mapping_test.go
With a document like:
```
{
"foo": "value",
"bar": {
"foo": "value2",
"baz": "value3"
}
}
```
And a mapping like:
```
mapping := bleve.NewIndexMapping()
mapping.IndexDynamic = false
mapping.DefaultMapping = bleve.NewDocumentStaticMapping()
mapping.DefaultMapping.AddFieldMappingsAt("foo", bleve.NewTextFieldMapping())
```
The default mapper will incorrectly index `bar.foo` as a dynamic field, but will correctly skip `bar.baz`.
> mapping: Fix closestDocMapping selecting wrong mapping

- index/scorch/introducer.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/snapshot_index.go
A new global variable, NumSnapshotsToKeep, represents the default
number of old snapshots that each scorch instance should maintain -- 0
is the default.  Apps that need rollback'ability may want to increase
this value in early initialization.
The Scorch.eligibleForRemoval field tracks epoches which are safe to
delete from the rootBolt.  The eligibleForRemoval is appended to
whenever the ref-count on an IndexSnapshot drops to 0.
On startup, eligibleForRemoval is also initialized with any older
epoch's found in the rootBolt.
The newly introduced Scorch.removeOldSnapshots() method is called on
every cycle of the persisterLoop(), where it maintains the
eligibleForRemoval slice to under a size defined by the
NumSnapshotsToKeep.
A future commit will remove actual storage files in order to match …
> scorch cleanup of the rootBolt of old snapshots

- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/scorch.go
A race & solution found by Marty Schoch... consider a case when the
merger might grab a nextSegmentID, like 4, but takes awhile to
complete.  Meanwhile, the persister grabs the nextSegmentID of 5, but
finishes its persistence work fast, and then loops to cleanup any old
files.  The simple approach of checking a "highest segment ID" of 5 is
wrong now, because the deleter now thinks that segment 4's zap file is
(incorrectly) ok to delete.
The solution in this commit is to track an ephemeral map of filenames
which are ineligibleForRemoval, because they're still being written
(by the merger) and haven't been fully incorporated into the rootBolt
yet.
The merger adds to that ineligibleForRemoval map as it starts a merged
zap file, the persister cleans up entries from that map when it
persists …
> scorch tracks zap files that can't be removed yet

- index/scorch/scorch_test.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
The cachedDocs preparation has to happen for all docs in the field,
not just on the currently requested docNum.
Also, as part of this commit, there's a loop optimization where we no
longer use bytes.Split() on the terms buffer, thus avoiding garbage
creation.
> scorch fix for TestSortMatchSearch

- index/scorch/persister.go
Found from "go test -race ./..."
WARNING: DATA RACE
Read at 0x00c420088060 by goroutine 48:
github.com/blevesearch/bleve/index/scorch.(*Scorch).AddEligibleForRemoval()
/Users/steveyen/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:348 +0x6d
Previous write at 0x00c420088060 by goroutine 31:
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadFromBolt.func1()
/Users/steveyen/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:332 +0x87b
github.com/boltdb/bolt.(*DB).View()
/Users/steveyen/go/src/github.com/boltdb/bolt/db.go:629 +0xc1
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadFromBolt()
/Users/steveyen/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:290 +0xa1
github.com/blevesearch/bleve/index/scorch.(*Scorch).Open() …
> scorch fix data race w/ AddEligibleForRemoval

- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_doc.go
- index/scorch/snapshot_index_tfr.go
On a couple of micro benchmarks on a dev macbook using bleve-query on
an index of 50K wikipedia docs, scorch is now in more the same
neighborhood of upsidedown/moss...
high-freq term search "text:date"...
400 qps - upsidedown/moss
360 qps - scorch before
404 qps - scorch after
zero-freq term search "text:mschoch"...
100K qps - upsidedown/moss
55K qps - scorch before
99K qps - scorch after
Of note, the scorch index had ~150 *.zap files in it, which likely
made made the worker goroutine overhead more costly than for a case
with few segments, where goroutine and channel related work appeared
relatively prominently in the pprof SVG's.
> scorch removed worker goroutines from TermFieldReader()

- index/scorch/mergeplan/merge_plan.go
- index/scorch/mergeplan/merge_plan_test.go
Previously, CalcBudget() was treating
MergePlanOptions.SegmentsPerMergeTask as the growth factor while
computing the idealized staircase of segments.
This change introduces a TierGrowth option to MergePlanOptions for
more control and so that SegmentsPerMergeTask can be tweaked
independently of the tier growth factor.
> scorch mergeplan added TierGrowth option

- index/scorch/introducer.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/scorch_test.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
The changes...
- allow a segmentIntroduction struct to have a nil segment
- persisted notification channels are now at the Scorch struct level (see rootPersisted field) instead of at the SegmentSnapshot level, so no more copying or "carrying over" the persisted notification channels from segment snapshot to segment snapshot.
- added an epochWatcher struct, which is how the persister now makes requests to the introducer when it wants to be notified when there's an updated root.  This replaces the double checking logic in the persister, removing a race condition.
> scorch handle zero-doc segments

- index/scorch/mergeplan/merge_plan.go
Rather than relying on heuristic scoring to weed out empty segments, this commit
does the weeding out of empty segments explicitly and up front.
> scorch mergeplan explicitly weeds out empty segments

- index/scorch/segment/segment.go
- index/scorch/segment/zap/posting.go
With this change, there are no more memory allocations in the calls to
PostingsIterator.Next() in the micro benchmarks of bleve-query.  On a
dev macbook, on an index of 50K wikipedia docs, using high frequency
search of "text:date"...
400 qps - upsidedown/moss
565 qps - scorch before
680 qps - scorch after
Related, looks like zap's PostingsIterator.Next() always allocates brand
new locations / array-positions, so it's safe there.
> scorch reuses Posting instance in PostingsIterator.Next()

- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/cmd/zap/cmd/dict.go
- index/scorch/segment/zap/cmd/zap/cmd/explore.go
- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/segment.go
- index/store/moss/lower.go
- index/store/moss/store.go
- search/search.go
Also, scrubbed an old couchbaselabs/moss reference in comments.
Also, go fmt.
> import couchbase/vellum instead of couchbaselabs/vellum

- index/scorch/segment/zap/posting.go
- index/scorch/snapshot_segment.go
This proposed approach avoids building a temporary AndNot() bitmap,
following the same kind of optimization used by mem segments.
> scorch optimize zap Count()

- index/scorch/snapshot_index.go
With more pprof focusing (zooming in on a particular func), there were
still some memory allocations showing up with docNumberToBytes() in
micro benchmarks of bleve-query.  On a dev macbook, on an index of 50K
wikipedia docs, using search of relatively common "text:date"...
400 qps - upsidedown/moss
680 qps - scorch before
775 qps - scorch after
> scorch docNumberToBytes() checks cap(buf) before allocating

- index/scorch/scorch.go
Added an option to the kvconfig JSON, called "unsafe_batch" (bool).
Default is false, so Batch() calls are synchronously persisted by
default.  Advanced users may want to unsafe, asynchronous persistence
to tradeoff performance (mutations are queryable sooner) over safety.
{
"index_type": "scorch",
"kvconfig": { "unsafe_batch": true }
}
This change replaces the previous kvstore=="moss" workaround.
> scorch added kvconfig unsafe_batch option

- index/scorch/snapshot_index.go
- search/searcher/search_conjunction.go
- search/searcher/search_disjunction.go
- test/versus_test.go
testrunner/RQG and Aruna + Mihir have found some differences between
upsidedown vs scorch search results with boolean MustNot queries.
The underlying reason is that upside down can handle an Advance() to a
previous or backwards InternalID, while scorch cannot.  The fix was to
improve the disjunction searcher to avoid backwards Advance() calls.
Along the way, I ended up on a detour to create a unit-test system
that's somewhat like a simple version of testrunner's random query generator,
but this so-called "versus" unit test does not have a dependency on an
external elasticsearch server, and instead depends on functional
correctness of upsidedown/bolt as a baseline to compare with scorch results.
> MB-27291 - scorch compared to upsidedown/bolt using templated, generated searches

- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_tfr.go
- search/searcher/search_conjunction.go
- search/searcher/search_phrase.go
- test/versus_test.go
While looking through some recent testrunner RQG runs, saw another case where there was a search result discrepancy.  This WIP change replicates this in the scorch-vs-upsidedown unit test.
From http://qa.sc.couchbase.com/job/test_suite_executor/39085/consoleText...
> [2017-12-18 22:07:02,054] - [task:1312] INFO - FTS hits for query: {"conjuncts": [{"field": "manages.reports", "match": "Balandria Cynara"}, {"field": "manages.reports", "match_phrase": "Maura"}]} is 5 (took 5.586473ms)
> [2017-12-18 22:07:02,060] - [task:1322] INFO - ES hits for query: {"query": {"bool": {"must": [{"match": {"manages.reports": "Balandria Cynara"}}, {"match_phrase": {"manages.reports": "Maura"}}]}}} on es_index is 7 (took 2ms)
> [2017-12-18 22:07:02,060] - [task:1327] ERROR - FAIL: FTS hits: 5, while ES hits: …
> scorch conjuncts match phrase

- index/scorch/scorch.go
- index/scorch/segment/mem/build.go
- index/scorch/segment/mem/segment.go
- index/scorch/segment/mem/segment_test.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/segment.go
- index/scorch/snapshot_segment.go
+ Track memory usage at a segment level
+ Add a new scorch API: MemoryUsed()
- Aggregate the memory consumption across
segments when API is invoked.
+ TODO:
- Revisit the second iteration if it can be gotten
rid off, and the size accounted for during the first
run while building an in-mem segment.
- Accounting for pointer and slice overhead.
> Tracking memory consumption for a scorch index

- index/scorch/persister.go
- index/scorch/scorch.go
- index_test.go
Observed problem:
Persisted index state (in root bolt) would contain index snapshots which
pointed to index files that did not exist.
Debugging this uncovered two main problems:
1.  At the end of persisting a snapshot, the persister creates a new index
snapshot with the SAME epoch as the current root, only it replaces in-memory
segments with the new disk based ones.  This is problematic because reference
counting an index segment triggers "eligible for deletion".  And eligible for
deletion is keyed by epoch.  So having two separate instances going by the same
epoch is problematic.  Specifically, one of them gets to 0 before the other,
and we wrongly conclude it's eligible for deletion, when in fact the "other"
instance with same epoch is actually still in use.
To address this problem, we …
> attempt to fix core reference counting issues

- index/scorch/introducer.go
- index/scorch/snapshot_rollback.go
- index/scorch/snapshot_rollback_test.go
New APIs:
+ RollbackPoints()
- Retrieves the available list of rollback points: epoch+meta.
- The application will need to check with the meta to decide
on the rollback point.
+ Rollback()
- API requires a rollback point identified by the first API.
- Atomically & Durably rolls back the index to specified point,
provided the specified rollback point is still available.
+ Unit test: TestIndexRollback
- Writes a batch.
- Sets the rollback point.
- Writes second batch.
- Rollback to previously decided point.
- Ensure that data is as is before the second batch.
> Updated Rollback APIs

- index/scorch/event.go
- index/scorch/event_test.go
- index/scorch/scorch.go
previous approach used SetEventCallback method which allowed
you to change the callback, unfotunately that also included
times after the goroutines were started and potentially firing
the callback.
checking lock on this would be too expensive, so instead we go
for an approach that allows callbacks to be registered by name
during process init(), then upon opening up an index a string
config key 'eventCallbackName' is used to look up the
appropriate callback function.  also, since this strinc config
name is serializable, it fits into the existing bleve index
metadata without any new issues.
> fix race condition in setting up event callbacks

- index/scorch/scorch.go
- index/scorch/segment/zap/segment.go
This API is designed to only emit the dirty "unpersisted"
bytes only. This does not included the mmap'ed part in the
zap segments (disk).
> Do not account mmap'ed part of zap segments in MemoryUsed

- document/field_boolean.go
- document/field_datetime.go
- document/field_numeric.go
- document/field_text.go
- document/indexing_options.go
- document/indexing_options_test.go
- index/scorch/scorch.go
- index/scorch/scorch_test.go
- index/scorch/segment/mem/build.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/build_test.go
- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/segment_test.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
- mapping/field.go
- mapping/index.go
- mapping/mapping_test.go
-new `VisitableDocValueFields` API for persisted DV field list
-making dv configs overridable at field level
-enabling on the fly/runtime un inverting of doc values
-few UT updates
> DocValue Config, new API Changes

- README.md
The link for coverage badge in the README seems to be incorrect; the updated link comes from https://coveralls.io/github/blevesearch/bleve.
Before:
After:
> Fix coverage badge in README

- search.go
- search_test.go
Initialise the facet results map in case of an
empty partial hits with a multi node cluster
>  MB-27498 - date range facet query panics

- index/scorch/segment/mem/segment.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/segment.go
+ Account for all the overhead incurred from the data structures
within mem.Segment and zap.Segment.
+ Include overhead from certain new fields as well.
> Include overhead from data structures in segment's SizeInBytes

- index/scorch/introducer.go
Saw this while trying to debug concurrency issues with the WIP prototyping on "in-memory segments that use zap's optimized data representation".
I'm thinking this probably isn't the cause of the other concurrency issues that we're seeing, but pushing this up for correctness.
> scorch unlocks in introduceSegment's DocNumbers() error codepath

- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/scorch_test.go
- index/scorch/segment/mem/build.go
- index/scorch/segment/mem/segment.go
- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/count.go
- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/posting.go
- index/scorch/segment/zap/read.go
- index/scorch/segment/zap/segment.go
- index/scorch/segment/zap/write.go
A new struct, a zap.SegmentBase, is refactored out that has all the read-only, in-memory fields of a zap.Segment.  A zap.Segment struct now embeds a zap.SegmentBase and layers on persistence.  Both the zap Segment and zap SegmentBase implement the scorch Segment interface.
> in-memory segment representation using zap's optimized encoding

- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/merge_test.go
- index/scorch/segment/zap/posting.go
hi @mschoch -- I started adding some more merge related unit testing & checks...
This PR is still work-in-progress as I'm seeing an occasional failure with a new scenario that just calls Merge() on an just merged segment -- term dictionary counts don't seem to match.  Still digging into it but just a heads up in case if this tickles an "a-ha" moment for you...
```
--- FAIL: TestMerge (0.01s)
merge_test.go:132: merged segments don't compare: field _all, itr nexts different: &index.DictEntry{Term:"cold", Count:0x48d} &index.DictEntry{Term:"cold", Count:0x368}
FAIL
FAIL	github.com/blevesearch/bleve/index/scorch/segment/zap	0.041s
```
> scorch zap DictIterator term count fixed and more merge unit tests

- mapping/document.go
- mapping/mapping_test.go
This handles the missing case for a geopoint when the
coordinates are in a slice format.
> MB-26396: Handling docs with geopoints in slice format

- index/scorch/mergeplan/merge_plan_test.go
Helps provide a sense of how # of segments grows as # of documents
grows.  Ex: 1B docs => budget of 54 segments.
> more zap merge-planner CalcBudget tests at larger sizes

- cmd/bleve/cmd/zap/docvalue.go
- index/scorch/scorch.go
- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/contentcoder.go
- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/merge.go
Most of this PR is about "mechanical" refactoring -- e.g., refactoring out a helper function to remove code duplication -- and, as steps towards in-memory segment merging.
But, special note should be taken of the change that reduces the read-lock area in prepareSegment(), which seems correct to me, but perhaps @mshoch will see subtleties that escape me.
> scorch zap merge related refactorings / optimizations

- index/scorch/segment/zap/merge.go
This change avoids an array/slice access in a loop body.
> scorch zap mergeStoredAndRemap loop optimization

- index/scorch/segment/mem/dict.go
- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/merge_test.go
- index/scorch/segment/zap/segment.go
Some more optimizations that use the struct reuse trick.
And, some more zap.MergeToWriter() changes as a stepping stone towards in-memory zap segment merging.
> scorch optimizations via struct reuse

- index/scorch/persister.go
Making the unblock outside the loop to ensure that it covers all the cases like only merged segments and the usual mix of both mem & zap segments.
> unblock the files for clean up, esp for merged new segment files

- index/scorch/mergeplan/merge_plan.go
- index/scorch/mergeplan/merge_plan_test.go
Adjusting the merge task creation loop to accommodate
the newly merged segments so that the eventual merge
results/ number of segments stay within the calculated budget.
The inner loop fix handles the smaller left over segments that 
were left un merged earlier.
> tuning the edge for merge-task execution loop

- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/scorch.go
The slow merger was lagging behind the fast persister
to a persister notify send-loop while the persister awaits
for any new introductions from introducer totally blocking
the merger
This fix along with the deleted files eligibilty flipping
makes the file count to around 6 to 11 files  per shard
for both travel and beer samples
Need to understand and fix the rollback test failure.
> fix for merger persister handshake stalemate

- index/scorch/segment/mem/build.go
- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/merge_test.go
- index/scorch/segment/zap/read.go
- index/scorch/segment/zap/segment_test.go
This PR has an optimization for merging to use byte-copying of a segment's stored docs when there are no doc deletions for a segment and when fields are the same across all the segments being merged.
> optimize zap merge byte copy stored docs

- index/scorch/snapshot_rollback.go
- index/scorch/snapshot_rollback_test.go
In this PR (ready for review)...
When a scorch is just opened and is "empty", RollbackPoints() no
longer considers that an error situation.
Also, this commit makes the TestIndexRollback unit tests is a bit more
forgiving to races, as we were seeing failures sometimes in travis-CI
environments (TestIndexRollback was passing fine on my dev macbook).
The theory is the double-looping in the persisterLoop would sometimes
be racy, leading to 1 or 2 rollback points.
> fix for TestIndexRollback unit tests

- index/scorch/persister.go
> scorch uses segment.id to encode boltdb sub-bucket key

- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/posting.go
During zap segment merging, a new zap PostingsIterator was allocated
for every field X segment X term.
This change optimizes by reusing a single PostingsIterator instance
per persistMergedRest() invocation.
And, also unused fields are removed from the PostingsIterator.
> scorch zap segment merging reuses prealloc'ed PostingsIterator

- index/scorch/snapshot_rollback.go
Picking off the easiest subpart of issue #760 -- ignoring the unsafeBatch flag in Rollback()
> scorch rollback ignores unsafeBatch flag

- index/scorch/introducer.go
- index/scorch/merge.go
Avoid creating new segment files with empty segments
tasks during the merge operation, avoid the
incorrect appending of a newer segment to snapshot
during such merge introductions.
Issue can be consistently reproduced upon loading 
travel sample with 80K docs. Budget Planning and 
persistence is falling into an infinite loop with
files keep created all the time.
UT update pending..
> Fix for empty segment merge handling 

- index/scorch/segment/zap/merge.go
Minor optimization to access the drops array outside of the inner loop.
> scorch zap merge optimize drops lookup to outside of loop

- index/scorch/introducer.go
There's now multiple competing merge activities (file-merging and
in-memory merging during persistence), so the simple math to
precalculate capacity for the slice of segments in introduceMerge() no
longer works for all cases and might have negative capacity.
This change removes that (sometimes wrong) precalculation, and instead
depends on append() to grow the slice correctly.
> MB-28403: scorch introduceMerge doesn't prealloc segments capacity

- index/scorch/introducer.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/stats.go
This change allows the introducer to become the only goroutine to
modify the root, which in turn allows the introducer to greatly reduce
its surface area of holding the root lock.
> scorch persister goes through introducer to affect root

- index/scorch/segment/zap/intcoder.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/posting.go
This PR optimizes zap segment merging by byte-copying the encoded tf/loc entries.
Also, PostingsIterator receive some more reuse of encoders/readers.
> scorch merge optimizations via tf/loc byte copy & reader/decoder reuse

- index/scorch/merge.go
- index/scorch/scorch.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/merge_test.go
- index/scorch/stats.go
I wasn't sure whether we need the written bytes to be tracked at the CountHashWriter write method level or not.
> adding compaction_written_bytes/sec stats to scorch

- index/scorch/segment/zap/posting.go
Do not re-account for certain referenced data in the zap structures.
New estimates:
ESTIMATE     BENCHMEM       TEST
11396        12437          TermQuery
12244        12951          MatchQuery
20644        20709          DisjunctionQuery (of term queries)
> Fixing the scorch search request memory estimate

- search.go
- search_test.go
exported API: MemoryNeededForSearchResult(req *SearchRequest)
> MB-28163: Provide an API to estimate the RAM needed for SearchResult

- cmd/bleve/cmd/zap/explore.go
- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/intcoder.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/merge_test.go
- index/scorch/segment/zap/posting.go
NOTE: this is a scorch zap file format change / bump to version 4.
In this optimization, the uint64 val stored in the vellum FST (term
dictionary) now may either be a uint64 postingsOffset (same as before
this change) or a uint64 encoding of the docNum + norm (in the case
where a term appears in just a single doc).
Using aruna's testrunner test (100K docs, 30K updates), file sizes
drop from 660MB before this change to 300MB after this change.
> scorch zap optimize FST val encoding for terms with 1 hit

- index_impl.go
- index_test.go
+ SearchQueryStartCallback
+ SearchQueryEndCallback
> MB-28562: Support search query callbacks before and after execution

- index/scorch/segment/zap/posting.go
- index/scorch/segment/zap/segment.go
This commit avoids creating roaring.Bitmap's (which would have just a
single entry) when a postings list/iterator represents a single
"1-hit" encoding.
> scorch zap optimize to avoid bitmaps for 1-hit posting lists

- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/new.go
- index/scorch/segment/zap/posting.go
Using sync.Pool for the interim struct and its slices.  As part of that, there's an interim.cleanse() method that prepares it for reuse when returning it to the sync.Pool.
And, roaring has a Clear() API that can help a tiny bit with memory reuse.  That should get even better if a proposed Clear() optimization PR gets approved into roaring: https://github.com/RoaringBitmap/roaring/pull/156
> reuse roaring Bitmaps and also use sync.Pool for interim data

- index_impl.go
De-duplicate the list of fields provided by the client as part
of the search request, so as to not inadvertantly load the same
stored field more than once.
> MB-27385: De-duplicate the list of requested fields

- index/index.go
- index/scorch/snapshot_index.go
- index/upsidedown/index_reader.go
- index/upsidedown/reader.go
- search/facets_builder.go
- search/searcher/search_boolean.go
- search/searcher/search_disjunction.go
- search/searcher/search_match_all.go
- search/searcher/search_match_none.go
- search/searcher/search_phrase.go
- search/searcher/search_term.go
Since its just the pointer size of the IndexReader that is being
accounted for while estimating the RAM needed to execute a
search query, get rid of the Size() API within the IndexReader.
> Do not account IndexReader's size in the query RAM estimate

- index/scorch/segment/zap/merge.go
pprof of bleve-blast was showing file merging was in syscall/write a
lot.  The bufio.NewWriter() provides a default buffer size of 4K,
which is too small, and using bufio.NewWriterSize(1MB buffer size)
leads to syscall/write dropping out of the file merging flame graphs.
> scorch zap file merger uses 1MB buffered writer

- cmd/bleve/cmd/zap/dict.go
- cmd/bleve/cmd/zap/explore.go
correctly handle/print additional loc bitmap address
this fixes bitmap length that is output
instantiate roaring bitmap and print it out
removed some unnecessary debug logging
updated dict command to print 1-hit encoded vals
this makes dict command usable for seeing which
doc ids are in a segment and their corresponding doc number
> improve command-line tool for zap

- index/scorch/segment/zap/new.go
Use of sync.Pool to reuse the interm structure relied on resetting
the fieldsInv slice.  However, actual segments continued to use
this same fieldsInv slice after returning it to the pool. Simple
fix is to nil out fieldsInv slice in reset method and let the
newly built segment keep the one from the interim struct.
> fix MB-28719 and MB-28781 invalid/missing field in scorch

- index/scorch/persister.go
Avoiding this stacktrace (SIGSEGV) while using bleve scorch cmd-line utility
when snapshotEpoch provided is invalid:
github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).Segments(...)
/Users/abhinavdangeti/Documents/couchbaseV/godeps/src/github.com/blevesearch/bleve/index/scorch/snapshot_index.go:56
github.com/blevesearch/bleve/cmd/bleve/cmd/scorch.glob..func1(0x1f347e0, 0xc4201f1400, 0x2, 0x2, 0x0, 0x0)
/Users/abhinavdangeti/Documents/couchbaseV/godeps/src/github.com/blevesearch/bleve/cmd/bleve/cmd/scorch/ascii.go:43 +0xe4
github.com/blevesearch/bleve/cmd/bleve/vendor/github.com/spf13/cobra.(*Command).execute(0x1f347e0, 0xc4201f12e0, 0x2, 0x2, 0x1f347e0, 0xc4201f12e0)
/Users/abhinavdangeti/Documents/couchbaseV/godeps/src/github.com/blevesearch/bleve/cmd/bleve/vendor/github.com/spf13 …
> Return an error when the snapshotEpoch is invalid

- index/scorch/segment/zap/posting.go
This PR might fix issues around document updates & deletions in scorch indexes and around freq/norm/locations handling, with a change to PostingsIterator.nextDocNum() that keeps the allNChunk variable in-sync with the allN variable.
Also, this PR removes some unused fields from PostingsIterator (offset & locoffset).
> PostingsIterator.nextDocNum() maintains allNChunk correctly

- index/scorch/merge.go
- index/scorch/persister.go
When the index is closed, do not fire an AsyncError (fatal) from either
the merger or the persister that is actively working. This is quite a
probable situation, so exit the loop within the goroutine.
>  MB-28782: Error handling in merger/persister when index is closed

- cmd/bleve/cmd/zap/explore.go
- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/new.go
- index/scorch/segment/zap/posting.go
The bug was PostingsIterator.nextBytes() was incorrectly handling the case of a 1-hit encoding.
> optimization to replace locations bitmap, attempt #2

- index/scorch/segment/empty.go
- index/scorch/segment/mem/posting.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/posting.go
- index/scorch/snapshot_index_tfr.go
skips to the target segment and avoid
un necessary read of freq,loc,norm details
> TermFieldReader Advance optimisation

- index/scorch/snapshot_index.go
docInternalToNumber() no longer allocates a reader instance and a
heap uint64 to hold the result.
> optimize docInternalToNumber() to avoid allocations

- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/build_test.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/new.go
- index/scorch/segment/zap/segment.go
- index/scorch/segment/zap/segment_test.go
NOTE: This is a zap version and file format change.
This optimization treats the _id field as a special case, where the
_id field is no longer snappy compressed along with all the other
non-"_id" stored fields.  Instead, the _id field's length and bytes
are written out early and as-is, making the _id value easier to
access.
This can be beneficial to search-related methods, such as
ExternalID(), which only require _id field information.
As part of this, we're also no longer writing out unnecessary data for
the _id field that we persist for other non-"_id" fields, such as: the
numeric fieldID (i.e., uint16(0)), the type (i.e., assumed to be 't'
as a text field), the start offset, the end len, and the
arrayPositions.
Various unit tests were corrected as part of this change in order to
more …
> optimize stored field format in zap for _id field

- index/index.go
- index/scorch/optimize.go
- index/scorch/segment/zap/posting.go
- search/searcher/search_conjunction.go
- search/searcher/search_disjunction.go
- search/searcher/search_term.go
This change pushes down conjunction information to indexers for
potential TermFieldReader optimizations.  The scorch indexer can
optimize this situation by constructing a more selective roaring
"actual" bitmap for any PostingsIterator's that are part of the
conjunction.
On a bleve-query microbenchmark, dev macbook, with a scorch index of
50K en-wiki docs, using a repeated, single-threaded conjunction query
of several relatively high-frequency terms (query-string of "+text:see
+text:also +text:where +text:http"), perf was ~265 queries/sec before
this change, and ~310 queries/sec after this change.
> scorch optimize conjunctions via push-down to roaring.And()

- index/scorch/persister.go
WARNING: DATA RACE
Read at 0x00c4201945c8 by goroutine 70:
runtime.growslice()
/usr/local/Cellar/go/1.9.3/libexec/src/runtime/slice.go:82 +0x0
github.com/blevesearch/bleve/index/scorch.(*Scorch).AddEligibleForRemoval()
/Users/abhinavdangeti/Documents/go/src/github.com/blevesearch/bleve/index/scorch/scorch.go:485 +0x1bd
Previous write at 0x00c4201945c8 by goroutine 47:
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadFromBolt.func1()
/Users/abhinavdangeti/Documents/go/src/github.com/blevesearch/bleve/index/scorch/persister.go:476 +0x32b
github.com/boltdb/bolt.(*DB).View()
/Users/abhinavdangeti/Documents/go/src/github.com/boltdb/bolt/db.go:629 +0xc1
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadFromBolt()
/Users/abhinavdangeti/Documents/go/src/github.com/blevesearch/bleve/in …
> Address data race with eligibleForRemoval

- index/scorch/snapshot_segment.go
WARNING: DATA RACE
Read at 0x00c420901b50 by goroutine 240:
github.com/blevesearch/bleve/index/scorch.(*SegmentSnapshot).Size()
/Users/abhinavdangeti/Documents/go/src/github.com/blevesearch/bleve/index/scorch/snapshot_segment.go:233 +0xbb
github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).updateSize()
/Users/abhinavdangeti/Documents/go/src/github.com/blevesearch/bleve/index/scorch/snapshot_index.go:108 +0x102
github.com/blevesearch/bleve/index/scorch.(*Scorch).introduceMerge()
/Users/abhinavdangeti/Documents/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:354 +0x131e
github.com/blevesearch/bleve/index/scorch.(*Scorch).mainLoop()
/Users/abhinavdangeti/Documents/go/src/github.com/blevesearch/bleve/index/scorch/introducer.go:66 +0x82d
Previous write at 0x00c420901b50 …
> Address data race with size of cachedDocs

- index/scorch/segment/zap/dict.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_dict.go
Optimize DictionaryIterator to reuse a index.DictEntry instance rather than
allocating a new instance on every Next().  This follows an approach
used by upsidedown's dictionary iterators to avoid mem allocations.
> optimize scorch DictionaryIterator.Next() to reuse DictEntry's

- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
With term locations laid out like "a b c d d", findPhrasePaths() on a search for "a b c d" with sloppiness of 1 ought to have returned a result like...
a: 1, b: 2, c: 3, d: 4
a: 1, b: 2, c: 3, d: 5
...but instead was incorrectly returning results like this due to a subtle slice memory reuse issue...
a: 1, b: 2, c: 3, d: 5
a: 1, b: 2, c: 3, d: 5
This correctness fix, however, has a cost of generating even more interim allocations / garbage, so that'll probably need to be addressed in some future PR.
> search_phrase findPhrasePaths() fix on slice reuse

- search/levenshtein.go
- search/searcher/search_fuzzy.go
This optimization allows the levenshtein-distance-max calculation to
not necessarily have to allocate memory on every invocation.
This optimization is used in the prefix edge case by the fuzzy
searcher during the findFuzzyCandidateTerms() inner loop.
> optimization for LevenshteinDistanceMaxReuseSlice()

- index/scorch/introducer.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
I've found that knowing where a snapshot comes from helps a little with debugging.
> scorch track provenance or creator of snapshots

- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
With term locations that look like "a b b", findPhrasePaths() on a search for "a b b" with sloppiness of 1 ought to have a result like...
a: 1, b: 2, b: 3
...but instead was incorrectly returning results like the following due to not "consuming" or ignoring previously used locations during recursion...
a: 1, b: 2, b: 2    <-- incorrect
a: 1, b: 2, b: 3
One followup issue is that this correctness fix allocates more interim garbage, which probably should be addressed in some future perf improvements.
> search phrase findPhrasePaths() fix to avoid reuse of locations

- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
From feedback on a previous PR, the doc comments on findPhrasePaths() was outdated.  See...
https://github.com/blevesearch/bleve/pull/872
Additionally, the recently introduced recursive helper func allowed simplification of the params of findPhrasePaths().
> improve findPhrasePaths() doc comments and call signature

- cmd/bleve/cmd/root.go
this change allows an alternate distribution of the bleve
command-line tool to change the default behavior and always
open the index read-only
> add ability change default open read-only flag

- index/scorch/persister.go
In this optimization, scorch loadSegment() will convert an empty 'deleted' roaring bitmap to nil, so that later codepaths that test for nil-ness can avoid roaring operations like AndNot() -- which helps in the case when there's no mutations (insertions-only).
> scorch optimize loadSegment() to treat empty deleted bitmaps as nil

- index/scorch/scorch_test.go
- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/new.go
- index/scorch/segment/zap/posting.go
NOTE: This is a zap file format change.
In the case of a composite field (i.e., _all field), the component
fields might have differing configurations for IncludeTermVectors.
This can mean the freq can sometimes be > numberOfLocations, where the
previous code incorrectly assumed freq == numberOfLocations.
By encoding the # of bytes used for locations data, the loops
performing readLocation() will be able to read the correct # of
locations.
And, encoding the # of bytes used for locations data instead of the
count of locations allows for an optimization of no longer reading
unneeded locations data when skipping ahead.
This fixes issue https://github.com/blevesearch/bleve/issues/895
reported by @xeizmendi.
> fixes #895 - scorch zap file format updated w/ # bytes of locations

- index/scorch/segment/empty.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/segment_test.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
This change avoids more mem allocations / conversions.
Note, this change does have a tradeoff, though...
One the one hand, conversions are reduced while creating PostingsLists(), which is important for the low-frequency term search scenario...
But, on the other hand, populating the SegmentSnapshot.cachedDocs information via cachedDocs.prepareFields() now picks up an additional conversion in this PR, which may affect the cachedDocs initialization phase of DocumentVisitFieldTerms().
> scorch PostingsList() takes []byte, not string

- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/merge.go
Part3: Getting rid of docTermMap during the merge operation,
instead fetch all valid docNums and their corresponding
values from the segmentBases via docValueReaders.
> Optimization for reducing merger overhead from doc-values

- search/searcher/search_disjunction.go
- search/searcher/search_disjunction_heap.go
- search/searcher/search_disjunction_slice.go
introduce an alternate disjunction searcher implementation that
uses a heap to track searchers.  when you have a disjunction
of many other searchers, this should be more efficient by
performing much fewer key comparisions.
currently a cut-over from slice to heap is set at 10,
this can be adjusted by setting the package-level variable
named DisjunctionHeapTakeover
> alternate disjunction searcher impl using heap

- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/segment/zap/merge.go
The persister goroutine can decide to merge its incoming input
segments before persistence... and before this commit, that merging
would have been entirely in-memory, leading to a lot of memory usage.
After this change, the persistSnapshotMaybeMerge(), which calls
mergeSegmentBases(), performs the merging directly to file.
> persistSnapshotMaybeMerge() merges to directly to file

- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/merge.go
This reverts commit 2d5ae21650e05d26a3876b318b860546ab970a9b, reversing
changes made to cd840e0996e29962922be75c47014fad6e857078.
The issue was a panic: runtime error: slice bounds out of range
github.com/blevesearch/bleve/index/scorch/segment/zap.(*docValueReader).loadDvChunk
/Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/docvalues.go:149
github.com/blevesearch/bleve/index/scorch/segment/zap.(*docValueReader).iterateAllDocValues
/Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/docvalues.go:157
> Revert "Merge pull request #900 from abhinavdangeti/merger-overhead-doc-values"

- index/scorch/scorch.go
- index/scorch/segment/zap/build_test.go
- index/scorch/segment/zap/dict_test.go
- index/scorch/segment/zap/merge_test.go
- index/scorch/segment/zap/new.go
- index/scorch/segment/zap/segment_test.go
Account for these bytes in the memory used by the scorch index.
> MB-28847: Account for bytes of an allocated buffer while building new segment

- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/new.go
This adds more global variable "knobs" so that apps can more easily affect the estimates for new zap segment buffer preallocation.
And, it also bumps up the default extra headroom, so that there's less buffer slice grow()'ing during indexing for less garbage creation.  This has the tradeoff that in-memory segments might have extra preallocated but unused "slop" on the ends of their preallocated slices.  The reasoning is that hopefully in-memory segments will soon be persisted, replaced by right-sized mmap()'ed slices.
Also, there's a 2nd commit here that does a 'go fmt'.
> larger estimate for new zap segment buffer

- search/searcher/search_disjunction.go
- search/searcher/search_disjunction_heap.go
previously we incorreclty attempted to heap.Fix while
traversing the heap in Advance()
the fix also eliminates a full traversal of the heap
performing comparisons, by taking advantage of the fact
that heap elements are already ordered.  so in addition
to being correct, this should also be faster.
> fix disjunction heap implementation and re-enable

- search/searcher/search_disjunction.go
geo queries are supposed to execute without considering the max
disjunction clauses limit, but a recent refactoring introduced
this bug, causing them to run with the limit enforced.
> fix geo searches hitting max clause limit

- index/scorch/segment/empty.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/segment.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
The previous implementation of ExternalID(), which used the generic
VisitDocument() API to access the _id field (with extra closure
allocations), has now been replaced in this optimization by invoking a
new Segment.DocID() method.
> scorch optimize ExternalID() with Segment.DocID() API

- index/index.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/segment_test.go
- index/scorch/snapshot_index.go
- index/upsidedown/index_reader.go
- search/collector/search_test.go
- search/collector/topn.go
-attempt to improve the reuse of dvReaders
-avoid the redundant dvCache prep and checks for a given segment
there is this ugly FieldDocValueState thing introduced to save the runtime dv cache preparations and checks, looking for better ways to handle this..  (thought of putting these methods to the original DocVisitState interface, but even that doesn't looked any better..) . another flip side is dvState management kind of spread across the index_snapshot and zap layer(docvalues.go)..
> dvReader improvement

- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/segment.go
This reverts commit 0a3f3e44224c1fc8f8b0e8777b7554abb8113d3b.
> MB-29763: Revert "scorch optimize via vellum.FST.Reader() API"

- index/scorch/snapshot_segment.go
Before this change, the cachedDocs.visitDoc() method was accessing the
docs map before the readyCh was closed.  Without this check, another
goroutine that's executing the cachedFieldDocs.prepareField() method
might be concurrently populating and modifying the docs map.
See also: https://issues.couchbase.com/browse/MB-29844
> cachedDocs.visitDoc() check whether docs map is ready for use

- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/segment.go
- index/scorch/snapshot_index.go
+ This change sets up a vellum.Reader (which carries a prealloc'ed
fstState) for the term dictionaries.
+ However the Reader cannot be used concurrently, so rather than
re-using a fieldDicts initialized for the IndexSnapshot, re-use
one that is set up for TermFieldReaders which are recycled.
> Scorch optimize via vellum.FST.Reader() API

- search/searcher/search_term_prefix.go
- search/searcher/search_term_range.go
Attempt to fix the ref_count leak by closing the
field dictionary for term_prefix and term_range
searches
> MB-30342 - ref_count leak from FieldDict

- search/searcher/search_boolean.go
- search_test.go
+ Advance nested searchers within a boolean searcher only if
the cursor is trailing the ID being looked up.
+ Unit test
+ Fixes blevesearch#954
Here's an example bug scenario with nested boolean searchers ..
conjunctionSearcher [a]
=> booleanSearcher [b]
Must => conjunctionSearcher [d]
=> disjunctionSearcher [f]
=> disjunctionSearcher
=> termSearcher
=> disjunctionSearcher
=> termSearcher
=> booleanSearcher [c]
Must => conjunctionSearcher [e]
=> termSearcher
Consider there to be docs ranging from 1 to 100 in the index
and these are the expected matches, for the query:
1, 11, 16, 21,..
On the first Next() call by the collector ..
[d]
- initSearchers .. sets local cursor of [f] to 1
- moves local cursor of disjunction cursor to 11
[b]
- init: local cursor of [d] set to 1
- moves [d]’s local …
> Fix to boolean searcher's Advance()

- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/scorch_test.go
- test/versus_test.go
The fix aims to loosen the persister-merger lock
stepping and also introduces a configurable
wait in the persister work loop to favour healthier
in-memory segment merges.
> MB-29923 - high memory consumption in scorch

- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/scorch_test.go
- test/versus_test.go
Noticed operational deadlocks by stalling the persister to
allow more in-memory merges.
This reverts commit 84502bf2c73fd9a85477d7018220e0af6a69374e.
> MB-30616: Revert "MB-29923 - high memory consumption in scorch"

- index/scorch/segment/zap/posting.go
- search/searcher/base_test.go
- search/searcher/search_regexp_test.go
The "1-hit" encoding optimization for scorch was incorrectly returning
from the postings list iterator constructor too early, before setting
the includeFreqNorm & includeLocs flags.
This was caught while refactoring the existing regexp searcher unit
test from upside-down to also test scorch.
> fix 1-hit scorch optimization freq/norm & added scorch regexp test

- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/scorch_test.go
- test/versus_test.go
This change includes,
-persister nap to favour in-memory merging
-skip in-memory merging on memory pressure
-skip persister nap on memory pressure
-checks during persister-merger wait to guard against an already advanced merger
toy build passes the tests here: http://qa.sc.couchbase.com/job/test_suite_executor/85255/console
> MB-29923 - high scorch mem usage with items to persist

- index/scorch/segment/zap/enumerator.go
- index/scorch/segment/zap/merge.go
- search_test.go
> MB-30776: [Scorch] Merger's enumerator to not skip empty terms

- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
The SegmentDictionarySnapshot wrapper didn't provide a lot of extra
functionality, mainly to help construct PostingsLists with the right
deleted bitmaps.
Removing it helps optimize a little bit on memory allocations.
See also: https://issues.couchbase.com/browse/MB-21318
> remove scorch SegmentDictionarySnapshot wrapper

- index/scorch/snapshot_index.go
When scorch is finished using a TermFieldReader, if the indexSnapshot
that it belongs to is obsolete (not the current indexSnapshot), then
don't recycle the TermFieldReader so that GC can take care of it
sooner.
This can matter in a scenario of ongoing mutations (the current
indexSnapshot keeps on changing) when there are searches (like prefix
& wildcard/regexp) that might involve lots (hundreds or more) of terms
per search request, meaning lots of TermFieldReaders can be in play.
See also: https://issues.couchbase.com/browse/MB-29923
> optimize scorch to only recycle current TermFieldReaders

- index/scorch/segment/empty.go
- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/posting.go
- index/scorch/segment/zap/segment.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_tfr.go
- index/scorch/stats.go
Some searches like prefix searches can generate many term field
readers per search request, and in the face of ongoing mutations,
scorch will not recycle those term field readers.
This change adds sync pooling or recycling of the constituent parts of
a scorch TermFieldReader, which hopefully reduces some garbage and
takes some pressure off the memory allocator.
> optimize scorch with sync.Pool of zap Dict/PostingsList/Iterator

- index/scorch/segment/empty.go
- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/posting.go
- index/scorch/segment/zap/segment.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_tfr.go
- index/scorch/stats.go
Reverting:
- commit 15e5f6d3059089149b59cd47c5a5b069d3e21d59
Author: abhinavdangeti <abhinav@couchbase.com>
Date:   Thu Sep 6 11:28:37 2018 -0700
Invvoke fst/reader's Close() to reuse via sync pool on recycle
- commit 38f239cf70326c6983e7e09a22a4a3769969f6a6
Author: Steve Yen <steve.yen@gmail.com>
Date:   Thu Aug 23 08:59:55 2018 -0700
optimize scorch with sync.Pool of zap Dict/PostingsList/Iterator
Some searches like prefix searches can generate many term field
readers per search request, and in the face of ongoing mutations,
scorch will not recycle those term field readers.
This change adds sync pooling or recycling of the constituent parts of
a scorch TermFieldReader, which hopefully reduces some garbage and
takes some pressure off the memory allocator.
> Overall performance regression in throughput/latency observed with recent sync pool optimizations 

- analysis/token/camelcase/parser.go
- index/scorch/introducer.go
- search/collector/heap.go
- search/collector/list.go
- search/collector/slice.go
- search/query/query.go
Small cleanups found by [go-critic](https://github.com/go-critic/go-critic)
Rules: `builtinShadow`, `typeSwitchVar`, `singleCaseSwitch`.
go-critic log:
```
check-package: github.com/blevesearch/bleve/index/scorch/introducer.go:517:2: singleCaseSwitch: should rewrite switch statement to if statement
check-package: github.com/blevesearch/bleve/search/collector/heap.go:28:19: builtinShadow: shadowing of predeclared identifier: cap
check-package: github.com/blevesearch/bleve/search/collector/list.go:28:19: builtinShadow: shadowing of predeclared identifier: cap
check-package: github.com/blevesearch/bleve/search/collector/slice.go:24:20: builtinShadow: shadowing of predeclared identifier: cap
check-package: github.com/blevesearch/bleve/analysis/token/camelcase/parser.go:49:16: builtinShadow: …
```
> minor code cleanups

- index/scorch/persister.go
Always perform in-memory segment merging before
persisting segments, esp even when the memory pressure
is applied.
> MB-31405 - higher disk usage in DGM

- search/searcher/search_boolean.go
- search_test.go
+ Relates to: https://github.com/blevesearch/bleve/pull/955
+ Advance the boolean searcher's cursor only if necessary,
the boolean searcher's cursor is tracked by it's currentID.
+ With this in place, we shouldn't be further checking
the tracked cursor positions of the nested searchers.
+ Unit test
+ Fixes: https://github.com/blevesearch/bleve/issues/1021
> Fix Boolean searcher's Advance

- index/scorch/persister.go
Re-initialising the default persister nap configs
to favour direct persistence without any naps.
> fix persister nap regression with safe batches

- geo/geohash.go
- geo/parse.go
- mapping/document.go
- mapping/mapping_test.go
Following specification used in elastic search:
https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html
Also see:
https://issues.couchbase.com/browse/MB-30542
> Add support for GeoSpatial points in string format

- search/searcher/search_fuzzy.go
- search/searcher/search_fuzzy_test.go
Querying for negative fuzziness or edit distance is
an invalid option and adding error messages for that.
This would help further wrinkles down the line due to
wrapping of -ve ED to a higher value during the uint
typecasting.
> Adding error messages for negative fuzziness

- index/scorch/event_test.go
- index/scorch/field_dict_test.go
- index/scorch/reader_test.go
- index/scorch/scorch_test.go
- index/scorch/snapshot_rollback_test.go
Here are few changes in scorch tests:
1. Tests fail in Windows with error `snapshot_rollback_test.go:37: remove C:\Users\rvncerr\AppData\Local\Temp/bleve-scorch-test-TestIndexRollback\000000000001.zap: The process cannot access the file because it is being used by another process.` (unlike Unix, Windows can not delete file which is being used by another process). Proposed workaround - do not throw `t.Fatal(err)` if we cannot delete test files at the end of the test, but throw if we cannot delete them at the begin of new test run.
2. Execute tests in different folders. It helps in parallel execution of tests and necessary for (1) - if running test is unable to clean up the data, we can continue with the next test.
3. Using `os.TempDir()` instead of `'/tmp'`. Necessary for OS, different …
> Scorch test refactoring

- index/scorch/segment/zap/segment.go
- vendor/manifest
Small performance improvement in SegmentBase.DocNumbers function.
Check, if current segment maximum docId smaller then smallest requested id.
If so, just skip this segment. This code uses recent vellum update (`GetMaxKey()`).
> DocNumbers - skip segments, that don't include requested ids

- search_test.go
If a test fails, to avoid a subsequent test from failing because
of the earlier test not closing the index, defer the closing part.
> Defer closing the index in tests to avoid cascade failures

- analysis/char/asciifolding/asciifolding.go
- analysis/char/asciifolding/asciifolding_test.go
ASCII Folding Filter reimplemented in Go based on Lucene's AsciiFoldingFilter.
**Notice:** It does fold German Umlauts `ä -> a` and **not** `ä -> ae` like mentioned in the referenced issue. Reason for that is to keep the filter generic for all languages and work the same way as the Lucene implementation.
By adding a few regexp filters to the chain (before this Ascii folding filter), above umlaut filtering can easily be achieved.
fixes #957
> add ASCII Folding Filter

- search/searcher/search_boolean.go
- search_test.go
+ Noted incorrect advancing of the boolean's currMustNot position:
[0xc4200b82c0] BOOL Advance to ID: 13965, currID: 13943, currMust: 13943, currMustNot: 13966
[0xc4200b82c0] BOOL Advanced, now currID: 13965, currMust: 13965, currMustNot: 13967
+ Fix the incorrect comparison for Boolean searcher's MustNot cached entry
- If the current position is already where it should be do not advance
- If the position is only less than (and not just inequal) to the requested ID, advance
+ Unit tests (thanks @mschoch)
+ Addresses https://github.com/blevesearch/bleve/issues/1059
> Fix Boolean Searcher's MustNotSearcher from advancing incorrectly

- search/query/query_string_lex.go
- search/query/query_string_parser_test.go
Query string query lexer reads IP addresses as tNUMBER instead of tSTRING.
The error is in the **inNumOrStrState** (_search/query/query_string_lex.go_) function where the **seenDot** field of the lexer is never set to true:
```go
// see where to go
if !l.seenDot && next == '.' {
// stay in this state
l.buf += string(next)
return inNumOrStrState, true
}
```
This PR fixes this issue.
> Fix query string number in query string query

- index/scorch/scorch.go
- test/versus_score_test.go
The composite field norm/scoring is broken with
scorch, as it incorrectly considers the "_id"
field during the composite field analysis.
> Fix #1079 - Incorrect scorch score

- index/scorch/segment/zap/posting.go
A postings list that has no obsoleted docs will have a postings
iterator with an actual roaring-bitmap that's logically the same as
the all roaring-bitmap (e.g., actual = all - obsoletions).
This optimization handles this edge case by using the same exact
roaring-bitmap instance for both the actual and all needs.  This means
that Next() calls will be only needed on a single roaring instance
rather than the general case of Next()'ing through two separate
roaring-bitmaps.  Additionally, one fewer roaring bitmap leads to less
memory used.
A helper method, PostingsIterator.currChunkNext(), is refactored out
as part of this change so that maintaining the freq/norm/location
readers correctly is more straightforward.
On a scorch index of 200,000 en-wiki docs, high-freq term searches
went from …
> optimize scorch postings list that has no obsoleted docs

- index/scorch/segment/zap/segment.go
Skip the segment if the current segment's maximum docId is
smaller than the smallest requested id, while fetching
the DocNumbers.
> [Scorch] Skipping segments that don't include requested ids

- search/collector.go
- search/collector/topn.go
- search/search.go
Adding optional builder/maker callbacks for the
document match handlers from applications.
These builder method gives back a threadsafe
document match handler callback for bleve which
it will invoke for every document hit during
a search.
The application should make its own copy of
the hit/documentMatch in the callback if it
wish to hold on to data.
> MB-31974 - Streaming search results

- index/scorch/scorch.go
- index/upsidedown/upsidedown.go
- index_test.go
When the batches passed to bleve are empty, this was a special
case that inadvertently avoided proper synchronization, and
led to the race detector to correctly point out that resetting
the batch was unsafe.  By simply avoiding an unnecessary step
when the batch is empty, we can avoid the problem.
> fix data race when indexing empty batches and using reset

- search/query/disjunction.go
- search/query/query.go
- search/searcher/search_disjunction_heap.go
- search/searcher/search_disjunction_slice.go
- search_test.go
+ This optimization can be applied only when ..
- The parent disjunction searcher has only 1 child searcher.
- The 1 child searcher's min is the same as the parent's min.
+ This means that the "min" setting doesn't need to be propagated.
> MB-32855: Applying the disjunction 1-clause optimization

- index/index.go
- index/scorch/optimize.go
- index/scorch/segment/empty.go
- index/scorch/segment/zap/posting.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_tfr.go
- index_impl.go
- search.go
- search/search.go
- search/searcher/base_test.go
- search/searcher/search_conjunction.go
- search/searcher/search_conjunction_test.go
- search/searcher/search_disjunction.go
- search/searcher/search_phrase.go
- search/searcher/search_term.go
This PR adds...
1) an API to allow applications to optionally specify in a search request that the additional information of scoring and locations are not needed.  
2) these so-called "unadorned" search requests might also be comprised of disjunctions of term searches -- where these disjunctions might be optimized by the scorch indexing layer by OR()'ing the constituent bitmaps.
Regarding perf microbenchmarks (bleve-query) on a 200K en-wiki docs scorch index...
```
for a high number of high-frequency terms...
- wildcard search on "th*" (~31K hits)...
before the change, with normal scoring         -  ~4.7 q/sec
w/ NoScore:true                                -  ~5.1 q/sec
w/ NoScore:true & unadorned disj. optimization - ~11.6 q/sec
for a low number of high-frequency terms...
- query-string …
```
> API change - optimize scorch non-scoring, no-term-vector disjunctions & conjunctions

- search/query/conjunction.go
Reverting the single-clause conjunction optimization for now,
as we're noticing unexpected results while executing a boolean
query in certain scenarios.
> MB-32855: Revert conjunction-single clause optimization

- index/store/boltdb/store.go
Without this option, sometimes committing a write Tx will block
until all ongoing read Txs finish.  If your application supports
running long searches, this may result in unacceptable delays
to indexing the data.
By setting this value to a very large value (say 1TB), you can
ensure that bolt will never need to remap to complete the
write Tx.  On 64-bit systems this may be an acceptable trade-off.
See also:
https://github.com/boltdb/bolt/issues/240
https://github.com/boltdb/bolt/issues/489
> add support for configuring the boltdb initialMmapSize option

- index/scorch/scorch.go
- index/upsidedown/upsidedown.go
- index_test.go
this is another variation of the race found/fixed in #1092
in that case the batch was empty, which meant we would skip
the code that properly synchronized access.  our fix only
handled this exact case (no data operations), however
there is another variation, if the batch contains only deletes
(which are data ops) we still spawned the goroutine, although
since there were no real updates, the again the synchronization
code would be skipped, and thus the data race could happen.
the fix is to check the number of updates (computed earlier on
the caller's goroutine, so it's safe) instead of the length
of the IndexOps (which includes updates and deletes)
the key is that we should only spawn the goroutine that will
range over the batch, in cases where we will synchronize on
waiting for the …
> fix data race with batch reset

- index/scorch/segment/zap/posting.go
previously the calculation subtracted the total number of
deleted documents, without regard for how the deleted documents
set might overlap with the postings list, this was incorrect.
fixes #1140
> fix postings list count implementation

- mapping/document.go
- mapping/mapping_test.go
If documents contained a field of type *time.Time AND they also
had an explicit mapping for the field of a type OTHER THAN text,
the field would not be mapped.
The issue was introduced when we added special support for
handling encoding.TextMarshaler because *time.Time satisfies
this interface.
This change fixes this issue, but there are some more complicated
cases exposed by this, specifically related to mapping the same
field multiple times, and handling cases where you try to mix
multiple types.
Instead, our solution is to further limit the way we support
using ecoding.TextMarshaler.  The new limitation is that we ONLY
use the output of MarshalText() if you have an explicit mapping
AND ALL the index fields are of type text.  All other cases
will ignore TextMarshaler and follow regular …
> fix issue mapping documents containing *time.Time

- search/collector/topn.go
Initialising the IndexReader field of the
SearchContext so that the DocumentMatchHandler
implementation will have enough details for
invoking the LoadAndHighlightFields API.
> IndexReader initialisation in SearchContext

- index/scorch/segment/zap/dict.go
- index/scorch/segment/zap/dict_test.go
This pull request fixed the [issue#1156](https://github.com/blevesearch/bleve/issues/1156).
> Fix panic on range query with unlimited upper in scorch (issue#1156).

- .travis.yml
- test/tests/basic/searches.json
- test/tests/fosdem/searches.json
- test/tests/sort/searches.json
some minor changes have been made to a few of the queries to
ensure that the search results have a deterministic order
one test was removed as it was specifically checking the order
when no sort was specified, which is defined in a way that
does not lend itself to easy testing
we did not change all tests without sort order, as many of them
are correctly ordered by score already
> run integration tests with scorch

- test/tests/basic/searches.json
- test/tests/employee/searches.json
- test/tests/fosdem/searches.json
- test/tests/phrase/searches.json
any test which is not explicitly setting a sort order
should instead specify:
"sort": ["-_score", "_id"]
this starts with the natural order of score descending,
but also imposes an additional tiebreaking rule to sort
by the documents identifier.  this comes with some
additional cost, but makes results more stable for
testing purposes.
> change sort strategy for integration tests

- search/search.go
- search/search_test.go
- search_test.go
- test/integration_test.go
This fix filters out duplicate locations using a destructive in-place
sort on the locations slice, and then a pass to remove duplicates.
This hopefully does not have undue impact on normal case performance,
as the deduplication effort happens only in the "last step" of
finalizeResults() and its DocumentMatch.Complete() invocations.
e.g., the deduplication will be only invoked on the final result hits
(e.g., "size": 10) instead of on all the (potentially many) candidate
document-matches which were examined beforehand.
Also, we only perform the deduplication effort only if we detect that
the locations that are being examined look like they're not in
increasing order.
> fixes #1168 - filter duplicate locations in search results

- search/query/date_range.go
- search/query/date_range_test.go
+ All datetimes after 2262-04-11T11:59:59Z will cause UnixNano()
which generates an Int64 to overflow.
+ Error out early for these values rather than the query to fail
quietly.
> MB-33462: Validating the range for a date range query

- analysis/char/asciifolding/asciifolding_test.go
@mihirkamdarcouchbase provided some asciifolding strings in https://issues.couchbase.com/browse/MB-33486, so I figured I'd bring them over into a unit test case as a sanity check
> asciifolding test apples from MB-33486

- index/scorch/segment/int.go
- index/scorch/segment/int_test.go
- index/scorch/segment/zap/posting.go
This commit introduces a specialized MemUvarintReader which is focused
on the "hot inner loop" of scorch/zap's reading of uvarint's -- such
as the postingsList reading freqNormHasLocs and location information.
The various changes include...
- the separate bytes.Reader vs binary.ReadUvarint() codepaths are
unified, and ReadByte() is now inlined.
- error return codes are removed, since the memory slices are
"perfectly sized" in scorch/zap, which meant there's never an error.
- SkipUvarint() allows entries to be skipped more efficiently (by
postingsList.currChunkNext()).
- prevRune maintenance is removed.
- postingsList.readLocation() is always provided a non-nil output
location.
In microbenchmarks...
```
$ go test -benchmem -bench=. ./index/scorch/segment/
BenchmarkUvarint-8 …
```
> fixes #1166 - perf optimizations for ReadUvarint()

- numeric/prefix_coded.go
- search/searcher/search_geoboundingbox.go
- search/searcher/search_geoboundingbox_test.go
This change improves ComputeGeoRange() performance by avoiding trips
to the allocator by using pre-allocated []byte slices and by avoiding
creation of interim [][]byte slices by append()'ing directly to
returned output slices.
Before the change...
```
BenchmarkComputeGeoRangePt01-8 100000     18516 ns/op      2005 B/op     63 allocs/op
BenchmarkComputeGeoRangePt1-8   10000    108882 ns/op     96267 B/op    736 allocs/op
BenchmarkComputeGeoRange10-8       50  35883331 ns/op  35812513 B/op 184543 allocs/op
BenchmarkComputeGeoRange100-8      10 192568538 ns/op 187524856 B/op 926510 allocs/op
```
After the change...
```
BenchmarkComputeGeoRangePt01-8 100000     12447 ns/op       280 B/op      7 allocs/op
BenchmarkComputeGeoRangePt1-8   30000     47053 ns/op     16416 B/op     28 allocs/op …
```
> MB-33455: improve ComputeGeoRange() performance

- index/store/moss/lower_test.go
- search/query/disjunction.go
- search_test.go
+ Reverting the single-clause disjunction optimization as well,
as we're noticing unexpected results while executing a boolean
query in certain scenarios.
+ Note that I've already reverted the single-clause conjunction
optimization with: https://github.com/blevesearch/bleve/pull/1133
+ Included unit tests that capture failing test cases with the
above mentioned optimizations.
+ With this change, I've completely reverted:
- https://github.com/blevesearch/bleve/pull/1073
- https://github.com/blevesearch/bleve/pull/1116
- https://github.com/blevesearch/bleve/pull/1128
+ Apologies for the grand mess :)
Also, some related discussion on why these optimizations don't
work: https://github.com/blevesearch/bleve/pull/1136
> MB-32855: Revert disjunction-single clause optimization

- search/query/date_range.go
- search/query/date_range_test.go
+ MinAllowedTime: 1677-12-01T00:00:00Z
+ MaxAllowedTime: 2262-04-11T11:59:59Z
Any NonZero time.Time values that fall outside this range
will cause UnixNano() to overflow (int64 cannot accommodate).
> MB-33600: Allow date ranges before epoch time

- search/searcher/search_geoboundingbox.go
- search/searcher/search_geoboundingbox_test.go
- search/searcher/search_geopointdistance_test.go
Unlike normal disjunctions, a geoboundingbox searcher does not limit
its multi-term-searcher against the DisjunctionMaxClauseCount, so my
recent maxTerms optimization for ComputeGeoRange() in commit 3d774b9
was just wrong.
This commit is a manual revert instead of an automated "git revert",
in that the previous commit 3d774b9 also changed a few things that
we'd still like to keep (e.g., error return value instead of
panic'ing) and there are now more unit tests in this commit from
diagnosing this issue, which compare the outputs of the optimized
ComputeGeoRange() with the previous, non-optimized version.
See also: https://issues.couchbase.com/browse/MB-33614
> remove maxTerms optimization for ComputeGeoRange()

- index/scorch/segment/zap/build.go
- index/scorch/segment/zap/segment.go
This change aims to cache the vellum fst instances
per field at the SegmentBase level to help it’s reuse
across queries.
Its been noted from the cpu profiles that the
vellum.Load/new could be optimised.
Improvements observed for a 1M data set with 10K w/sec,
Wildcard queries -  147 – 184 [25%]
Fuzzy1 – 705 – 790 [12%]
Fuzzy2 - 71 - 79 [11%]
Prefix queries - 253 -> 270 [7%]
> reuse/cache the vellum fst instances at segment level 

- index/scorch/segment/zap/docvalues.go
- index/scorch/segment/zap/merge_test.go
- index/scorch/segment/zap/segment.go
- first, we now check the error returned by
loadFieldDocValueReader
- second, in order for that to no break things we changed the
behavior of loadFieldDocValueReader to not return an error
in the case where the field isn't uninverted.  this isn't really
an error, we now just return nil, nil
- third, we return a new error when the condition
fieldDvLocEnd-fieldDvLocStart > 16
isn't satisfied.  this is a good indication that we're pointing
at the wrong part of the file, or it has been corrupted.
- fourth, the unit test helper method
testMergeWithEmptySegments was updated to check for errors
returned by AnalysisResultsToSegmentBase
- finally, the loadDvReaders metdod was updated to return early
when the number of docs is 0.  this was necessary because there
is a way to build a segment which …
> fix some minor issues with zap doc values

- index/scorch/merge.go
- index/scorch/segment/zap/merge.go
- index/scorch/segment/zap/new.go
ValidateDocFields can be used to check each field
seen by zap
ValidateMerge can be used to check the results of
a merge operation
These hooks are intended to allow for application specific
checks inside the main bleve branch, so as to allow maximum
flexibility with minimal disruption.  These hooks are not
intended to be permanent, but that decision can be made
at a later time.
> add optional validation hooks to scorch/zap

- index/scorch/segment/zap/docvalues.go
previously these methods were defined on Segment
but they only use fields in SegmentBase,
and having them defined on SegmentBase means you
can use them on in-memory segments
> move the impl of DocumentFieldTermVisitable

- geo/geohash_test.go
Its been noted a precision/accuracy issue
with respect to the existing geoHash decoder
since it performs rounding of lat/lon values.
This matters when the given hash is having a
smaller precision like 5, eg: "d3hn3".
This test is just a confirmation for the
results with some sample values.
> adding UTs for GeoHash

- search/searcher/search_geoboundingbox.go
- search/searcher/search_geoboundingbox_test.go
- search/searcher/search_geopointdistance_test.go
Geo queries are reported to have high memory consumption
and higher latencies.
One plausible root cause for this could be,
-Very high number of candidate terms computed during
the bounded box ranges. (unlike other queries, looks like
these terms are just mathematically created without actual
existence in the bleve index)
-Too many candidate terms keeps more TermFieldReaders and
term searcher objects live and manage over the disjunction heap.
This fix tries to filter out the onBoundary/notOnBoundary
terms early in the search path so that it creates
lesser garbage from TFRs, term byte searchers and lighter
disjunction heap management.
Fix have shown good improvement with numbers in local/mac
environment against the functional tests with
1000 documents and num_queries=100
Average FTS latency …
> MB-33364 - perf wrinkles with geo queries

- search.go
There's a setter method for `SearchAfter` (called `SetSearchAfter`) but no method to do the same for `SearchBefore`.
> add missing setter method for SetSearchBefore

- index/scorch/segment/regexp.go
- index/scorch/segment/regexp_test.go
the previous version incorrectly returned a literal
prefix when case-insensitive matching was enabled
> fix scorch regex literal prefix for case insensitive

- search/searcher/search_numeric_range.go
- search/searcher/search_numeric_range_test.go
Numeric range query to use the new Exists iterator
from Vellum for filtering the candidate terms for
scorch index types.
Empirical evidence shows that this brought about
44% throughput improvements for qps.
> Numeric range query adopts Exists Iterator

- index/index.go
- index/scorch/segment/empty.go
- index/scorch/segment/segment.go
- index/scorch/segment/zap/dict.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_dict.go
- search/searcher/search_geoboundingbox.go
- search/searcher/search_numeric_range.go
TermDictionary's Contains api implementation to use the
FST's Contains method directly, and there is
no need for a ContainsIterator for TD now.
> Adding Contains method to segment TermDictionary

- index/scorch/scorch.go
- index/scorch/snapshot_segment.go
opening on behalf of @darren
makes Scorch and cachedDocs aligned so that scorch run properly on arm
see the bottom of page on https://golang.org/pkg/sync/atomic/#pkg-note-BUG
fixes #1231
> scorch: fix crashes on ARM due to mis-aligned atomic access

- index/scorch/segment/zap/posting.go
- vendor/manifest
Roaring bitmap library now has IntPeekable iterator implementation, that allows skipping values instead of using a naive sequential iteration with `HasNext/Next()`
> Replace for-loop that calls HasNext/Next() with roaring.IntPeekable

- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/stats.go
Fix for #1269.
Its observed in an under resourced situation that
the merger was treading ahead of the persister and the
scorch files were piling up. It was reaching upto 70K
with an update heavy workload.
The intention of this fix is to unflip any
ineligible files which are genuinely eligible for
clean up.
Also, adding stats to track this for future.
> Tightening the scorch stale file clean ups

- document/field_text.go
this change allows applications to see the analyzer set for
a text field, useful if applications want to modify the document
after mapping, but prior to indexing.
> add method to access analyzer of a text field

- geo/geo.go
- search/query/geo_boundingpolygon.go
- search/query/query.go
- search/searcher/search_geopointdistance.go
- search/searcher/search_geopolygon.go
- search/searcher/search_geopolygon_test.go
- test/tests/geo/data/amoeba_brewery.json
- test/tests/geo/data/communiti_brewery.json
- test/tests/geo/data/social_brewery.json
- test/tests/geo/searches.json
Attempt to introduce GeoBoundingPolygonQuery
to enable the bounded polygon queries.
Polygon searcher internally finds the bounded
rectangle for the given polygon points and
apply the filter which performs the point-in-polygon
checks.
In this iteration, as simplicity is preferred over
precision(on boundary points), the point-in-polygon check
is based on ray-casting algorithm.
geo points can be in any of the following forms as with other geo queries
{"query": {"field": "geo", "polygon_points":[[-80.881,35.282],[-80.858,35.281],[-80.864,35.270]]}}
"query": {"field": "geo", "polygon_points":[{"lon" :-80.881,"lat":35.282},{"lon":-80.858,"lat":35.281},{"lon":-80.864,"lat":35.270}]}}
{"query": {"field": "geo", "polygon_points":["35.282,-80.881","35.281, -80.858","35.270,-80.864"]}}
{"query": …
> Support for bounded polygon query

- index/scorch/persister.go
- index/scorch/scorch.go
The new "num_bytes_used_disk_by_root" stats shows
the disk size used by the latest root index.
The idea is that this should help in suggesting
a sizing recommendation for RAM quota driven by
an index size resident ratio.
> adding a disk size stats for the index

- search/searcher/search_geoboundingbox.go
- search/searcher/search_geopointdistance.go
- search/searcher/search_geopolygon.go
- search_test.go
If a field (for example _all) were to index multiple numeric terms
(of type numeric and geopoint morton hash), verify all numeric
matches rather than just the last encountered entry to determine
if the entry morton unhashes into a geo point match.
Fixes: https://github.com/blevesearch/bleve/issues/1301
> [GEO] Search all numeric type terms to match geo points

- index/scorch/mergeplan/merge_plan_test.go
- search/searcher/search_geopointdistance.go
Using an aggressive merge policy, scorch is able to create a single 
segment index.
> Unit tests for a single segment merge policy

- .travis.yml
>> etcd-io/bbolt complains with go version 1.11.x
> Update .travis.yml to run for go versions 1.12.x and 1.13.x (latest)

- search/searcher/search_geopolygon.go
- search/searcher/search_geopolygon_test.go
Polygon query was returning less results after adding
initial point as last point. This fix aims to address
that by extending the ray casting checks.
> MB-37392 - incorrect results with closed polygon coordinates

- index/scorch/persister.go
If the persister is busy doing the catch up with
the ongoing mutations then there is a chance for
the older snapshot clean up call/removeOldData to
wait for a longer time to get invoked. This can
result in unbounded growth in the number of scorch
files.
This change attempt to invoke removeOldData whenever
the number of files grow beyond the thresholds.
> [BP] MB-37579: [MB-35333 - Potential removeOldData call starve issue]

- index/upsidedown/upsidedown.go
This is the stack trace we got in our tests
```
fatal error: concurrent map read and map write
goroutine 7 [running]:
runtime.throw(0x17b1b17, 0x21)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00c97f8b8 sp=0xc00c97f888 pc=0x431422
runtime.mapaccess2_faststr(0x15f4040, 0xc011202f90, 0x257c531, 0x1, 0xc00c97fa70, 0xcb5919)
/usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc00c97f928 sp=0xc00c97f8b8 pc=0x4150ff
github.com/blevesearch/bleve/analysis.TokenFrequencies.MergeAll(0xc011202f90, 0x14488dd, 0x2, 0xc01121cc00)
/home/circleci/.go_workspace/pkg/mod/github.com/blevesearch/bleve@v0.0.0-20190812174355-c997533a776f/    +0x100 fp=0xc00c97fa38 sp=0xc00c97f928 pc=0x9d6770
github.com/blevesearch/bleve/document.(*CompositeField).Compose(0xc00e499d80, 0x14488dd, 0x2, 0x1, …
```
> Fix concurrent read write on analysis

- search/collector/topn.go
- test/tests/sort/data/d.json
- test/tests/sort/data/e.json
- test/tests/sort/data/f.json
- test/tests/sort/searches.json
This change attempts to enable users provide the last
fetched document's score or ID values as keys in the
search after/before fields to make the deep pagination
works for the default _score or _id based sort orders.
> Enabling score/id based search_after/before paginations

- index/scorch/scorch.go
During the scorch's Close call, the root snapshot's
DecRef return errs are ignored. Fixing that to bubble up
the errors so that the higher levels may listen and
act on it.
> Initialise the root snapshot's DecRef errs with Close()

- index/scorch/scorch.go
- index/scorch/scorch_test.go
Fix for issue #1352 
Resetting the closeCh in Open api so that scorch
index's main routine trio remains in their active
work loops.
> Resetting closeCh with Open api

- index/scorch/introducer.go
- index/scorch/merge.go
- index/scorch/stats.go
Improving ownership handling during merge introductions
As a part of notifying the merger during the merge
introductions, the introducer bumps the newer
snapshot's reference count. But in situations
where the index is getting closed, there is a
chance that the merge requested merger(file/in memory)
routines would have already exited.
This would cause the newly introduced, ref count
bumped snapshot to leak as there is none to decrement
the bumped up reference count.
The fix is about tighening the merge introduction
notifications handling at the merger side.
As the introducer non-preemptively handles the
intro notify channel, its safe for the merger
to blockingly awaits for each of those merge introduction
notifications and decrements the reference counts
where applicable.
Unlike earlier, …
> Fix for snapshot leak by merger routine on scorch index Close

- index/scorch/introducer.go
- index/scorch/merge.go
- index/scorch/stats.go
As a part of notifying the merger during the merge
introductions, the introducer bumps the newer
snapshot's reference count. But in situations
where the index is getting closed, there is a
chance that the merge requested merger(file/in memory)
routines would have already exited.
This would cause the newly introduced, ref count
bumped snapshot to leak as there is none to decrement
the bumped up reference count.
The fix is about tighening the merge introduction
notifications handling at the merger side.
As the introducer non-preemptively handles the
intro notify channel, its safe for the merger
to blockingly awaits for each of those merge introduction
notifications and decrements the reference counts
where applicable.
Unlike earlier, merger is processing each of the merge
tasks and awaits …
> [Backport] Improving ownership handling during merge introductions

- index/scorch/introducer.go
- index/scorch/scorch.go
- index/scorch/snapshot_rollback.go
- index/scorch/snapshot_rollback_test.go
This change comprises of enabling the rollback related scorch APIs
to work only with closed/offline indexes.
Both the API signatures have modified to accept an index path
pointing to the scorch index location to accommodate this change.
The two API approach(RollbackPoints api for fetching the rollback points
and the Rollback api for performing the actual rollback) is retained in
favour of modularity and simplicity of usage.
The Rollback api would make the meta/bolt store with the given
rollback point as the most recent epoch to be loaded.
During the process of restoring the index state to the relevant
rollback point, the new Rollback implementation cleans up the
irrelevant epoch data from the bolt store. This is done to favour
a lean version of persisted epochs in root bolt anytime to …
> Offline RollbackPoints/Rollback apis for scorch index

- analysis/char/regexp/regexp.go
- analysis/char/regexp/regexp_test.go
- search/highlight/fragmenter/simple/simple.go
- search_test.go
+ regexp filter's should replace a match with a
single entry of replace and not by a number of times.
+ For example ..
- Consider the following regex:
([a-z])\s+(\d)
- For the string "temp 1", the above regex matches:
"p 1"
- Let the replacement be "$1-$2", so the expectation
is that "p 1" gets replaced by "p-1".
- The code before the fix replaces "p 1" with:
"$1-$2$1-$2$1-$2"
> Extend Regexp support to accommodate expanding $ variables

- index_alias_impl_test.go
observed this test failing frequently on mac
environment through github actions
simple change seems to still test the same behavior
instead of arranging for one request to sleep longer
than the context timeout, instead arrange for it
to never return.  that way no matter when the context
timeout eventually happens, we correctly observe
partial results.
> improve reliability of test on mac

- index_test.go
Before:
```
$ go test -v -run=TestSearchQueryCallback
=== RUN   TestSearchQueryCallback
--- PASS: TestSearchQueryCallback (20.99s)
PASS
ok  	github.com/blevesearch/bleve	20.997s
```
After:
```
$ ✗ go test -v -run=TestSearchQueryCallback
=== RUN   TestSearchQueryCallback
--- PASS: TestSearchQueryCallback (1.50s)
PASS
ok  	github.com/blevesearch/bleve	1.509s
```
> improve unit test execution time

- go.mod
- mapping/document.go
- mapping/mapping_test.go
- search_test.go
Check if the top level document mapping's (default mapping or a
type mapping) default analyzer is available while determining the
analyzer to use for a child field in the event that neither the child
field has an analyzer set nor any of the intermediate child mappings.
Fixes: https://github.com/blevesearch/bleve/issues/1390
> MB-38957: Document mapping's analyzer to be inherited correctly

- search/sort.go
In the comments from strings.Compare:
```
// Compare is included only for symmetry with package bytes.
// It is usually clearer and always faster to use the built-in
// string comparison operators ==, <, >, and so on.
```
And another comment within the implementation:
```
// NOTE(rsc): This function does NOT call the runtime cmpstring function,
// because we do not want to provide any performance justification for
// using strings.Compare. Basically no one should use strings.Compare.
```
> use inline comparison operators instead of strings.Compare

- index/scorch/builder.go
logic was reversed, preventing correct configuration
from actually switching the segment plugin used
fixes #1406
> allow segment type/version override to work

- index/scorch/scorch.go
previous version did not correctly handle integer
values stored in a float64 due to JSON parsing
> improve scorch config parsing of forced zap version

- index_alias_impl.go
- index_impl.go
- search.go
This allows SearchRequests to specify the sort implementation (defaults to sort.Sort) to use
when sorting hits.
> Add SortImpl to SearchRequest

- index/scorch/event.go
- index/scorch/introducer.go
- index/scorch/merge.go
- index/scorch/merge_test.go
- index/scorch/stats.go
During merge segment introduction, if the segment contents
becomes totally obsolete, then the introducer skips
its introduction to the root. But it wasn't handling the clean
up ceremonies for the segment like Closing and cleaning
the entries from the ineligibleToRemove file list.
> MB-40007 -Obsolete segment file leaks during merge introductions

- index/scorch/event.go
- index/scorch/introducer.go
- index/scorch/merge.go
- index/scorch/merge_test.go
- index/scorch/stats.go
During merge segment introduction, if the segment contents
becomes totally obsolete, then the introducer skips
its introduction to the root. But it wasn't handling the clean
up ceremonies for the segment like Closing and cleaning
the entries from the ineligibleToRemove file list.
> [BP] MB-40007 -Obsolete segment file leaks during merge introductions

- mapping/index.go
Documentation for AddCustomAnalyzer is using invalid, non-existing import paths
> Fix for import paths in function documentation

- index/scorch/optimize.go
- index/scorch/segment/unadorned.go
- search/searcher/search_disjunction.go
- search/searcher/search_multi_term.go
- search/searcher/search_term_range_test.go
Observation: When a search does not perform scoring and does not
need location information, disjunction queries are optimized by
directly OR'ing the underlying bitset.  This avoids all the
usual multi-iterator disjunction logic.  However, in it's
traditional form, we still have a TooManyClauses limit, and
this makes sense as all the underlying iterators are still
in memory at one time.
Observation: The MultiTerm search is unique in that we have a
flat list of terms that are used to build the disjunction.
This is significant because it means we can ensure that
all the underlying searchers are optimizable.
By combining these two observations we can introduce a new mode
of operation for the MultiTerm search.  When it does not perform
scoring and does not need location information, we can do …
> remove TooManyClauses limitation when optimizable

- go.mod
- index/scorch/snapshot_index.go
+ Fixes https://github.com/blevesearch/bleve/issues/1442
+ Also removing unnecessary go.mod entry for ghistogram
> Fix mishandled error within IndexSnapshot's newDocIDReader

- index/scorch/optimize.go
- index/scorch/scorch_test.go
- index/scorch/segment/unadorned.go
- index/scorch/segment_plugin.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_tfr.go
- search/searcher/search_multi_term.go
- search/searcher/search_term_range_test.go
When a conjunction or a disjunction query is eligible to be optimized
to conjunctionUnadorned or disjunctionUnadorned, roaring.Bitmaps are
created by AND-ing or OR-ing the individual bitmaps. These'll need
to be released - for GC.
> MB-40916: Do not recycle unadorned term field readers for optimized conjunctions/disjunctions

- search/searcher/search_numeric_range.go
+ Return the error upon failure to close the field dictionary
obtained from the IndexReader.
+ Fixes: https://github.com/blevesearch/bleve/issues/1444
> Fix mishandled error within NewNumericRangeSearcher

- index/scorch/optimize.go
- search/searcher/search_multi_term.go
+ Getting rid of the minChildCardinality heuristic for optimized
unadorned disjunctions where we previously used to skip the
optimization in case of low-cardinality bitmaps.
+ Removing this heuristic showed tremendous improvement for certain
types of queries which involved a conjunction of disjunctions of
fuzzy queries.
+ However, here's something worth noting from the commit that introduced
this heuristic .. https://github.com/blevesearch/bleve/commit/58e6641d13844e212687bd35823914c5e26b04dd
```
Regarding perf microbenchmarks (bleve-query) on a 200K en-wiki docs scorch index...
for a high number of high-frequency terms...
- wildcard search on "th*" (~31K hits)...
before the change, with normal scoring         -  ~4.7 q/sec
w/ NoScore:true                                -  ~5.1 q/sec
w/ …
```
> MB-40962: Dropping the heuristic to skip disjunction optimizations

- search/sort.go
Fixing the filterTermsByType method by resetting
the terms only when valid prefix coded, zero shifted
values are found to guard against any inadvertent overrides
of the original field values.
> MB-40730 - Sort by field returns incorrect results

- index/scorch/mergeplan/merge_plan.go
Intention was for calcBudget local var to either use
the CalcBudget provided in the Options, or fall back
to the default mergeplan.CalcBudget method.  However,
after assigning the correct impl to the calcBudget
local var, the code always invoked
mergeplan.CalcBudget anwyay.
This change allows the CalcBudget option to work as
intended.
> fix ineffectual assignment

- go.mod
This fixes issues related to bad usage of the
unsafe library.
> Upgrading go.mod tags for etcd-io/bbolt, RoaringBitmap/roaring

- go.mod
zap v11 v11.0.10
zap v12 v12.0.10
zap v13 v13.0.2
zap v14 v14.0.1
> bump bleve versions for next bleve release

- index/scorch/optimize.go
- index/scorch/segment/segment.go
- index/scorch/segment/unadorned.go
- index/scorch/segment/zap/posting.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_tfr.go
- index_test.go
- search/searcher/search_disjunction.go
- search/searcher/search_disjunction_heap.go
- search/searcher/search_disjunction_slice.go
- search/searcher/search_fuzzy.go
- search/searcher/search_multi_term.go
- search/searcher/search_numeric_range.go
- search/searcher/search_regexp.go
- search/searcher/search_term.go
- search/searcher/search_term_prefix.go
- search/searcher/search_term_range_test.go
Fixes for:
- MB-40916: Memory leak observed when using conjuncts/disjuncts with score:none optimization
- MB-40961: Inconsistent results seen with and without score:none for disjunct queries
- MB-40962: Remove TooManyClauses limitation for optimizable queries
- MB-40962: Dropping the minCardinality heuristic for unadorned optimized disjunctions
> Backports for 6.6.1: MB-40916, MB-40961, MB-40962

- search/collector/topn.go
- test/tests/sort/data/d.json
- test/tests/sort/data/e.json
- test/tests/sort/data/f.json
- test/tests/sort/searches.json
This is a backport of: https://github.com/blevesearch/bleve/pull/1334
This change attempts to enable users provide the last
fetched document's score or ID values as keys in the
search after/before fields to make the deep pagination
works for the default _score or _id based sort orders.
> MB-41541: [BP] Enabling score/id based search_after/before paginations

- mapping/mapping_test.go
`go test` fails on my macos (go 1.15.2), complaining:
mapping/mapping_test.go:962:31: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
This PR fixes the issue by just doing what the error suggests. But I didn't dig into whether this is the thing that should be done and what the code actually did before this change.
> fix tests on go 1.15

- index/scorch/scorch.go
- index/scorch/snapshot_index.go
Adding a new stat `num_bytes_used_disk_by_root_reclaimable`
which hints about the approximate amount of reclaimable disk space
from a scorch index. This could turn out to be a useful insight
into knowing the amount of disk space wasted due to tombstoned/obsoleted
contents across the segments and could potentially act as a trigger input
for the forceMerge api.
> New stats for reclaimable disk space from scorch index

- index_impl.go
When index opening fails in some later stage, after storage is opened, nil and error are returned, but the index remains open. There is no way for the user to close the index, because of nil.
The fix closes the index when nil is going to be returned.
> Index is always left closed when opening process failed

- config.go
Hi!
In package `bleve` function `init` runs several goroutines for procession analysis queue.
In some cases we need to shutdown this goroutines. For example, it triggers goleak tool.
```
package main
import (
"testing"
"github.com/blevesearch/bleve"
"go.uber.org/goleak"
)
func main() {
var idx bleve.Index
_ = idx
}
func TestMain(m *testing.M) {
goleak.VerifyTestMain(m)
}
```
Causes:
```
goleak: Errors on successful test run: found unexpected goroutines:
...
```
Also, when `SetAnalysisQueueSize` is called analysis queue size not set to specified size, but increased on this number because exited workers isn't closed.
This PR adds `Shutdown` function that closes analysis queue from user's code and closes queue when new size is set.
> Shutdown analysis queue

- analysis/char/asciifolding/asciifolding.go
- analysis/char/asciifolding/asciifolding_test.go
Hi, following error happened in my application:
```
panic: runtime error: index out of range [189006] with length 189006
goroutine 9 [running]:
github.com/blevesearch/bleve/analysis/char/asciifolding.foldToASCII(0xc00720c000, 0x2e155, 0x2e800, 0x0, 0xc007f16000, 0x2e155, 0xb8554, 0
~/go/pkg/mod/github.com/blevesearch/bleve@v1.0.9/analysis/char/asciifolding/asciifolding.go:65 +0x84a9
github.com/blevesearch/bleve/analysis/char/asciifolding.(*AsciiFoldingFilter).Filter(0x14617e8, 0xc004bf0000, 0x4976c, 0x4a000, 0x2, 0x1, 
~/go/pkg/mod/github.com/blevesearch/bleve@v1.0.9/analysis/char/asciifolding/asciifolding.go:44 +0x162
github.com/blevesearch/bleve/analysis.(*Analyzer).Analyze(0xc001c0a0c0, 0xc004bf0000, 0x4976c, 0x4a000, 0xc003348000, 0xc003349a00, 0x0) …
```
> Fixed ASCII folding of \u24A2

- index_test.go
- mapping/index.go
+ DocValuesDynamic defaults to "true" if unset.
+ Now, because of the "omitempty" json setting for the attribute,
we incorrectly flip a "false" setting for the attribute (which is
omitted as it's the zero value for boolean) to "true" (it's default).
+ Dropping the omitempty setting for this attribute corrects the
behavior to this:
- when unset, DocValuesDynamic will default to true (like before)
- when set, DocValuesDynamic will take that value and will retain
the value until an index definition update for the setting.
+ Fixes https://github.com/blevesearch/bleve/issues/1484
(where the scenario is highlighted better)
> Fix DocValuesDynamic's json-ability within IndexMappingImpl

- cmd/bleve/cmd/bulk.go
- cmd/bleve/cmd/check.go
- cmd/bleve/cmd/index.go
- cmd/bleve/cmd/query.go
Default is added to the output automatically by the flags package, so having it in the text as well is redundant. Closes #1488.
> Remove default from text description

- mapping/document.go
- mapping/mapping_test.go
At query time, we sometimes attempt to lookup the correct
analyzer for a field.  When doing so, the "." character can
be interpretted as a path separater.  Doing this can result
in lookup failure in cases where the user specified a field
name which also contains a dot.
This fix addresses the case where the path contains a dot,
but the next element does not match a mapping at this level.
Previously this ended all looukp in this mapping, now we
attempt to match the remaining path as a whole, without
splitting on the dot.
This fix is intended to fix most common cases where a user has
given a field a name with a dot.  However, ambigutities
between custom field names containing dots, and actual mapping
paths can still happen, and must be manually avoided.
> fix analyzer lookup when field name contains dot

- index/scorch/snapshot_index.go
- index/scorch/snapshot_segment.go
- search/searcher/search_numeric_range.go
Logic inside segment implementations has been
moved up the stack into scorch, so that fewer
methods are required in the API.
- Iterator() becomes AutomatonIterator(nil, nil, nil)
- RangeIterator(start, end) now computes an end key
compatible with traditional inclusive start, exclusive
end keys.  Then becomes:
AutomatonIterator(nil, start, endExclusive)
- PrefixIterator(prefix) now computes an end key
and becomes:
AutomatonIterator(nil, prefix, prefixEnd)
NumericRangeSearcher updated to no longer require
the IndexReaderOnly interface.  This interface
was only used for non-scorch indexes, but only
scorch actually implemented it.  Removing this
also meant we can remove the OnlyIterator method
from the segment dictionary API.
> reduce index and segment API surface area

- index/scorch/regexp.go
- index/scorch/regexp_test.go
- index/scorch/snapshot_index.go
this code was originally placed in the segment package,
however it is only used by scorch, and makes more sense
to be placed at this level
> move regexp compilation into scorch

- index/scorch/empty.go
- index/scorch/int.go
- index/scorch/int_test.go
- index/scorch/optimize.go
- index/scorch/persister.go
- index/scorch/rollback.go
the empty postings iterator is now only used
by scorch's optimize.go, so it is relocated here
the uvarint ascending encode/decode is only used
by scorch, so it too is moved inside this package
> move in more things from the segment package

- index/upsidedown/field_cache.go
- index/upsidedown/upsidedown.go
previous the FieldCache type was in the index package,
but it is only used by upsidedown, so we relocate it there.
> move FieldCache into upsidedown

- error.go
- index/upsidedown/upsidedown.go
- index_impl.go
- index_test.go
this removes the top-level bleve err ErrUnknownIndexType
instead, now the upsidedown specific error is returned.
users who actually care and are checking for this error type
still can, only now it is defined in the upsidedown package.
> make ErrUnknownIndexType upsidedown specific

- search/searcher/search_regexp.go
this interface is only used by the searcher package, thus
it makes sense to define it there
> move regexp interface to searcher

- cmd/bleve/cmd/dump.go
- cmd/bleve/cmd/dumpDoc.go
- cmd/bleve/cmd/dumpFields.go
- http/debug.go
- index/upsidedown/dump_test.go
the dump methods were only ever supposed by upsidedown
now, users of this method must type-assert that their reader
is from the upsidedown package, where these methods remain,
unchanged.
> remove use of dump methods from index reader

- config.go
- examples_test.go
- index.go
- index/scorch/segment_plugin.go
one example required updating as it's custom sort contained a
tie (both fields with age 0).  upsidedown always returned the
results in a particular order, which was not guaranteed by scorch.
to address this, the exmaple has been updated to include the
doc id as an additional sort criteria (ensuring the original
order expected is kept by scorch)
> switch default index to scorch with latest zap

- search/highlight/format/html/html.go
- search/highlight/format/html/html_test.go
depending on the analyzer used, it is possible for the search
term itself to contain characters which should be escaped
before generating html output. this commit adds escaping
on the term itself, and adds some unit tests as well.
> also escape the matched term

- index/scorch/int.go
- index/scorch/int_test.go
it appears that while moving files around I mistakenly
changed a copyright header, which was not my intention
> restore correct copyright header

- search/query/match.go
- search/query/query_test.go
Right now `MatchOperator` constants are ints and when you're trying to
assign them to a variable you get an int. If you try to use those
variables as an operator you get the following error:
```
cannot use operator (type int) as type MatchQueryOperator in argument to q.SetOperator
```
So, to fix this problem we just need to create `MatchOperator` constants
> MatchOperator should be that type instead of int

- index/scorch/scorch.go
- index/upsidedown/analysis.go
- test/tests/sort/searches.json
Note that these APIs have different signatures for the two.
> Adding back an exported Analyze(..) API for scorch & upsidedown

- search.go
+ Check this test ..
```
func TestEstimate(t *testing.T) {
q := []byte(`{"from":8996,"highlight":{},"query":{"bool":false,"field":"free_parking"},"size":405}`)
var sr *SearchRequest
err := json.Unmarshal(q, &sr)
if err != nil {
t.Fatal(err)
}
x := MemoryNeededForSearchResult(sr)
fmt.Println(x)
}
```
+ For the query, the MemoryNeededForSearchResult API claims that it
needs .. 6363433784 bytes (that's over 6GB!).
+ Fixing the size calculation estimate when the query requests for
"fields" to be returned or "highlighting", basing the number of
results returned on the collector's PreAllocSizeSkipCap.
+ Also removing the factor "numDocMatches" to the document size in
this scenario.
> MB-31358: Estimation of memory needed for query with highlighting

- index/scorch/scorch.go
- index/scorch/scorch_test.go
Users can specify the config setting bolt_timeout with a string,
this string will be parsed using time.ParseDuration.  The
resulting time.Duration will be set as the bolt option Timeout
when the bolt database is opened.
For more information about this bolt setting see:
https://github.com/etcd-io/bbolt/blob/f6be82302843a215152f5a1daf652c1ee5503f85/db.go#L1020-L1023
fixes #1491
> introduce new scorch config bolt_timeout

- index/upsidedown/store/moss/lower.go
- index/upsidedown/store/moss/stats.go
+ There appears to be racey code path in obtaining stats for a
moss store that has since been closed.
+ Fetch histograms from moss within lock to avoid this panic ..
```
http: panic serving 127.0.0.1:36252: runtime error: invalid memory address or nil pointer dereference
goroutine 1069 [running]:
net/http.(*conn).serve.func1(0xc0004301e0)
/home/couchbase/.cbdepscache/exploded/x86_64/go-1.13.7/go/src/net/http/server.go:1767 +0x139
panic(0xffeba0, 0x1cb22b0)
/home/couchbase/.cbdepscache/exploded/x86_64/go-1.13.7/go/src/runtime/panic.go:679 +0x1b2
github.com/couchbase/moss.(*Store).Histograms(...)
/home/couchbase/jenkins/workspace/couchbase-server-unix/server_build/gopkg/go-1.13.7/pkg/mod/github.com/couchbase/moss@v0.1.0/store_stats.go:89 …
```
> MB-44216: Race in closing moss store and obtaining stats

- .github/workflows/tests.yml
(We should probably remove 1.13 too).
> add Go 1.16 to the test matrix

- search/search_test.go
- search/sort.go
Using unicode/utf8's MaxRune as the `HighTerm` for sort while
missing values.
> MB-47476: JSON marshalers cannot work on `0xff` (HighTerm)

- search/search.go
Previously the implementation of Complete used the zero
value of a string to detect and handle the first time
though a loop iteration.  If however, we decide to support
the empty field name, this change is required to correctly
differentiate between first iteration of the loop and a
field with empty name.
relates to #1593
> fix Complete method to hand empty field name

- index.go
- index/scorch/builder.go
- index/scorch/persister.go
- index/scorch/snapshot_index.go
- index_impl.go
- index_meta.go
- index_test.go
Approach used is to acquire an index snapshot
and reuse existing code for persisting
snapshot segments and recording snapshot
information into the root bolt.
> Introduce online Copy for scorch indexes.

- index/scorch/merge.go
+ Fixes: https://github.com/blevesearch/bleve/issues/1609
panic: close of closed channel
goroutine 68 [running]:
github.com/blevesearch/bleve/v2/index/scorch.(*closeChWrapper).close(0xc000346b80)
/Users/runner/work/bleve/bleve/index/scorch/merge.go:228 +0x99
github.com/blevesearch/bleve/v2/index/scorch.(*closeChWrapper).listen(0xc000346b80)
/Users/runner/work/bleve/bleve/index/scorch/merge.go:235 +0x1cd
created by github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).planMergeAtSnapshot
/Users/runner/work/bleve/bleve/index/scorch/merge.go:275 +0x4ba
> Address panic on closing a previously closed channel

- search/highlight/fragmenter/simple/simple.go
- search/highlight/fragmenter/simple/simple_test.go
Fix simple fragmenter utf8 out of bounds when `highlight.TermLocations` is nil
> fix utf8 out of bounds

- mapping.go
- mapping/document.go
- mapping/field.go
A keyword field mapping is a text field with `keyword` analyzer. It will be easier for users who are migrating from ElasticSearch.
closes #1633 
Dear @abhinavdangeti, could you help review and give your opinions?
p.s. i signed the CLA.
> Introduce `NewKeywordFieldMapping()`.

- search/query/query_string_lex.go
- search/query/query_string_lex_test.go
- search/query/query_string_parser_test.go
+ This is the fix put forth by @mschoch here ..
https://github.com/blugelabs/query_string/pull/6
+ The bug:
The query string age:65^10 appears to be valid.
It should match documents that have the exact value 65 in the age field,
and scores produced by this clause should be boosted by 10.
(NOTE: due to the way our query string works, we will attempt to find text
and numeric matches of "65", but this does not directly relate to the bug)
Today, the lexer produces these 3 tokens:
string "age"
colon
string "65^10"
In this case, it will still parse correctly in the grammar,
but it will search for a term that does not exist,
and this is not the query the user expressed.
After the fix, the lexer produces these 4 tokens:
string "age"
colon
number 65
boost 10
> Fix issue found in lexer when the ~^: characters are encountered in the inNumOrStrState state

- search/facet/facet_builder_datetime.go
- search/facet/facet_builder_numeric.go
- search/facet/facet_builder_numeric_test.go
- search/facet/facet_builder_terms.go
- search/facet/facet_builder_terms_test.go
- search/facets_builder.go
Replace O(n) implementation in FacetsBuilder.UpdateVisitor
The existing implementation iterated over every facet in the search request and called `UpdateVisitor` along with the field name.
The new implementation maintains a map of FacetBuilders referencing each field and only calls `UpdateVisitor` on the relevant FacetBuilders.
> optimize FacetsBuilder

- analysis/char/html/html.go
- search_test.go
+ I've tracked this down as a regression that was introduced
when I changed the regexp character filter's replacement
behavior here - https://github.com/blevesearch/bleve/pull/1351
+ The above change is still necessary for highlighting to work
correctly when regexp character filter is used and for
replacements that involve '$' variables.
+ The HTML character filter which uses the regexp character
filter will need to replace every character of the matched
sequence with whitespace so that the number of whitespaces
equals the length of the HTML tag.
+ Tracking ticket: https://issues.couchbase.com/browse/MB-50002
> Use of HTML character filter breaks highlighting

- document/field_geopoint.go
- geo/geo_s2_utils.go
- geo/parse_test.go
- go.mod
- go.sum
- index/scorch/builder.go
- index/scorch/scorch.go
- index/scorch/segment_plugin.go
- index/scorch/snapshot_index.go
- search/searcher/search_geoboundingbox.go
- search/searcher/search_geopointdistance.go
- search/searcher/search_geopolygon.go
Indexing and searching of geo points are based out of
multi-precision tokens generated from the morton
hash of the original geo point. And this commit
adds another configurable index level option to
load and use google's s2gemetry library for generating
the hierarchical spatial tokens for both indexing
and search flows. This has shown considerable
performance improvements to the memory usage as
well as to throughout of geo point queries.
(up to 5X)
In the absence of the config override for s2
plugin, the conventional ways of geo token
generation prevails. And this would let all the
existing indexes works as usual.
> Configurable hierarchical spatial tokens using s2geometry.

- go.mod
- go.sum
- search/searcher/search_geoshape_polygon_test.go
This version bump primarily includes a porting fix
in s2/loop.go in the original golang port version.
This change also includes a unit test that covers
the case.
> Updating the s2/geo version

- go.mod
- go.sum
- search/searcher/geoshape_intersects_test.go
- search/searcher/geoshape_within_test.go
This PR extends the unit tests for 'intersects', particularly polygon-linestring tests. 
It also fixes some issues with geometry collection unit tests across relations.
> Added intersects unit tests and fixed existing tests.

- search/query/query.go
- search/query/query_test.go
- search_test.go
Related: https://github.com/blevesearch/bleve/pull/1546
> MB-40604: Support IPRange query

- query_bench_test.go
Here're results on my computer:
```
[12:52:04] AD: ~/Documents/go/src/github.com/blevesearch/bleve $ go test -run=BenchmarkQuery -bench=BenchmarkQuery -v
goos: darwin
goarch: amd64
pkg: github.com/blevesearch/bleve/v2
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkQueryTerm
BenchmarkQueryTerm-12                     181676              6309 ns/op            4130 B/op         59 allocs/op
BenchmarkQueryTermRange
BenchmarkQueryTermRange-12                 72004             16440 ns/op            7286 B/op         94 allocs/op
BenchmarkQueryWildcard
BenchmarkQueryWildcard-12                   4686            251194 ns/op          124294 B/op        291 allocs/op
BenchmarkQueryNumericRange
BenchmarkQueryNumericRange-12              59023             20151 ns/op           12760 B/op …
```
> Adding benchmark tests over some popular queries

- search.go
Currently, when firing multiple queries with "score" : "none", the first query response displays the non-zero bytesRead as part of the JSON response. Subsequent queries do not display it as part of the response since the bytesRead is 0.
This PR fixes it such that even if the bytesRead is 0, it displays it as part of the response.
> Display 0 bytesRead in search responses

- go.mod
- go.sum
To include:
* 67addef Callum Jones | Fixed 64-bit alignment panic in chunkedContentCoder on 32-bit platforms. (#148)
> Upgrade zapx@v15 to v15.3.9

- index/scorch/persister.go
This change aims to make the IO Stats part of internal keys such that on rollback to a checkpoint, the IO stats can be retrieved using GetInternal() API after the rollback.
> Including the IO stats as part of metadata

- index/scorch/event.go
- index/scorch/scorch.go
+ This change in signature is necessary to introduce some more context in the user application to associate the scorch index with the error.
> MB-55637: Adapting signature of scorch's async onError callback

- index/upsidedown/index_reader.go
- index/upsidedown/upsidedown.go
This pull request replaces the existing `sync.Pool` implementation with a more optimized version that uses pointers to objects. Specifically, the `GetRowBuffer()` function now returns a pointer to a `RowBuffer` object that contains a byte slice, instead of returning the byte slice directly. The `PutRowBuffer()` function now takes a pointer to a `RowBuffer` object instead of a byte slice.
Storing pointers instead of values can help reduce memory usage and avoid unnecessary copying of buffer data. Additionally, using pointers can reduce the overhead of creating and copying data, which can improve performance.
> perf: Use pointer-based `sync.Pool` for optimized memory management

- analysis/lang/en/plural_stemmer.go
- analysis/lang/en/plural_stemmer_test.go
+ This contribution was made by https://github.com/jgschis .
+ This has not been incorporated into the `en` analyzer.
+ The user will however be able to build a custom analyzer with the `en` components alongside this.
+ For: https://github.com/blevesearch/bleve/issues/1750
+ Also: https://issues.couchbase.com/browse/MB-56359
> Add english plural stemmer as a new token filter

- cmd/bleve/cmd/root.go
- go.mod
- go.sum
+ Index Open and Close are not applicable for this CLI: `bleve completion ...`
+ Also, upgrade to spf13/cobra@v1.7.0
+ Addresses: https://github.com/blevesearch/bleve/issues/1816
> bleve index operations not applicable to cobra's completion commands

- index/scorch/scorch.go
- index/scorch/snapshot_index_tfr.go
- index_impl.go
- index_test.go
- search.go
- search/collector/topn.go
- search/query/geo_boundingbox.go
- search/query/geo_boundingpolygon.go
- search/query/geo_distance.go
- search/query/geo_shape.go
- search/query/numeric_range.go
- search/search.go
- search/searcher/search_fuzzy.go
- search/searcher/search_geoboundingbox.go
- search/searcher/search_geopointdistance.go
- search/searcher/search_geopolygon.go
- search/searcher/search_geoshape.go
- search/searcher/search_numeric_range.go
- search/searcher/search_regexp.go
- search/searcher/search_term.go
- search/searcher/search_term_prefix.go
- search/searcher/search_term_range.go
- search/util.go
- test/versus_test.go
- Adds a new callback function SearchIncrementalCostCallbackFn which is used to track incremental cost updates for the query. It can also be used to track costs for different types of queries as well.
- Renames "bytesRead" to "search_cost"
> recording the cost for different types of queries

- mapping/document.go
- mapping/index.go
+ This is to half the number of times we iterate through the document mappings while mapping a document.
> MB-57394: Consolidate documentMappingForPath & closestDocMapping

- search/collector/topn.go
- search/collector/topn_test.go
- search_test.go
When a query sorts by the same field as the facets, the number of search results per facet doubles. This is because there is double counting of the documents by the collector on that field for both sorting and faceting.
This PR deduplicates the fields in the collector to avoid this.
> Avoid double counting when sorting by field for faceted query

- search/search.go
- search/searcher/search_disjunction_heap.go
- search/searcher/search_disjunction_slice.go
- search_test.go
[MB-55479](https://issues.couchbase.com/browse/MB-55479)
Search result set for Match Queries now reflect if the Hit was a partial or a full match using a boolean flag
> MB-55479: Reflect partial or complete match for match queries

- config.go
- http/util.go
- index_test.go
- mapping/mapping.go
- search/query/query.go
I think it would be better to change the io/ioutil package to the os package.
Please check the [link](https://go.dev/doc/go1.16#ioutil) and code and thank you.
Bleve search is using go 1.19 so I think it is better not to use io/ioutil package.
> Replacing deprecated io/ioutil functions

- analysis/datetime/flexible/flexible_test.go
- analysis/datetime/optional/optional.go
- index_test.go
[MB-57972](https://issues.couchbase.com/browse/MB-57972)
Currently in Couchbase sample datasets:
1. gamesim-sample: No date fields are there
2. travel-sample: A reviews.date field is there with the layout YYYY:MM:DD HH:MM:SS Offset
3. beer-sample: A date field is there with layout YYYY:MM:DD HH:MM:SS
A default mapping (uncustomized) will use dateTimeOptional which has layouts to parse beer-sample but not travel-sample, because of this the user needs to set a custom date time parser to do a date-range query on travel sample. To avoid this and enchance UX, add YYYY:MM:DD HH:MM:SS Offset layout to dateTimeOptional
> MB-57972: Add new layout to dateTimeOptional

- search/query/match_phrase.go
- search/query/multi_phrase.go
- search/query/phrase.go
- search/query/query.go
- search/searcher/search_fuzzy.go
- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
- search/util.go
[MB-31210](https://issues.couchbase.com/browse/MB-31210)
Added fuzziness support for MatchPhrase queries.
> MB-31210: Support Fuzzy MatchPhrase, MultiPhrase and Phrase queries

- analysis/datetime/sanitized/sanitized.go
- analysis/datetime/sanitized/sanitized_test.go
- config/config.go
- search_test.go
[MB-57973](https://issues.couchbase.com/browse/MB-57973)
Currently user does not receive any feedback if the custom date time parser input by him is valid or not. These custom parsers must only contain magic numbers/ constants specified in https://pkg.go.dev/time#pkg-constants else it is not valid even though no error is returned buy the time package. The input validation here ensures only valid magic numbers are used.
> MB-57973: Validate custom date time parser layout 

- index_impl.go
In case a document is not found, a nil check is required since `doc.StoredFieldsBytes()` then results in a panic.
> Added missing nil check

- go.mod
- go.sum
Includes:
* dd26ea1 Thejas-bhat | command line tool support for vector search (#175)
* d292ef9 Thejas-bhat | replacing the flat index with the IVF family index. (#180)
* f5e149a Thejas-bhat | bug fix: accounting the vecIDs approriately while merging (#179)
* 0296d71 Thejas-bhat | optimization: avoiding storing of bitmaps when vector is in a single document (#181)
* 6b9b047 Abhi Dangeti | MB-59692: Respect choice of similarity metric, bleve_index_api@v1.1.3 (#182)
* e1fe4fb Abhi Dangeti | MB-59569: Upgrade to blevesearch/go-faiss@v1.0.3 (#183)
> Upgrade zapx@v16

- index_impl.go
- search_knn.go
- search_knn_test.go
- search_no_knn.go
This PR allows a user to specify a KNN Operator to determine if KNN hits are conjuncted/disjuncted with filter query hits.
> Add KNN Operator

- search_knn.go
- search_knn_test.go
total must reflect total doc hits in full index and not just the number of hits returned as part of search result
> MB-59766: Fix total calculation

- search/scorer/scorer_knn.go
- search/scorer/scorer_knn_test.go
- search/searcher/search_knn.go
This PR adds a score Explanation to the KNN scorer, along with a unit test.
Also, contains a minor refactor of scoring related code.
> Adding KNN scorer explanation

- search_knn.go
Addresses a bug introduced with https://github.com/blevesearch/bleve/pull/1935
> MB-60077: Accommodate kNNOperator validation better

- mapping/mapping_vectors.go
- mapping/mapping_vectors_test.go
- search_knn_test.go
- util/extract.go
Enable user to chunk vectors ([]float32) into nested_vectors ([][]float32).
This is helpful to capture more intent from text or to use multiple vector generation models for the same input.
While mapping a document, user submitted nested_vectors are flattened and submitted to bleve_index_api.Index impl (Scorch).
Scorch will then submit it to the segment plugin (Zapx).
Zapx is expected to realise that this flattened_vector have length more than Dims.
zapx should read all the subVecs out of the flattened_vector and index them individually.
We are not passing the nested_vector directly to zap. This is done to keep the API contract intact.
related changes:
https://github.com/blevesearch/zapx/pull/185
> MB-59447: support nested/chunked vectors

- mapping/document.go
- mapping/field.go
- mapping/index.go
- mapping/mapping_no_vectors.go
- mapping/mapping_vectors.go
- mapping/mapping_vectors_test.go
vector field Aliases (fields with same name and type as vector) must have same value for dimensions and similarity, respectively.
> MB-59421: add validation for vector field aliases

- error.go
- index_alias_impl.go
- index_alias_impl_test.go
- index_impl.go
- search/collector.go
- search/collector/knn.go
- search/collector/topn.go
- search/query/query.go
- search/scorer/scorer_knn.go
- search/search.go
- search/searcher/search_conjunction.go
- search/searcher/search_disjunction_heap.go
- search/searcher/search_disjunction_slice.go
- search/searcher/util_knn.go
- search/searcher/util_no_knn.go
- search/util.go
- search_knn.go
- search_knn_test.go
- search_no_knn.go
- Reverts commit https://github.com/blevesearch/bleve/pull/1910, which was an earlier attempt to address this issue.
- Implements the PreSearch Construct in Bleve alias search, enabling a preliminary query to collect metadata from all alias indexes before executing the main search query in MultiSearch. PreSearch gathers KNN results from all alias indexes, selecting the top K results. This facilitates the main Bleve Query to operate within the context of documents that matched the KNN query, ensuring seamless functionality of existing Bleve constructs such as Faceting, Sorting, Pagination, SearchAfter, and SearchBefore.
- Introduces the KNN Collector construct to merge and obtain accurate Top K results from multiple Zap Segments' KNN results.
- Enhances KNN Unit Tests for greater …
> MB-59102: Merging kNN hits from a distributed index with exact search hits

- search/collector/topn.go
- search_knn.go
Based on the updated definition of knn_operator = and, the hits from the Query object are to be Union'd with all the KNN hits irrespectve of the value of "knn_operator"
> MB-60125: Update knn_operator =  "and" to intersect only KNN hits

- search/collector/topn.go
- search_knn.go
This is simply a dup of https://github.com/blevesearch/bleve/pull/1938.
I guess it was the order in which I merged things, this didn't get included into `unstable`, so here we go.
> MB-60125: Update knn_operator = "and" to intersect only KNN hits

- search/collector/knn.go
- search/collector/topn.go
- search/scorer/scorer_disjunction.go
- search/scorer/scorer_knn.go
- search/scorer/scorer_knn_test.go
- search/searcher/search_disjunction_heap.go
- search/searcher/search_disjunction_slice.go
- search/util.go
- search_knn.go
- search_knn_test.go
- search_test.go
- The score explanation is now accurate. It's determined by establishing the final score and its explanation only when the KNN hits are finalized. This happens after a PreSearch for an index alias or at the end of the KNN collector phase for a single index.
> MB-60081: Fix Score Explanation

- search_knn.go
https://issues.couchbase.com/browse/MB-60274
Currently, the value of K in KNN queries is only lower-bounded to 1 without an upper limit. This lack of an upper boundary leads to issues where users setting K to extremely high values, such as 999999999, cause a crash due to excessive memory allocation exceeding 8GB.
To address this issue, this commit introduces an upper bound check for variable K. Setting an upper limit of 10000 for K prevents excessive memory demands, capping the maximum memory requirement at a reasonable 120KB. This change ensures system stability by preventing memory overflow issues caused by excessively high K values."
> MB-60274: Set an upper bound for K value for KNN queries

- error.go
- index_alias_impl.go
- search/search.go
- search_knn.go
- search_no_knn.go
In a distributed indexing setup, the child indexes linked to an alias are labeled as `[IP]:[port]/[indexName]`. During a two-phase KNN search, if a node is taken out and re-added (by means of a rebalance operation) after the first phase but before the start of the second phase, the reference to the child index in the alias remains unchanged (with the same IP address, port, and indexName). However, the actual indexes present on that node will differ from those available during the first phase. This discrepancy causes inaccurate results due to inconsistencies in the indexId stack.
This method substitutes the indexId with the specific indexName, ensuring redistribution even if the index arrangement undergoes changes. Yet, if the index isn’t found within that alias, an error will be …
> MB-60241: Add consistency checks for redistribution of KNN hits

- analysis/lang/es/analyzer_es.go
- analysis/lang/es/light_stemmer_es.go
- analysis/lang/es/spanish_normalize.go
- analysis/lang/es/spanish_normalize_test.go
Normalization of accented letters only happens if the input is larger than 5 characters, something that, for example, neither `guía` nor `fría` comply.
The solution would be to always execute the accented characters normalization, by moving it to a separate file just like it is done in the german analyzer.
Fixes: https://github.com/blevesearch/bleve/issues/1956
> Fixed spanish accents normalization

- go.mod
- go.sum
Includes:
* cefd4af Aditi Ahuja | Changing the defaults for centroid count and nprobe. (https://github.com/blevesearch/zapx/pull/203)
> MB-60209: Upgrade to blevesearch/zapx/v16@master & blevesearch/go-faiss@v1.0.4

- index_alias_impl.go
- index_impl.go
- search/collector/topn.go
- search_knn.go
- search_no_knn.go
If a search request has KNN requests in it, and
- the main query is a match_none 
- the facets request is nil 
the final search result is constructed with just the presearch results, and multi search is skipped.
> Optionally skip multisearch after presearch

- go.mod
- go.sum
Includes:
* c19e7ab Aditi Ahuja | MB-60202 - Filtering deleted documents during FAISS vector index search (https://github.com/blevesearch/zapx/pull/205)
> MB-60202: Upgrade zapx/v16 for fix

- index_alias_impl.go
Ensure the integrity of Presearch operation by resetting the presearch result in an alias when encountering the following conditions, preventing inaccuracies in the final result:
- Any child index fails during the operation.
- Any child alias provides partial results.
> MB-60370: Reset search result if presearch fails

- index/scorch/optimize_knn.go
- search_knn_test.go
- Calling InterpretVectorIndex() with BleveMaxK = 10000 results in 200KB of memory usage per call. With a million documents and around 1000 Zap segments (a scenario that occurs while the index is still being built and the merger routine is still running), parallel calls consume 200MB, making it necessary to limit the concurrency involved.
- Created a global variable named BleveMaxKNNConcurrency with a value of 10, representing the maximum number of concurrent goroutines allowed. This ensures that 10 segments can be read concurrently at once.
> MB-60400: Add a semaphore for concurrently reading vector indexes from zap segments

- go.mod
- go.sum
* 84be009 Abhi Dangeti | Upgrade to go-faiss@v1.0.6 + additional commentary (https://github.com/blevesearch/zapx/pull/207) * d9e6c45 Thejas-bhat | MB-60367: Avoiding extra allocation on C heap while reading index from buffer (https://github.com/blevesearch/go-faiss/pull/12)
* 72fc813 Thejas-bhat | MB-60367: Handle memory allocations more responsibly  (https://github.com/blevesearch/zapx/pull/206)
> Upgrade to zapx/v16@v16.0.1 @ go-faiss@v1.0.6

- mapping/document.go
- search_knn_test.go
- internal API rerouting: avoid calling strings.Split(strings.Join([]string), "."),".") since it returns the same thing 
- parallelize the knn_test for multi segment search to make it faster to run
> MB-60400: Reduce garbage generated

- go.mod
- go.sum
Includes:
* c27bdd0 Rahul Rampure | MB-60400: Reduce Garbage generated (https://github.com/blevesearch/zapx/pull/208)
> MB-60400: Upgrade to zapx/v16@v16.0.2

- go.mod
- go.sum
* eaf077c Thejas-bhat | MB-60367 Restructuring the code for better memory cleanup
> MB-60367: Move up to zapx/v16@v16.0.6

- index/scorch/introducer.go
- index/scorch/merge.go
- index/scorch/optimize_knn.go
- index/scorch/persister.go
- index/scorch/scorch.go
- Avoid creating an unnecessary copy of a bitmap 
- Added capacities for some maps
- Fixed bug where a loop variable was used inside a closure
> Minor optimizations

- mapping/document.go
- mapping/mapping_no_vectors.go
- mapping/mapping_vectors.go
- Currently, the walkDocument function is called after processing every vector, regardless of whether the vector was processed successfully or not. This results in the execution of the following code:
for i := 0; i < val.Len(); i++ {
if val.Index(i).CanInterface() {
fieldVal := val.Index(i).Interface()
dm.processProperty(fieldVal, path, append(indexes, uint64(i)), context)
}
}
- In this code, val.Len() will be equal to the dimension of the vector, which could potentially be very high (up to 2048). For each iteration of the loop, processProperty() is called on each float value extracted from the vector. Within processProperty(), it attempts to add a numeric field and creates a new array using append().
- If the property has already been successfully processed as a vector, then each …
> MB-60400: Do not walk document if vector is processed successfully

- go.mod
- go.sum
* 2f42fb7 Thejas-bhat | MB-60781: Writing the vector section only when there are valid number of vectors in section (https://github.com/blevesearch/zapx/pull/219)
> MB-60781: Upgrade zapx/v16 to v16.0.8

- go.mod
- go.sum
* f0dac5c Thejas-bhat | MB-60816: Using runtime.LockOSThread to bind the running goroutine to the specific OS thread.
> MB-60816: Absorb zapx/v16@v16.0.9 + go-faiss@v1.0.11

- go.mod
- go.sum
* 0c7027f Rahul Rampure | MB-60662: revert doc id cache (https://github.com/blevesearch/zapx/pull/222)
> MB-60662: Upgrade zapx/v16 to v16.0.11

- go.mod
- go.sum
- index/scorch/introducer.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/scorch_test.go
- index/scorch/snapshot_segment.go
- search_knn_test.go
- These metrics are calculated based on analysis results initially and directly from the SegmentBase after a merge
- This map will be stored in segment Introduction and segment snapshot
- After merge, field level stats are collected from segment base after checking if it implements the FieldStatsReporter interface defined in scorch_segment_api
- This map is also persisted in bolt to avoid recomputation under the key "stats" as part of the persisted part of the segment snapshot
- FieldStats have been added to the StatsMap function of scorch. This will give an aggregated value of the stats with respect to the segments but specific to the field name and the stat using the stat name field:<field name>:<stat name>. For example, field:vector:num_vectors
> MB-60914: Supporting field specific metrics

- index_alias_impl.go
- index_impl.go
- pre_search.go
- search/scorer/scorer_knn.go
- search_knn.go
- search_no_knn.go
- Instead of Merging all the PreSearch Results in one shot at the main coordinator node of an alias tree, merge them incrementally at each level of the tree instead, which would balance the reduction process across all the indexes in a distributed Bleve index, leading to a more even memory distribution.
> MB-60844: MapReduce for PreSearch

- go.mod
- go.sum
- index/scorch/optimize_knn.go
This change is intended to save compute in determining "vectorIdsToExclude" during search(..).
Requires:
- https://github.com/blevesearch/scorch_segment_api/pull/40
- https://github.com/blevesearch/zapx/pull/229
> MB-60791: Conform to new interfaces for VectorIndex & VectorSegment

- index/scorch/merge.go
- index/scorch/stats.go
- There are chances that the merger doesn't see any eligible segments to be merged in the current iteration which causes the tasks list to be empty. In this situation, merger which didn't update the root snapshot would notify the persister. 
- Now, if the persister was napping at this point of time, and assuming there were mutations coming into the system (so the root snapshot would be updated by the introducer) would lead to the persister to be awoken and start flushing out the in-memory segments to disk. 
- Perhaps a better behaviour would be to not let the merger notify the persister when there is no change in the root snapshot. This would help the persister to perform healthier in memory merging of the segments before persisting out to disk thereby helping in controlling the number of …
> MB-60971: Avoiding unnecessary persister notifs from merger

- index/scorch/merge.go
- index/scorch/stats.go
This reverts commit 4fd8313c54855717d27e281fd2fb1faa00c0937f.
> Revert "MB-60971: Avoiding unnecessary persister notifs from merger (#2003)"

- .github/workflows/tests.yml
- go.mod
- go.sum
Includes:
* 9e2514f Aditi Ahuja | MB-60943 - Add a coarse quantiser to the IVF indexes (https://github.com/blevesearch/zapx/pulls/225)
> Bump up zapx/v16 & move GO version to 1.21

- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/stats.go
Authored-by: @Thejas-bhat 
Original: https://github.com/blevesearch/bleve/pull/2003
- There are chances that the merger doesn't see any eligible segments to
be merged in the current iteration which causes the tasks list to be
empty. In this situation, merger which didn't update the root snapshot
would notify the persister.
- Now, if the persister was napping at this point of time, and assuming
there were mutations coming into the system (so the root snapshot would
be updated by the introducer) would lead to the persister to be awoken
and start flushing out the in-memory segments to disk.
- Perhaps a better behaviour would be to let the persister nap for the remaining 
duration such and then let the persister do some work. This would also help in merger
waiting for the notification reply …
> MB-60971: Avoiding work on persister side on no-op notifs from merger

- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/stats.go
This reverts commit 2d81bf0aef3a9bd33a9abe6597618dcb4f469123 ( https://github.com/blevesearch/bleve/pull/2006 ) on account of the regression highlighted with MB-61447.
> Revert "MB-60971: Avoiding work on persister side on no-op notifs from merger"

- go.mod
- go.sum
* 91a5e17 Abhi Dangeti | Revert "MB-60943 - Add a coarse quantiser to the IVF indexes" (https://github.com/blevesearch/zapx/pull/232)
> MB-60943: Bump up zapx/v16 for MB-61470

- go.mod
- go.sum
Includes:
* eeb2336 Likith B | MB-61029: Caching Vec To DocID Map (https://github.com/blevesearch/zapx/pull/231)
* b2384fc Rahul Rampure | minor optimizations and bug fixes (https://github.com/blevesearch/zapx/pull/233)
* b56abea Thejas-bhat | MB-61029: Deferring the closing of vector index (https://github.com/blevesearch/zapx/pull/226)
> Upgrade blevesearch/zapx/v16

- document/field_vector_base64.go
- document/field_vector_base64_test.go
- mapping/document.go
- mapping/index.go
- mapping/mapping_no_vectors.go
- mapping/mapping_vectors.go
- mapping_vector.go
- search_knn.go
- search_knn_test.go
- Added a new field type called vector_base64.
- Acts similar to vector in most cases.
- When a new document arrives in the bleve layer, during the parsing of all its fields in processProperty, if the field mapping type is vector-base64, then its value is decoded into a vector field and processed like a vector.
- The standard golang base64 library is used for the decode operation.
> MB-59616: Adding vector_base64 field

- index_test.go
- search_knn.go
- search_no_knn.go
- Fix the BytesRead and BytesStored unit tests to pass when using the `vectors` tag. The following commands can be used to validate that all UTs now pass.
- go test -tags=vectors -race ./...
- go test -race ./...
> Fix search cost unit test

- mapping/mapping_vectors.go
+ Allow calling application to change min/max.
+ Will require downstream changes to disallow any setting greater
than 2048 in the event of a mixed version cluster.
> MB-61009: Raise max supported dimensionality of vectors to 4096

- index/upsidedown/store/boltdb/store_test.go
+ Test(s) in this file hang on my computer and it seems they've started hanging on the workflow jobs as well.
> Disable upside_down's boltdb tests on darwin arm64

- search/search.go
+ Omitting the score from the document hits when score:"none" causes an older SDK to panic that was expecting to see the attribute regardless.
+ This commit reverts a portion of what was proposed with https://github.com/blevesearch/bleve/pull/1930.
> MB-60719: Do not `omit` score from document hits, even when empty

- go.mod
- go.sum
blevesearch/go-faiss:
* 693b06a Rahul Rampure | MB-61650: Release IDSelectorBatch's batchSelector to avoid memory leak
> MB-61650: Address memory leak in faiss query path

- go.mod
- go.sum
Includes:
* d8f2ddf Abhi Dangeti | MB-60697: Windows requires nprobe to be of 'long long' type
* 9bb55f8 Abhi Dangeti | Retain IDSelector's Delete() API for complete-ness
> MB-60697: Upgrade blevesearch/go-faiss for windows fix

- go.mod
- go.sum
Includes:
* 6fe4e6b Aditi Ahuja | MB-60943 - Reduce number of centroids for IVF indexes.
* 8de5651 Rahul Rampure | add map capacity
> MB-60943: Bump up zapx/v16

- analysis/datetime/timestamp/microseconds/microseconds.go
- analysis/datetime/timestamp/milliseconds/milliseconds.go
- analysis/datetime/timestamp/nanoseconds/nanoseconds.go
- analysis/datetime/timestamp/seconds/seconds.go
- http/doc_get.go
- index_impl.go
- search_test.go
Addresses https://github.com/blevesearch/bleve/issues/2027
In bleve v2.3.10, [a bug fix](https://github.com/blevesearch/bleve/pull/1868) was introduced where the value of a datetime field in the Fields part of a search hit was made to match the value actually present in the document.
- For example if a document A was indexed and had value of a datetime field X to be "2001/08/20 03:00:10", and ifA was returned as part of the search result, A's Fields will have a map which would look like
- Before Fix 
- "X" : "2001-08-20T03:00:10Z"
- After fix 
- "X" : "2001/08/20 03:00:10"
This would come to play in case of custom user defined date time parser, and we did this by storing the layout with which the time string was parsed with during indexing. With timestamp support being added at the same …
> Fix issue in parsing datetime field

- document/field_vector_base64.go
- document/field_vector_base64_test.go
- mapping/mapping_vectors.go
- search_knn.go
- util/extract.go
+ Handle the situation when interpreted vectors have NaN or Inf when decoded from base64 encoded strings.
+ Also, in the vector_base64 path - it seems we were unnecessarily casting a []float32 into an interface{} to again be interpreted as a []float32 which we can avoid.
> MB-61742: Interpreting vectors w/ spurious float32s from base64 encodings

- mapping/index.go
The previous logic here only checked fields one level deep which means any nested fields were not being considered. I replaced these with existing functions to get back the correct field mapping.
> MB-61716: Corrected Field Mapping for Path Logic

- go.mod
- go.sum
- index.go
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/snapshot_index.go
- index_impl.go
- Use a modified index reader, CopyReader, to mark segments in the Scorch root for online copy/backup operations. This prevents their deletion by the asynchronous cleanup routine during the copy/backup process, thereby mitigating the race condition between the merger/persistor and the copy/backup routine.
> MB-61421: Prevent deletion of segments scheduled for copy

- index/scorch/event.go
- index/scorch/event_test.go
- index/scorch/merge.go
- index/scorch/merge_test.go
- index/scorch/scorch.go
This PR adds an event to check whether a merge can proceed based on criteria set by the caller(eg. cbft). If not, it's aborted and the merger loop continues its next iteration. 
Also includes minor refactor to the function signature of the event callback registry to accommodate the new event type.
> MB-60945 - Add scorch event for pre merge check

- go.mod
- go.sum
Requires:
- blevesearch/faiss@17c3992 (branch:bleve)
Includes:
* 8c1937d Thejas-bhat | bug fix: de-duplicating fieldsInv value
* 08059f8 Thejas-bhat | MB-59575: Handling memory mapped content more responsibly
> MB-59575: Upgrade zapx/v16, go-faiss

- go.mod
- go.sum
Needs:
* 7977457 Rahul Rampure | MB-61930: Add a num_threads clause to every openMP pragma.
Brings in:
* 74a854f Rahul Rampure | MB-61930: Use the go-faiss OpenMP API for setting the default number of OMP Threads to be 1 
* Use the go-faiss OpenMP API for setting the default number of OMP Threads to be 1
* Upgrade to go-faiss@v1.0.17
* ec45499 Rahul Rampure | MB-61930: Improve threading performance
> MB-61930: Upgrade faiss (`7977457`), go-faiss + zapx/v16

- go.mod
- go.sum
faiss version to use: `a2f4183`, brings in -
* a2f4183 Rahul Rampure | MB-62221: Fix buffer overflow
go-faiss version to use: `v1.0.18`, brings in -
* 7531ec8 Rahul Rampure | MB-62221: Fix platform specific behaviour
zapx/v16 version to use: `v16.1.3`, brings in -
* 3c35ac7 Abhi Dangeti | MB-62221: Upgrade go-faiss
> MB-62221: Upgrade faiss, go-faiss, zapx/v16

- .github/workflows/tests.yml
- go.mod
- go.sum
- index/scorch/persister.go
- index/scorch/scorch.go
- index/scorch/snapshot_index.go
- index/upsidedown/store/boltdb/store_test.go
- index_impl.go
- Use a modified index reader, CopyReader, to mark segments in the Scorch root for online copy/backup operations. This prevents their deletion by the asynchronous cleanup routine during the copy/backup process, thereby mitigating the race condition between the merger/persistor and the copy/backup routine.
Backports: https://github.com/blevesearch/bleve/pull/2032
> MB-61421: Prevent deletion of segments scheduled for copy (#2032)

- index/scorch/mergeplan/merge_plan.go
There was a small oversight introduced in force merge paths, where `MaxSegmentFileSize` option was missing in the `SingleSegmentMergePlanOptions`. This lead to none of the segments being eligible for a force merge. (https://github.com/blevesearch/bleve/blob/0672efa5cc7e79a9534b11517a9b8808bd8a277a/index/scorch/mergeplan/merge_plan.go#L189)
Consequently I was observing that the force merge was a no op when I triggered the API. Currently, this value has been set to 1TB.
> Updating SingleSegmentMergePlanOptions with MaxSegmentFileSize

- index/scorch/persister.go
- index/scorch/rollback.go
- Added checks for cases where bolt buckets are nil
> MB-62124: Dealing with bolt panics while reading

- document/field_boolean.go
- document/field_composite.go
- document/field_datetime.go
- document/field_geopoint.go
- document/field_geoshape.go
- document/field_ip.go
- document/field_numeric.go
- document/field_text.go
- document/field_vector.go
- document/field_vector_base64.go
- index/scorch/snapshot_index_tfr.go
- index/scorch/snapshot_index_vr.go
- search/scorer/scorer_knn.go
- Fix Size() calculation to account for dynamic entries of the struct, to ensure that accurate information is passed on to the memory throttler
> Fix Size Calculation

- mapping/document.go
- Removed logic that prevents numeric field mappings to be executed after a vector field has been detected
- Added checks to walk document on non vector field types preserving previous logic
> MB-62400: Allow vector and numeric aliases for the same field

- index.go
- index/scorch/event.go
- index/scorch/scorch.go
- index_impl.go
- Add a scorch event for notifying listeners, if available, that a document is about to get added to the index, using the Index() API.
- This event can be useful for halting indexing before the Index() operation is carried out - since Index() converts an interface into a Document object using the IndexMapping's MapDocument, which consumes some extra memory.
- Shifted the EventKindBatchIntroductionStart event to before the documents were analyzed as document analysis consumes extra memory.
> MB-61985: Add a Scorch event for Index()

- search/query/boolean.go
- Early exit in boolean query if must/should/mustNot query list is nil.
> Optimize boolean query handling with early exit on nil conditions

- go.mod
- go.sum
- search_knn_test.go
* 1bb080b Abhi Dangeti | MB-61889: Address corner case with ivf_nprobe_pct
Also drops an unnecessary method in search_knn_test.go.
> MB-61889: Upgrade go-faiss, zapx/v16 for corner case fix

- search_knn.go
This PR adds support for search-time params in the query parser and custom JSON unmarshaling logic.
> MB-62230: Added params in KNN request when parsing a query

- go.mod
- go.sum
- mapping/mapping_vectors.go
- mapping/mapping_vectors_test.go
Uses new version of blevesearch/go-faiss that brings in:
* f19c1d4 Abhi Dangeti | MB-63334: Method to normalize a single vector
(https://github.com/blevesearch/go-faiss/pull/36)
> MB-63334: Use faiss's advertized method to normalize vector

- go.mod
- go.sum
- index/scorch/optimize_knn.go
- index/scorch/snapshot_index_vr.go
- search_knn.go
Currently, there are a bunch of additional computations done on every kNN query that are necessary only for pre-filtered kNN. 
This PR adds checks to perform these only when at least one kNN query, out of one or more in the search request, is a filtered kNN query.
Also added some commentary.
> MB-62230 - Avoiding unnecessary computations for un-filtered kNN.

- docs/vectors.md
- go.mod
- go.sum
zapx:     1c5b688 Abhi Dangeti | MB-62230: Upgrade blevesearch/go-faiss for selector fix
go-faiss: b64c588 Aditi Ahuja | MB-62230 - Use a selector to pick centroid IDs
Update faiss SHA requirement in docs/vectors.md.
> MB-62230: Upgrade zapx, go-faiss to bring in pre-filter fixes

- search/collector/eligible.go
- search/collector/topn.go
- search_knn.go
+ This _MUST NOT_ be replaced with the document handler from the calling application's context which could contain the streaming document match handler used by result streamers (like n1fty). The bug in the current code will cause bleve to prematurely stream interim eligible docs to the listener which is unintended at best.
+ Also a side optimization along allocation in the same code path.
> MB-63736: "EligibleDocumentMatchHandler" is for local purposes only

- search_knn.go
Populates the initialised filter hits map using an index.
> MB-63742 - Fix populating the filter hits map

- go.mod
- go.sum
- index/scorch/optimize_knn.go
- index/scorch/snapshot_index_vr.go
MB-62230:
* Add elements to bitmap in a batch.
* 5f8f0f0 Aditi Ahuja | MB-62230 - Pre-filtering performance optimisations
MB-57871:
* 7bab2f9 Abhi Dangeti | MB-57871: One more nil check before dereferencing postings
* bf971e6 Abhi Dangeti | Add nil pointer checks for postings before dereference
* 9a80f5f Abhi Dangeti | One more case for zero chunk size / mode
* 0c6f397 Mohd Shaad Khan | Handle zero chunk size
> MB-57871, MB-62230: Upgrade to zapx/v16@v16.1.7 + go-faiss@v1.0.23

- mapping/mapping_vectors.go
- Normalizing the query vector in place would create a race condition, causing different 
indexes within an alias to receive inconsistent query vectors. 
- This inconsistency could lead to incorrect results when merging hits from all indexes in the 
alias.
> MB-63334: Fix race condition in NormalizeVector

- go.mod
- go.sum
Includes:
* f19d5f0 Aditi Ahuja | MB-63992 - High selectivity specific optimisations.
* d29eb55 Thejas-bhat | Handling a case to avoid bringing faiss index to memory unnecessarily
* 30a47cd Aditi Ahuja | MB-62230 - More pre-filtering optimisations
> MB-62230, MB-63992: Upgrade zapx/v16

- go.mod
- go.sum
- search/collector/eligible.go
- search/collector/heap.go
- search/collector/list.go
- search/collector/slice.go
- search/collector/topn.go
- search_knn.go
This PR - 
1. Avoids creating document matches for the pre-filter phase, when IDs suffice. 
2. Re-uses document matches by adding them to the doc match pool after each hit.
> MB-62230 - Pre-filtering Optimisation

- search/query/multi_phrase.go
- search/query/phrase.go
- Without these API's, these queries are falsely recognised as `Non-Fieldable` queries.
> Add missing API's for a few queries

- search/query/fuzzy.go
- search/query/match.go
- search/query/match_phrase.go
- search/query/multi_phrase.go
- search/query/phrase.go
- search/searcher/search_fuzzy.go
- search/searcher/search_phrase.go
- search/searcher/search_phrase_test.go
- search_test.go
- The following queries can now automatically detect fuzziness based on the length of the terms:
- Match Query
- Fuzzy Query
- Match-Phrase Query
- Multi-Phrase Query
- Phrase Query
- In these queries, each term (whether in a multi-term query like Match or Phrase, or in a single-term query like Fuzzy can have its own edit distance based on its length. The edit distance is calculated as follows:
- For terms with 1 or 2 characters: edit distance = 0 (exact match)
- For terms with 3, 4, or 5 characters: edit distance = 1 (fuzzy match)
- For terms with more than 5 characters: edit distance = 2 (fuzzy match)
- This feature can be enabled using the `<query>.SetAutoFuzziness(<bool>)` API.
- Additionally, we've extended the functionality to query JSON parsing. You can specify fuzziness as either …
> MB-19243: Detect fuzziness automatically based on term length

- go.mod
- go.sum
- index_test.go
- search/searcher/search_fuzzy.go
- search/searcher/search_multi_term.go
- Added levenshtein distance calculation for fuzzy and wildcard searchers
- Added new implementations of certain functions to allow passing of edit distances per term
- Multiplied boosts by inverse of edit distance for score calculation
> MB-61640: Fuzzy Dynamic Scoring

- go.mod
- go.sum
To bring in:
* 60ebc9a Aditi Ahuja | Merge branch v16-trinity-couchbase (https://github.com/blevesearch/zapx/pulls/283)
* c85f4c5 Aditi Ahuja | MB-64360 - Guardrail fix for missing vectors (https://github.com/blevesearch/zapx/pulls/282)
> Use v16.1.9 for zapx/v16

- index_alias_impl.go
- pre_search.go
- search.go
- search/query/query.go
- search/query/query_test.go
- search_knn.go
- search_no_knn.go
- Refactor the presearch code path to make it more generic and extensible.
- Add an ExtractFields API for obtaining the set of fields applicable to a generic query.
- Add support for a new API to set the index mapping for an alias.
This is useful when an alias contains partitions of the same index, as the index 
mapping would be consistent across all indexes and can be inferred directly from 
the alias.
> Presearch Code Refactor

- index/scorch/snapshot_index.go
- index_test.go
+ Setting the default to 0 on account of the panics caught in the MB.
+ Firstly, refactor `FieldTFRCacheThreshold` to `fieldTFRCacheThreshold` for _some_ naming consistency here.
+ This threshold can be used to toggle recycling of TermFieldReaders on/off.
+ Couchbase users will have the ability to provide this setting within a JSON payload, which when interpreted into a `map[string]interface{}` will need to be interpreted as a `float64`.
+ Should library users set it as an `int` within the index config - we'll honor that setting as well.
> MB-64604: Fix interpreting scorch config: "fieldTFRCacheThreshold"

- .github/workflows/tests.yml
- index/scorch/snapshot_index.go
+ Setting the default to 0 on account of the panics caught in the MB.
+ Firstly, refactor FieldTFRCacheThreshold to fieldTFRCacheThreshold for some naming consistency here.
+ This threshold can be used to toggle recycling of TermFieldReaders on/off.
+ Couchbase users will have the ability to provide this setting within a JSON payload, which when interpreted into a map[string]interface{} will need to be interpreted as a float64.
+ Should library users set it as an int within the index config - we'll honor that setting as well.
> MB-64604: [BP] Fix interpreting scorch config: "fieldTFRCacheThreshold"

- index/scorch/snapshot_index.go
- index_test.go
```
|\
| * 5c536342 Abhi Dangeti | MB-64604: Remove unnecessary second map lookup (#2121)
| * 78cf7899 Abhi Dangeti | MB-64604: Fix interpreting scorch config: "fieldTFRCacheThreshold" (#2117)
| * 7d627b9f Aditi Ahuja | MB-64360 - Upgrade zapx v16 (#2107)
```
> MB-64604: Merge remote-tracking branch 'origin/trinity-couchbase' into 'master'

- go.mod
- go.sum
go-faiss:
* 2127bb0 Likith B | MB-64513: Removing modification of max codes based on filtered document size
> MB-64513: Upgrade blevesearch/go-faiss, zapx/v16 for fix

- analysis/lang/tr/stemmer_tr_test.go
**What this PR does:**
- Adds a test file for the Snowball Turkish stemmer.
- Tests various Turkish words to ensure proper stemming.
**Why this is useful:**
- Improves test coverage for Turkish language support in Bleve.
- Ensures the Snowball stemmer works as expected for Turkish words.
**Notes:**
- This PR only adds a test file and does not modify any existing functionality.
> Unit test for turkish stemmer

- search/scorer/scorer_knn.go
- search_knn_test.go
1. Changed weight of a kNN query to 1 to allow the boost value to kick in when computing query score.
Since the weight of only the kNN scorer is changed, this will not impact how boosting is calculated for other types of queries.
To reduce the kNN score relative to the FTS query score, set boost to <1.
2. Added a unit test which demonstrates boost increasing scores even for pure kNN queries(kNN + match none query).
> MB-64636 - Modified Weight for KNN Scorer

- docs/synonyms.md
- Add docs/synonyms.md to provide an overview on synonym search.
> Add synonym search documentation with detailed indexing and querying examples

- search/explanation.go
- search/scorer/scorer_disjunction.go
- search/search.go
- search/searcher/search_disjunction_heap.go
- search/searcher/search_disjunction_slice.go
- search_test.go
- Previously, the `PartialMatch` field was returned for every hit, but this caused confusion in complex queries involving disjunctions and match queries. As a result, we moved `PartialMatch` to the score explanation, where each subquery's explanation will include its own `PartialMatch`. This field is set only if the query uses the DisjunctionSearcher or scorer.
> Move PartialMatch field to Explanation struct and update related logic

- document/field_boolean.go
- document/field_ip.go
- go.mod
- go.sum
- index_impl.go
- search/query/ip_range.go
- IP fields were not returned in the search response, even when stored, because they were not 
handled in the `LoadAndHighlightFields` API.
- Requires https://github.com/blevesearch/bleve_index_api/pull/60
> Add IP field handling in LoadAndHighlightFields

- index/scorch/scorch.go
`index_bgthreads_active` indicates whether the background routines that maintain the index are busy doing some work. This means that the index hasn't converged to a steady state and there could be potential file segment merges or in-memory segment flushes still remaining. 
This stat is beneficial for the application layer to get better insight as to whether the index is doing some background work (which can have implications on the system's resource utilisation) or not.
> Introduce a new stat which indicates a bleve index's convergence

- geo/versus_test.go
- index/scorch/mergeplan/merge_plan_test.go
- index/scorch/scorch_test.go
- index/upsidedown/field_dict_test.go
- index/upsidedown/reader_test.go
- index/upsidedown/store/metrics/metrics_test.go
- index/upsidedown/upsidedown_test.go
- index_alias_impl_test.go
- index_test.go
- query_bench_test.go
- search/query/query_string_parser_test.go
- search/searcher/geoshape_contains_test.go
- search/searcher/geoshape_intersects_test.go
- search/searcher/geoshape_within_test.go
- search/searcher/search_boolean_test.go
- search/searcher/search_conjunction_test.go
- search/searcher/search_term_range_test.go
- search_test.go
- test/versus_score_test.go
- test/versus_test.go
Since I started using this project on my production workloads, I would like to contribute to the project.
This first contribution is focused on the easy part of cleaning the code according to the common `golang linters`, like `golangci-lint` and `gopls`.  To impact the less possible in my contribution I started with `_test.go files`, I fixed some of the easy ones, there are too many and many of these linters warnings come from old go code.
I hope this contribution starts helping and standardizing the code according to the golang version used.
> fix: linter warnings on test files

- geo/parse.go
- geo/parse_test.go
Geo's `extract3DCoordinates` does not validate input data which can cause malformed polygon data to cause a panic:
```
panic: reflect: call of reflect.Value.Index on map Value
panic({0x100a9e0c0?, 0x140001163a8?})
/opt/homebrew/opt/go/libexec/src/runtime/panic.go:770 +0x124
reflect.Value.Index({0x100a9ffe0?, 0x14000118c00?, 0x14000062c58?}, 0x1008913c8?)
/opt/homebrew/opt/go/libexec/src/reflect/value.go:1447 +0x170
github.com/blevesearch/bleve/v2/geo.extract3DCoordinates({0x100a9ffe0?, 0x14000118c00?})
/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/geo/parse.go:245 +0x12c
github.com/blevesearch/bleve/v2/geo.ExtractGeoShapeCoordinates({0x100a9ffe0?, 0x14000118c00?}, {0x100a24659, 0x7})
```
See: https://pkg.go.dev/reflect#Value.IsValid
> MB-65807: Graceful handling of non-conforming polygon data

- analysis/token/keyword/keyword.go
- index/scorch/reader_test.go
- index/upsidedown/row.go
- search/query/regexp.go
- search/searcher/search_conjunction.go
- search/searcher/search_disjunction_slice.go
- search/sort.go
- search/sort_test.go
Since I started using this project on my production workloads, I would like to contribute to the project.
This third delivery is still fixing easy stuff like:
- `golangci-lint run ./... | grep "S1001:"`  
- search/searcher/search_conjunction.go:53:2: S1001: should use copy(to, from) instead of a loop (gosimple)
- search/searcher/search_disjunction_slice.go:82:3: S1001: should use copy(to, from) instead of a loop (gosimple)
- `golangci-lint run ./... | grep "ineffectual assignment"`->
- search/sort.go:49:14: ineffectual assignment to ok (ineffassign)
- index/scorch/reader_test.go:72:2: ineffectual assignment to expectedCount (ineffassign)
- index/upsidedown/row.go:645:7: ineffectual assignment to arrayPositionsLen (ineffassign)
- `golangci-lint run ./... | grep "S1017:"`
- …
> fix: golangci-lint findings, third delivery

- index/scorch/scorch.go
- index/scorch/scorch_test.go
- If a malformed setting is used in the persistor/merger options, an async error is thrown leading to a crash loop in a live system.
- This PR adds a validation step to ensure that the options are valid before creating/opening the index.
> Validate scorch routine options when creating or opening a Bleve Index.

- index/scorch/merge.go
- index/scorch/mergeplan/merge_plan.go
This PR introduces a new option of `FloorSegmentFileSize` into the merge planner's algorithm which is used in the budget calculation. The budget calculation drives the merge planner to keep the actual number of file segments within a `budget`.
Currently the budget calculation is dependent on the number of documents however this doesn't translate well in terms of resource utilization when the per doc size - which directly translates to the segment file size, varies significantly across use-cases. The scoring mechanism is kept the same for now - this is because the factors involved in scoring a set of segments end up canceling out the per doc size factor. For eg the [nonDelRatio's](https://github.com/blevesearch/bleve/blob/deb523009e0232993086c00942b0eec08ad1c4e4/index/scorch/mergeplan/merge …
> MB-62182: Making the merge planner aware of segment file size

- go.mod
- go.sum
- index/scorch/optimize_knn.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_vr.go
- index/scorch/snapshot_vector_index.go
- search.go
- search/collector/eligible.go
- search/query/knn.go
- search/searcher/search_knn.go
- search_knn.go
- search_knn_test.go
- Refactor pre-filtered vector search to enhance performance and reduce memory footprint.
- Replace the current bitmap-based approach for calculating segment local document numbers with a more direct method, where the local document numbers are mapped directly to the segment ID during the execution of the eligible collector.
- Requires:
- https://github.com/blevesearch/bleve_index_api/pull/67
- https://github.com/blevesearch/zapx/pull/320
- https://github.com/blevesearch/go-faiss/pull/41
- https://github.com/blevesearch/faiss/pull/49
---------
> MB-65473: [BP] Refactor and Optimize Pre-Filtered Vector Search (#2169)

- index/scorch/merge.go
- index/scorch/persister.go
- This is applicable to concurrent persister algorithm (introduced in v2.5.0) - which is not _ON_ by default.
- In cases where the persister creates new file segments, the bolt file is supposed to be updated with the complete set of file segments. 
- However currently, while loading the index from the bolt source, there can be data loss issues because a set of segments associated with the root snapshot weren't tracked in the bolt file and hence wouldn't be loaded from the disk.
- Note that the live index doesn't have issues because the root would track the live persisted segments and point to the corresponding files. 
- Also added some better code comments
> MB-60971: update the bolt with the correct file segments

- index_alias_impl.go
- If any index participating in a presearch returns an error, the entire presearch is considered failed, as partial results are not allowed for maintaining query consistency and accuracy.
- Previously, even though no hits were returned in such cases, the status could incorrectly indicate that some indexes succeeded—suggesting partial results existed when they didn't.
- This PR fixes the inconsistency by setting `status.Failed = status.Total` and `status.Successful = 0`, ensuring the status accurately reflects the absence of results.
> MB-66271: Fix presearch result status on errors

- go.mod
- go.sum
- index/scorch/snapshot_index.go
- index/upsidedown/index_reader.go
- index_impl.go
- search/collector/search_test.go
- search/searcher/search_term.go
- cache a map which maps the field to its cardinality value so that we don't create the fieldDict everytime
- Furthermore in the case all the threads have a cache miss, use the write lock to make sure that we create the fieldDict only once to minimize garbage. 
- Use a separate mutex construct so that the contention is localised to the metrics gathering and doesn't affect the other threads' TFR generation.
- https://github.com/blevesearch/bleve_index_api/pull/68
> MB-66295: avoid redundant calculation of bm25 metrics

- index/scorch/optimize_knn.go
- index_alias_impl.go
- index_impl.go
- index_test.go
- search/query/query.go
- search/util.go
Since I started using this project on my production workloads, I would like to contribute to the project.
This fourth delivery is still fixing easy stuff like:
- minor formatting changes
- `golangci-lint run ./... | grep "SA1029"` 
- index_impl.go:651:31: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
- index_impl.go:642:32: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
- index_impl.go:657:32: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
- index_impl.go:676:31: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
- …
> fix: golangci-lint findings, fourth delivery

- go.mod
- go.sum
This commit updates our fork to use the latest from golang/geo (commits as of 2025/04/16).
> Upgrade to blevesearch/geo@v0.2.0

- index/scorch/event.go
- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/rollback_test.go
- Currently because of the time-series based checkpointing mechanism, there can be edge cases where we don't end up protecting the very latest snapshot that's there in the bolt file. 
- This can cause some serious issues along the persister path, where the newly created file segments that's part of the new snapshot written to bolt can potentially get cleaned up when the purge code `removeOldData` is invoked. If there were a backup operation `indexReader.CopyTo()` to be performed just after this purge operation, the latest root still has a pointer to the file segment but the underlying file itself would have been purged because its not part of `ineligibleForRemoval` structure and also the corresponding bolt entry would have been deleted.
- The issue highlighted has also been unit tested …
> MB-66163: always protect the latest snapshot within bolt

- index/scorch/event.go
- index/scorch/merge.go
- index/scorch/persister.go
- index/scorch/rollback_test.go
Backporting #2183 for couchbase 7.6.x release cycle builds.
> [BP] MB-66163: always protect the latest snapshot within bolt

- index/scorch/persister.go
- index/scorch/rollback_test.go
- the checkpointing mechanism considers snapshots which fall within the `numSnapshotsToKeep * rollbackSamplingInterval` duration window. The snapshots outside this window are purged. 
- Under sparse mutation scenario for eg, when the workload pattern in such that it results in seldomly persisting snapshots that too outside this duration window - we could end up purging ALL those snapshots which makes the system fallback to preserving the latest snapshots
- For a better partial rollback behaviour, we retain `rollbackRetentionFactor` worth of snapshots out of this duration window such that the cost of rebuilding the index from scratch is avoided. 
- This PR fixes the decision logic involved in the scenario pointed and tracks the previous checkpoints while opening back the index as well.
> MB-66163: fix checkpointing mechanism under sparse mutation scenarios 

- index/scorch/persister.go
- index/scorch/rollback_test.go
Backporting #2186 to couchbase 7.6.x release cycle
> [BP] MB-66163: fix checkpointing mechanism under sparse mutation scenarios

- index_impl.go
- search/searcher/search_term.go
- search/util.go
- Separates the use of `BM25PreSearchDataKey` (for pre-search data) and introduces `BM25StatsKey` for passing BM25 stats via context, similar to the existing `SynonymPreSearchDataKey` vs. `FieldTermSynonymMapKey` pattern. This improves clarity and consistency in key usage.
> Refactor BM25 context key usage

- index_impl.go
- Previously, the `searches` stat was only incremented at the end of the second phase in two-phase searches.
- If the search request was satisfied during the presearch phase and the second phase was skipped, the `searches` stat was not incremented.
- This PR fixes the issue by incrementing the stat at the end of the presearch phase itself, ensuring it correctly reflects the number of searches whether the request is satisfied in the first phase or requires both phases.
- Also fixes the `searchTime` stat to ensure accurate values for both single-phase and two-phase searches.
> Fix: Increment `searches` stat correctly during presearch phase

- analysis/char/asciifolding/asciifolding.go
- analysis/char/asciifolding/asciifolding_test.go
- analysis/datetime/iso/iso.go
- analysis/datetime/iso/iso_test.go
- analysis/datetime/percent/percent.go
- analysis/datetime/percent/percent_test.go
- analysis/lang/cjk/cjk_bigram.go
- analysis/lang/cjk/cjk_bigram_test.go
- index/scorch/merge_test.go
- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_test.go
- mapping/document.go
- mapping/field.go
- search/sort.go
Since I started using this project on my production workloads, I would like to contribute to the project.
__NOTES:__
- In the cases where I can use a `unit test` to test the code, I will do it. The unit test I added was created by `Github Copilot Agent` using the model `Gemini 2.5 Pro`, and most of them were adapted by me.
- Some of the improvements I made are not directly related to the `golangci-lint` findings, but I believe they are important for the project. All of them were proposed by `Github Copilot Agent` using the model `Gemini 2.5 Pro`, but I modified most of them so that they wouldn't alter  the code too much and facilitate the `code review`.
This delivery improves two golangci-lint findings:
1. `S1023:` redundant break statement (staticcheck)
2. `QF1003:` could use tagged …
> fix: golangci-lint findings, fifth delivery

- document/field_geoshape.go
- document/field_vector.go
- If a field mapping for a vector or geoshape has the `Index` option set to `false`, the field is still indexed because the current code incorrectly always overrides this option to `true`.
- This behavior has been fixed by ensuring that the Index option is not overridden and the field is only indexed if explicitly allowed by the user-specified Index setting.
> Bug Fix: Prevent Indexing of `vector` and `geoshape` fields when `Index` option is `False`

- search/query/knn.go
- search_knn.go
- search_knn_test.go
- Previously, filter queries were not validated during the KNN request validation phase, which could lead to unexpected filter query behavior. This has been fixed by adding proper validation.
- Also fixed an issue where errors during JSON unmarshalling of invalid filter queries were being silently ignored.
> Bug Fix: Validate KNN Filter Queries

- index/scorch/snapshot_index.go
- index/scorch/snapshot_index_str.go
- Fixed a bug where legacy segment plugins caused an infinite loop during query execution; the synonym set is now correctly left empty, triggering fallback to basic FTS search without synonyms
- Refactored related code for improved clarity and performance
> Fix: Prevent infinite loop in synonym search with legacy (`<v16`) segment plugins

- CONTRIBUTING.md
- README.md
- SECURITY.md
- docs/scoring.md
- docs/vectors.md
- geo/README.md
- index/scorch/README.md
- Used a tool to identify and fix lint errors in all the markdown files.
- Fixed code examples to use only the exported bleve package (and not internal ones)
- Formatted JSON and code examples throughout
- Added Hybrid Search example to vectors.md
> Fix lint errors in markdown files

- index/scorch/optimize.go
- index/scorch/snapshot_index_tfr.go
- index/scorch/unadorned.go
- search/searcher/search_disjunction_test.go
- When using the `Advance()` API on an `IndexSnapshotTermFieldReader`, a special replacement mechanism is applied during a `Rewind`— when the requested document ID is behind the current document ID pointed to by the reader. In such cases, the object itself gets replaced.  
- However, this approach fails when the `IndexSnapshotTermFieldReader` is created by the `optimizeCompositeSearcher` method, which is used to construct optimized `conjunction` or `disjunction` searchers.  
- The issue arises because the `unadornedTermFieldReader` is initialized with the `term` set to `<optimization-type>` and `field` set to `*`. As a result, calling `Advance()` renders the entire `TFR` unusable, as it gets replaced by a dummy `TFR` that no longer functions.  
- This problem occurs specifically when …
> BugFix: Fixed Advance() API implementation in Optimized Composite Searchers

- index/scorch/mergeplan/merge_plan.go
- index/scorch/mergeplan/merge_plan_test.go
- As an edge case, the segment layout can be such that the merge planning generates tasks having only a single non-empty segment. 
- When this task is processed and introduced into the scorch system, the root doesn't change and you'd be stuck in an infinite loop because the same segment is still present in the system and the plan keeps generating the task with the same single segment, which doesn't converge the index to a steady state.
> MB-66112: fix an edge case related to index convergence

- docs/pagination.md
Added short documentation about pagination in Bleve
> Add pagination documentation

- search/query/boolean.go
- search/query/query.go
- search/searcher/search_filter.go
- search/searcher/search_geoboundingbox.go
- search/searcher/search_geopointdistance.go
- search/searcher/search_geopolygon.go
- search/searcher/search_geoshape.go
- search_test.go
- Add a Filter query for Boolean queries, which filters the document set returned by the
Boolean query itself.
- The filter query does not affect scores, and any document returned by the Boolean query
must also satisfy the filter query.
- The key difference between using a Filter query and placing an equivalent query in the
Must clause is that queries in the Must clause contribute to the score. The Filter
query is intended purely for filtering purposes without modifying the document scores
set by the base Boolean query.
- Requires a Bug Fix (https://github.com/blevesearch/bleve/pull/2146)
to allow for the usage of the Advanced API in case the FilterQuery is an optimized
composite searcher.
- Resolves https://github.com/blevesearch/bleve/issues/2037
> MB-65170: Add filter support to BooleanQuery
